"""สตอรี่บอร์ดชุดที่ 2 — 5 เรื่อง × ไทย/อังกฤษ (4 ก.ย. 2569) — storyboard.py นำเข้าไฟล์นี้แล้วต่อท้าย CLIPS/PALETTE

กติกาเดียวกับชุดนำร่อง + กติกาที่ตกลงเพิ่ม 4 ก.ย.:
  · ศูนย์ฯ เป็นผู้เล่า ไม่ใช่ผู้ทำ — ประธานของกริยาวิจัยคือ ทีมวิจัย/คณะผู้วิจัย/ผู้วิจัย
  · ข้อความบนจอเว้นวรรคตามหน่วยความหมาย · เลขในเสียงพากย์เป็นคำอ่าน · ไม่ใช้ ๆ ฯ ในเสียง
  · ภาพใหม่นับวัตถุไม่เกินสี่ชิ้น · ฉาก hook ใช้ภาพประจำบทความที่มีอยู่แล้ว · ฉากข้อควรระวังใช้ดอกจันกระดาษประจำชุด
  · ข้อเท็จจริงทุกข้อตรงกับบทสรุปบนเว็บ (paperSummaries.ts) ซึ่งตรวจกับตัวบทความแล้ว
  · ไม่ระบุชื่อบุคคล/องค์กรที่ถูกวิจารณ์ (กติกาข้อ 5) — คลิปแชตบอตไม่เอ่ยชื่อผลิตภัณฑ์ในเสียง
"""

CLOSING2 = {
    "th": "นี่คือหนึ่งในงานวิจัยของศูนย์คอมอินโน คณะนิเทศศาสตร์ จุฬาลงกรณ์มหาวิทยาลัย อ่านบทสรุปและบทความฉบับเต็ม พร้อมช่องทางร่วมงานกับเรา ได้ที่ คอมอินโนเซ็นเตอร์ ดอท คอม",
    "en": "This is one of the studies from the ComInno Center, Faculty of Communication Arts, Chulalongkorn University. Read the summary, the full article, and how to work with us at cominnocenter dot com.",
}

ASTERISK = "ONE folded paper asterisk: exactly three short paper strips of equal length crossing at a single centre point to form a six-armed star, lying flat at the centre of the frame. One object, nothing else."

# คู่สีอ่านจากภาพประจำบทความของแต่ละเรื่อง (วัดจากพิกเซลที่อิ่มสี ไม่ได้กะด้วยตา) เพื่อให้ภาพใหม่กลมกลืนกับภาพ hook
PALETTE2 = {
    "aicite": {"object": "dusty rose pink", "shadow": "olive green", "obj_hex": "#B8547A", "sh_hex": "#7D8B57",
               "shadow_style": "clean flat-edged shadows to the lower right rendered as solid olive-green shapes, like cut paper rather than soft photographic shadows"},
    "vr360": {"object": "deep magenta pink", "shadow": "soft sky blue", "obj_hex": "#C0446E", "sh_hex": "#A0CAE6",
              "shadow_style": "clean flat-edged shadows to the lower right rendered as solid soft-sky-blue shapes, like cut paper rather than soft photographic shadows"},
    "cannabis": {"object": "deep wine magenta", "shadow": "sage green", "obj_hex": "#72273F", "sh_hex": "#8A9A5B",
                 "shadow_style": "clean flat-edged shadows to the lower right rendered as solid sage-green shapes, like cut paper rather than soft photographic shadows"},
    "negwom": {"object": "warm amber-yellow", "shadow": "coral pink", "obj_hex": "#EEBB60", "sh_hex": "#E88569",
               "shadow_style": "clean flat-edged shadows to the lower right rendered as solid coral-pink shapes, like cut paper rather than soft photographic shadows"},
    "migrant": {"object": "olive green", "shadow": "sky blue", "obj_hex": "#949A5E", "sh_hex": "#7EABCA",
                "shadow_style": "soft sky-blue shadows to the lower right, as in a real studio photograph of paper on a table"},
}


def closing():
    return {"role": "closing", "secs": (14, 14), "image": "logo", "narr": CLOSING2, "label": None, "text": None,
            "visual_th": "การ์ดปิดประจำชุด + ชื่อผู้เขียนทุกคน (ไม่ต้องเจนภาพ)", "subject": None}


def caveat(narr_th, narr_en, text_th, text_en, secs=(9, 9)):
    return {"role": "caveat", "secs": secs, "image": "new", "narr": {"th": narr_th, "en": narr_en},
            "label": {"th": "ข้อควรระวัง", "en": "One caution"}, "text": {"th": text_th, "en": text_en},
            "visual_th": "ดอกจันกระดาษพับหนึ่งดอก — สัญลักษณ์ประจำฉากข้อควรระวัง (คู่สีของคลิปนี้)", "subject": ASTERISK}


CLIPS2 = [
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "aicite", "batch": 2,
        "slug": "ai-generated-citations-students",
        "name_th": "แชตบอตกับการอ้างอิงที่ไม่มีอยู่จริง",
        "name_en": "Chatbots and the citations that never existed",
        "label": {"th": "งานวิจัย · การรู้เท่าทันสื่อ", "en": "Research · Media literacy"},
        "scenes": [
            {
                "role": "hook", "secs": (8, 8), "image": "existing",
                "narr": {"th": "ให้นิสิตหาคำตอบเรื่องวิชาการที่ไม่คุ้น หนึ่งในห้าหันไปถามแชตบอต … แล้วสิ่งที่มันยกมาอ้าง มีจริงไหม",
                         "en": "Give students an unfamiliar academic question, and one in five asks a chatbot … but does what it quotes actually exist?"},
                "label": {"th": "งานวิจัย · การรู้เท่าทันสื่อ", "en": "Research · Media literacy"},
                "text": {"th": "นิสิตหนึ่งในห้า ค้นข้อมูลวิชาการจากแชตบอต และคำพูดที่มันยกมาอ้าง ไม่มีอยู่จริงสักประโยค",
                         "en": "One student in five researched an academic question with a chatbot. Not one of the quotations it supplied exists"},
                "visual_th": "ภาพประจำบทความ (มีแล้ว): กรอบรูปประดับสวยงามที่ข้างในว่างเปล่า — รูปแบบของการอ้างอิงที่ครบ แต่ไม่มีเนื้อหาจริง",
                "subject": None,
            },
            {
                "role": "method", "secs": (16, 16), "image": "new",
                "narr": {"th": "ผู้วิจัยให้นิสิตปริญญาตรีจุฬาฯ สองร้อยสี่สิบคน ทำโจทย์เดียวกัน คือค้นอย่างเร็วว่านักปรัชญาคนหนึ่งคิดอย่างไรกับแนวคิดหนึ่ง แล้วยกข้อความจากงานเขียนของเขามาหนึ่งประโยค ใช้แหล่งไหนก็ได้ จากนั้นผู้วิจัยเอาทุกข้อความที่นิสิตยกมา ไปไล่ตรวจกับต้นฉบับทีละข้อ",
                         "en": "The researcher gave two hundred and forty Chulalongkorn undergraduates the same task: find out quickly what a particular philosopher thought about one idea, and back it up with a quotation from his own writing, using any source they liked. Then every quotation the students handed in was checked against the original work, line by line."},
                "label": {"th": "ทำอะไร", "en": "What was done"},
                "text": {"th": "นิสิต 240 คน · โจทย์เดียวกัน · ใช้แหล่งใดก็ได้ · ตรวจทุกข้อความกับต้นฉบับ",
                         "en": "240 students · one task · any source · every quotation checked against the original"},
                "visual_th": "กระดาษสามแผ่นซ้อนกันหลวมๆ มีแว่นขยายกระดาษหนึ่งอันวางทับ — การไล่ตรวจกับต้นฉบับ",
                "subject": "exactly THREE sheets of paper fanned in a loose stack, and ONE paper magnifying glass (a flat ring with a short straight handle) lying on top of them. Four pieces in total. Nothing else.",
            },
            {
                "role": "finding", "secs": (12, 12), "image": "new",
                "narr": {"th": "กูเกิลยังเป็นแหล่งแรกของคนส่วนใหญ่ ราวห้าสิบเจ็ดเปอร์เซ็นต์ แต่ยี่สิบสองเปอร์เซ็นต์เลือกแชตบอตเป็นแหล่งหลัก มากกว่าวิกิพีเดียเสียอีก เหตุผลที่ให้คือ ได้คำตอบตรงและกระชับ",
                         "en": "Google was still most people's first stop, at fifty-seven percent. But twenty-two percent chose a chatbot as their main source, more than Wikipedia. Their reason: the answer was direct and short."},
                "label": {"th": "พบอะไร", "en": "What was found"},
                "text": {"th": "กูเกิล 57% · แชตบอต 22% · วิกิพีเดีย 21%", "en": "Google 57% · chatbot 22% · Wikipedia 21%"},
                "visual_th": "แท่งกระดาษสามแท่งตั้งเรียงกัน แท่งแรกสูง อีกสองแท่งเตี้ยเกือบเท่ากัน",
                "subject": "exactly THREE upright paper columns standing side by side in a row: the first tall, the other two short and almost equal in height. Three objects, nothing else.",
            },
            {
                "role": "finding", "secs": (16, 16), "image": "new",
                "narr": {"th": "คำตอบสามสิบเจ็ดชิ้น มีข้อความที่บอกว่ายกมาจากงานของนักปรัชญาคนนั้น พร้อมชื่อหนังสือ พร้อมปีที่พิมพ์ อ่านแล้วเหมือนการอ้างอิงวิชาการทุกประการ แต่พอไปเปิดต้นฉบับ ไม่มีข้อความไหนอยู่ในนั้นเลย ทั้งหมดเป็นประโยคที่ระบบแต่งขึ้น เลียนสำนวนและแนวคิดของเขา",
                         "en": "Thirty-seven answers contained a quotation attributed to that philosopher, complete with the title of the book and the year it was published. Everything about them looked like a scholarly citation. Open the original, and not one of those sentences is there. All of them were written by the system, imitating his style and his ideas."},
                "label": {"th": "ข้อความที่ไม่มีอยู่จริง", "en": "The quotations that never existed"},
                "text": {"th": "37 ข้อความ มีชื่อหนังสือและปีครบ · ไม่มีข้อความใด อยู่ในต้นฉบับจริง",
                         "en": "37 quotations with book title and year · none of them exists in the original"},
                "visual_th": "หนังสือกระดาษเปิดกางอยู่ กับกรอบคำพูดกระดาษที่ลอยอยู่เหนือมัน ข้างในว่างเปล่า",
                "subject": "ONE paper book lying open with two blank pages, and ONE paper speech bubble floating just above it, its inside completely blank. Two objects, nothing else.",
            },
            {
                "role": "finding", "secs": (9, 9), "image": "new",
                "narr": {"th": "ตอนชี้แจงหลังการทดลอง นิสิตทั้งสามสิบเจ็ดคนบอกว่ามั่นใจ ว่ากำลังอ้างข้อความจริง ไม่มีใครเอะใจว่าต้องกลับไปตรวจ",
                         "en": "At the debriefing, all thirty-seven students said they were confident they had been quoting the real thing. Not one had thought to check."},
                "label": {"th": "ความมั่นใจ", "en": "The confidence"},
                "text": {"th": "ทั้ง 37 คน มั่นใจว่าอ้างของจริง · ไม่มีใครกลับไปตรวจ",
                         "en": "All 37 were confident it was real · none went back to check"},
                "visual_th": "โบว์รางวัลกระดาษติดอยู่บนแผ่นกระดาษเปล่า — ตราแห่งการรับรองบนหน้าที่ไม่มีอะไร",
                "subject": "ONE blank sheet of paper lying flat, with ONE paper award rosette (a pleated circle with two short ribbon tails) pinned near its top corner. Two objects, nothing else.",
            },
            {
                "role": "lesson", "secs": (20, 20), "image": "new",
                "narr": {"th": "บทเรียนคือ ปัญหาไม่ได้อยู่ที่ปัญญาประดิษฐ์ตอบผิด แต่อยู่ที่รูปแบบของคำตอบ มีชื่อหนังสือ มีปี มีสำนวนของเจ้าของงาน ซึ่งในโลกวิชาการคือสัญญาณว่าตรวจมาแล้ว ผู้วิจัยจึงไม่ได้เสนอให้ห้ามใช้ แต่เสนอให้แพลตฟอร์มบอกข้อจำกัดของตัวเองให้ชัด และให้สถาบันการศึกษาสอนการตรวจย้อนกลับไปถึงต้นฉบับ เป็นทักษะรู้เท่าทันสื่อชุดใหม่",
                         "en": "The lesson is that the problem is not that the AI got it wrong. It is the form of the answer: a title, a year, the author's own cadence, which in academic life is the signal that checking has been done. So the proposal is not a ban. It is for platforms to state plainly what they cannot verify, and for universities to teach tracing a claim back to its source as a new media-literacy skill."},
                "label": {"th": "บทเรียน", "en": "The lesson"},
                "text": {"th": "คำตอบดูเหมือนตรวจแล้ว · แพลตฟอร์มต้องบอกข้อจำกัด · สอนการตรวจย้อนกลับ ถึงต้นฉบับ",
                         "en": "The answer looks verified · platforms must state their limits · teach tracing back to the source"},
                "visual_th": "ลูกศรกระดาษโค้งย้อนกลับมาชี้ที่หนังสือกระดาษเล่มปิด — ตรวจย้อนกลับถึงต้นฉบับ",
                "subject": "ONE closed paper book lying flat, and ONE long paper arrow that sweeps out and curves back on itself to point at the book. Two objects, nothing else.",
            },
            caveat("ข้อควรระวัง งานนี้ใช้โจทย์เดียว ในมหาวิทยาลัยเดียว และเก็บข้อมูลช่วงที่แชตบอตยังค้นเว็บไม่ได้ สัดส่วนที่เห็นจึงเป็นภาพของช่วงนั้น ไม่ใช่ตัวเลขปัจจุบัน",
                   "One caution: this was one task at one university, gathered when chatbots could not yet search the web. The proportions are a snapshot of that moment, not today's figures.",
                   "โจทย์เดียว มหาวิทยาลัยเดียว · เก็บข้อมูลก่อนแชตบอตค้นเว็บได้ · สัดส่วนเป็นภาพของช่วงนั้น",
                   "One task, one university · before chatbots could search the web · a snapshot, not today's figures"),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "vr360", "batch": 2,
        "slug": "vr360-neck-shoulder-pain",
        "name_th": "วิดีโอ 360 องศาสอนยืดคอบ่า",
        "name_en": "A 360-degree video for neck and shoulder pain",
        "label": {"th": "งานวิจัย · การสื่อสารสุขภาพ", "en": "Research · Health communication"},
        "scenes": [
            {
                "role": "hook", "secs": (8, 8), "image": "existing",
                "narr": {"th": "ปวดคอปวดบ่าจากการทำงาน ยืดคลายได้ด้วยตัวเอง แต่จะสอนท่ายืดผ่านวิดีโอแบบไหน ให้คนตั้งใจดูจริง",
                         "en": "Neck and shoulder pain from work can be eased with stretches. But what kind of video actually holds people's attention while it teaches them?"},
                "label": {"th": "งานวิจัย · การสื่อสารสุขภาพ", "en": "Research · Health communication"},
                "text": {"th": "สอนยืดคอบ่าด้วยวิดีโอ 360 องศา ผู้หญิงวัยทำงานบอกว่า ดูแล้วจดจ่อกว่าวิดีโอธรรมดา",
                         "en": "A 360-degree video teaching neck and shoulder stretches held working women's attention better than ordinary video"},
                "visual_th": "ภาพประจำบทความ (มีแล้ว): แผ่นสี่เหลี่ยมแบนใบเล็ก เทียบกับวงแหวนที่โอบรอบจุดกึ่งกลาง — วิดีโอจอแบน กับวิดีโอที่ล้อมรอบตัว",
                "subject": None,
            },
            {
                "role": "method", "secs": (14, 14), "image": "new",
                "narr": {"th": "คณะผู้วิจัยคัดผู้หญิงวัยทำงานยี่สิบคน อายุยี่สิบห้าถึงสี่สิบปี ที่เสี่ยงต่อกลุ่มอาการปวดกล้ามเนื้อและพังผืด ให้ชมวิดีโอสามร้อยหกสิบองศาที่สอนท่ายืดคอและบ่า แล้วเก็บความเห็นด้วยแบบสอบถาม และการสัมภาษณ์เชิงลึก",
                         "en": "The research team recruited twenty working women aged twenty-five to forty, all at risk of myofascial pain syndrome, had them watch a three-sixty-degree video teaching neck and shoulder stretches, and then gathered their views through questionnaires and in-depth interviews."},
                "label": {"th": "ทำอะไร", "en": "What was done"},
                "text": {"th": "ผู้หญิงวัยทำงาน 20 คน · อายุ 25–40 ปี · ชมวิดีโอ 360 องศา · แบบสอบถาม และสัมภาษณ์เชิงลึก",
                         "en": "20 working women · aged 25–40 · watched a 360° video · questionnaire and in-depth interviews"},
                "visual_th": "กระดานหนีบกระดาษ (แบบสอบถาม) กับกรอบคำพูดกระดาษ (สัมภาษณ์) วางคู่กัน",
                "subject": "ONE paper clipboard (a flat upright rectangle with a small clip at the top, its face blank) and ONE paper speech bubble lying beside it. Two objects, nothing else.",
            },
            {
                "role": "finding", "secs": (11, 11), "image": "new",
                "narr": {"th": "ผลออกมาชัด ผู้ชมพึงพอใจกับวิดีโอในระดับสูงมาก และเห็นด้วยอย่างยิ่งว่า วิดีโอสามร้อยหกสิบองศาทำให้จดจ่อกับสิ่งตรงหน้า มากกว่าวิดีโอธรรมดา",
                         "en": "The result was clear. Viewers were extremely satisfied, and strongly agreed that the three-sixty video made them concentrate on what was in front of them far more than ordinary video does."},
                "label": {"th": "พบอะไร", "en": "What was found"},
                "text": {"th": "พึงพอใจระดับสูงมาก · จดจ่อกว่าวิดีโอธรรมดา", "en": "Extremely satisfied · more focused than ordinary video"},
                "visual_th": "กรวยกระดาษเหมือนลำแสงส่องไปที่ลูกบาศก์กระดาษก้อนเล็ก — ความจดจ่อ",
                "subject": "ONE long paper cone lying on its side like a beam of light, its wide end open toward ONE small paper cube a short distance away. Two objects, nothing else.",
            },
            {
                "role": "finding", "secs": (8, 8), "image": "new",
                "narr": {"th": "ผู้ชมบอกว่ารู้สึกเหมือนอยู่ในเหตุการณ์ที่กำลังดู และเลือกได้เองว่าจะมองไปทางไหน",
                         "en": "They said they felt part of the scene they were watching, and free to choose where to look."},
                "label": {"th": "รู้สึกอย่างไร", "en": "How it felt"},
                "text": {"th": "รู้สึกอยู่ในเหตุการณ์ · เลือกทิศทางการมองได้เอง", "en": "Felt inside the scene · free to choose where to look"},
                "visual_th": "โดมกระดาษครึ่งทรงกลม มีลูกบาศก์กระดาษก้อนเล็กอยู่ตรงกลาง — ถูกล้อมรอบด้วยภาพ",
                "subject": "ONE paper hemisphere dome, cut open at the front so its inside is visible, with ONE small paper cube resting at its centre. Two objects, nothing else.",
            },
            {
                "role": "finding", "secs": (10, 10), "image": "new",
                "narr": {"th": "ส่วนตัวเนื้อหา ผู้ชมเห็นว่าน่าสนใจและเรียบเรียงดี ผู้นำเสนอ สถานที่ โทนของงาน และความยาว อยู่ในระดับที่เหมาะสม",
                         "en": "As for the content itself, viewers found it interesting and well organised, with the presenter, the setting, the tone and the length all judged about right."},
                "label": {"th": "เนื้อหา", "en": "The content"},
                "text": {"th": "เนื้อหาน่าสนใจ เรียบเรียงดี · ผู้นำเสนอ สถานที่ โทน ความยาว เหมาะสม",
                         "en": "Interesting, well organised · presenter, setting, tone and length about right"},
                "visual_th": "แผ่นกระดาษสี่เหลี่ยมสี่แผ่นขนาดเท่ากัน วางเรียงเป็นแถวเรียบร้อย — องค์ประกอบที่ลงตัว",
                "subject": "exactly FOUR small square paper tiles of identical size lying flat in one neat straight row with equal gaps. Four objects, nothing else.",
            },
            {
                "role": "lesson", "secs": (16, 16), "image": "new",
                "narr": {"th": "ข้อสรุปของคณะผู้วิจัยคือ เมื่อเนื้อหาออกแบบมาดีพอ กล้องสามร้อยหกสิบองศาราคาถูกลงขนาดนี้ และยูทูบเปิดให้อัปโหลดฟรี วิดีโอแบบนี้ก็เป็นวิธีดูแลอาการปวดที่ใช้ได้จริงในทางปฏิบัติ องค์กรที่อยากทำสื่อสุขภาพแบบนี้ ไม่ต้องรอห้องแล็บหรืองบก้อนใหญ่อีกต่อไป",
                         "en": "The team's conclusion: with well-designed content, cameras this cheap, and YouTube hosting the format for free, three-sixty video is a practical way to help people manage pain. An organisation that wants to make health media like this no longer needs a lab or a big budget."},
                "label": {"th": "บทเรียน", "en": "The lesson"},
                "text": {"th": "เนื้อหาดี + กล้องราคาถูก + ยูทูบฟรี = สื่อสุขภาพที่ทำได้จริง ไม่ต้องรอห้องแล็บ หรืองบก้อนใหญ่",
                         "en": "Good content + cheap cameras + free hosting = practical health media, no lab or big budget needed"},
                "visual_th": "กล้องกระดาษตัวเล็ก (กล่องกับเลนส์ทรงกระบอก) วางข้างเหรียญกระดาษหนึ่งเหรียญ — ต้นทุนต่ำ",
                "subject": "ONE small paper camera (a box with a short paper cylinder for a lens on its front) and ONE flat paper coin lying beside it. Two objects, nothing else.",
            },
            caveat("ข้อควรระวัง งานนี้ศึกษาทัศนคติของผู้ชมยี่สิบคน ไม่ได้วัดว่าอาการปวดลดลงจริงหรือไม่ และเก็บข้อมูลตั้งแต่ปีสองพันห้าร้อยหกสิบ",
                   "One caution: this study looked at the attitudes of twenty viewers. It did not measure whether pain actually went down, and the data dates from twenty seventeen.",
                   "วัดทัศนคติ 20 คน · ไม่ได้วัดว่าอาการปวดลดลง · ข้อมูลปี 2560",
                   "Attitudes of 20 viewers · pain relief itself not measured · data from 2017"),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "cannabis", "batch": 2,
        "slug": "thailand-image-cannabis-youtube",
        "name_th": "ภาพไทยบนยูทูบหลังปลดล็อกกัญชา",
        "name_en": "Thailand on YouTube after cannabis legalisation",
        "label": {"th": "งานวิจัย · ภาพลักษณ์ประเทศ", "en": "Research · Nation image"},
        "scenes": [
            {
                "role": "hook", "secs": (7, 7), "image": "existing",
                "narr": {"th": "หลังไทยปลดล็อกกัญชา โลกพูดถึงเราอย่างไรบนยูทูบ … และเล่าครบไหม",
                         "en": "After Thailand legalised cannabis, how did the world talk about us on YouTube … and did the story come out whole?"},
                "label": {"th": "งานวิจัย · ภาพลักษณ์ประเทศ", "en": "Research · Nation image"},
                "text": {"th": "โลกมองไทยหลังปลดล็อกกัญชา ในแง่บวกท่วมท้น แต่แทบไม่มีคลิปไหน เตือนนักท่องเที่ยว เรื่องกฎหมายบ้านตัวเอง",
                         "en": "The world's picture of Thailand after cannabis legalisation was overwhelmingly positive. Almost none of it mentioned the law back home"},
                "visual_th": "ภาพประจำบทความ (มีแล้ว): กองแผ่นกลมสูงลิ่วกองหนึ่ง เทียบกับกองจิ๋ว — คลิปแง่บวกมหาศาล กับคลิปที่เตือนนิดเดียว",
                "subject": None,
            },
            {
                "role": "method", "secs": (16, 16), "image": "new",
                "narr": {"th": "ทีมวิจัยวิเคราะห์คลิปยูทูบห้าสิบเจ็ดคลิป ที่เผยแพร่สามเดือนก่อนและสามเดือนหลังวันปลดล็อก เก้ามิถุนายนสองพันห้าร้อยหกสิบห้า เป็นคลิปข่าวสามสิบคลิป และวล็อกยี่สิบเจ็ดคลิป โดยดูว่าเรื่องเล่าถูกวางกรอบอย่างไร ใครเป็นคนพูด และภาพประเทศออกมาแบบไหน",
                         "en": "The research team analysed fifty-seven YouTube clips published in the three months before and the three months after legalisation on the ninth of June twenty twenty-two: thirty news segments and twenty-seven vlogs, looking at how the story was framed, who did the talking, and what image of the country came through."},
                "label": {"th": "ทำอะไร", "en": "What was done"},
                "text": {"th": "57 คลิป · 3 เดือนก่อนและหลัง 9 มิถุนายน 2565 · ข่าว 30 คลิป · วล็อก 27 คลิป",
                         "en": "57 clips · 3 months either side of 9 June 2022 · 30 news · 27 vlogs"},
                "visual_th": "กองการ์ดกระดาษแบนสองกอง กองหนึ่งสูงกว่าอีกกองเล็กน้อย — ข่าวกับวล็อก",
                "subject": "exactly TWO neat stacks of flat rectangular paper cards standing side by side, one stack slightly taller than the other. Two objects, nothing else.",
            },
            {
                "role": "finding", "secs": (11, 11), "image": "new",
                "narr": {"th": "ความสนใจพุ่งขึ้นแล้วหายเร็ว แปดสิบเอ็ดเปอร์เซ็นต์ของคลิปออกหลังวันประกาศ เดือนมิถุนายนเดือนเดียวมียี่สิบเอ็ดคลิป พอถึงกันยายนเหลือแค่สองคลิป",
                         "en": "Attention spiked and faded fast. Eighty-one percent of the clips came after the announcement. June alone had twenty-one; by September there were two."},
                "label": {"th": "พบอะไร", "en": "What was found"},
                "text": {"th": "81% ออกหลังวันประกาศ · มิถุนายน 21 คลิป · กันยายน 2 คลิป",
                         "en": "81% after the announcement · June 21 clips · September 2 clips"},
                "visual_th": "สามเหลี่ยมกระดาษแหลมสูงหนึ่งอัน ข้างสามเหลี่ยมเตี้ยมากอีกสองอัน — พุ่งแล้วแผ่ว",
                "subject": "exactly THREE upright paper triangles standing in a row: the first tall and narrow like a spike, the next two very short. Three objects, nothing else.",
            },
            {
                "role": "finding", "secs": (15, 15), "image": "new",
                "narr": {"th": "โทนโดยรวมเป็นบวกถึงเจ็ดสิบห้าเปอร์เซ็นต์ เป็นลบแค่เจ็ดเปอร์เซ็นต์ และคนที่ถูกอ้างเป็นเสียงแรก คือคนไทยทั่วไปกับเจ้าหน้าที่รัฐไทย รวมกันเกือบเจ็ดในสิบ เรื่องเล่าที่โลกได้ยิน จึงมาจากฝั่งไทยเป็นหลัก",
                         "en": "The overall tone was positive in seventy-five percent of clips and negative in only seven. And the first voice quoted was usually an ordinary Thai or a Thai official, nearly seven in ten together. The story the world heard came mainly from the Thai side."},
                "label": {"th": "ใครเล่า เล่าอย่างไร", "en": "Who told it, and how"},
                "text": {"th": "โทนบวก 75% · ลบ 7% · เสียงแรกเป็นคนไทย เกือบ 7 ใน 10",
                         "en": "Positive 75% · negative 7% · first voice Thai in nearly 7 of 10"},
                "visual_th": "กรอบคำพูดกระดาษใบใหญ่หนึ่งใบ กับใบจิ๋วหนึ่งใบ — เสียงบวกที่ดังกว่ามาก",
                "subject": "ONE very large paper speech bubble and ONE tiny paper speech bubble lying beside it. Two objects, nothing else.",
            },
            {
                "role": "finding", "secs": (14, 14), "image": "new",
                "narr": {"th": "แต่คลิปจำนวนมากมีเสียงเดียว ยี่สิบแปดเปอร์เซ็นต์ไม่มีคนที่สองถูกอ้างเลย และมีน้อยมากที่เตือนนักท่องเที่ยวว่า กลับประเทศตัวเองแล้วอาจมีปัญหาทางกฎหมาย ซึ่งเป็นข้อมูลที่คนดูกลุ่มนี้ต้องใช้มากที่สุด",
                         "en": "But many clips carried a single voice: twenty-eight percent quoted nobody else at all. And very few warned travellers that they could face legal trouble back in their own country, the one piece of information that audience needed most."},
                "label": {"th": "สิ่งที่ขาดไป", "en": "What was missing"},
                "text": {"th": "28% มีเสียงเดียว · แทบไม่มีคลิปเตือน เรื่องกฎหมายบ้านตัวเอง",
                         "en": "28% had only one voice · almost none warned about the law back home"},
                "visual_th": "กระเป๋าเดินทางกระดาษหนึ่งใบ มีป้ายกระดาษเปล่าผูกอยู่ — ข้อมูลที่ควรติดไปกับนักเดินทาง แต่ว่างเปล่า",
                "subject": "ONE paper suitcase (a rounded rectangle standing upright with a small paper handle on top) with ONE small blank paper luggage tag tied to the handle by a short paper string. Two objects, nothing else.",
            },
            {
                "role": "lesson", "secs": (18, 18), "image": "new",
                "narr": {"th": "บทเรียนสำหรับงานสื่อสารภาพลักษณ์ประเทศคือ นโยบายใหญ่สร้างความสนใจได้จริง และได้โทนบวก แต่ความสนใจนั้นอายุสั้น และกระจุกอยู่ที่ช่วงประกาศ ที่สำคัญกว่าคือ เรื่องเล่าที่บวกแต่ไม่ครบ อาจทำให้คนตัดสินใจโดยขาดข้อมูลที่จำเป็น แล้วย้อนกลับมากระทบชื่อเสียงของประเทศทีหลัง",
                         "en": "For nation-image work, the lesson is that a big policy change wins real attention and a favourable tone, but the attention is short-lived and clusters around the announcement. More importantly, a story that is positive but incomplete can leave people deciding without what they need to know, and that comes back on the country's reputation later."},
                "label": {"th": "บทเรียน", "en": "The lesson"},
                "text": {"th": "ความสนใจมาเร็วไปเร็ว · เรื่องเล่าบวกแต่ไม่ครบ ย้อนมากระทบชื่อเสียงได้",
                         "en": "Attention comes and goes fast · a positive but incomplete story can rebound on reputation"},
                "visual_th": "แถบกระดาษโค้งรูปบูมเมอแรงหนึ่งชิ้น — สิ่งที่ส่งออกไปย้อนกลับมา",
                "subject": "ONE paper boomerang: a single wide curved paper strip bent into a smooth V shape, lying flat. One object, nothing else.",
            },
            caveat("ข้อควรระวัง งานนี้วิเคราะห์เพียงห้าสิบเจ็ดคลิป จากแพลตฟอร์มเดียว ในช่วงหกเดือน และเก็บข้อมูลปีสองพันห้าร้อยหกสิบห้า ก่อนที่นโยบายกัญชาของไทยจะเปลี่ยนทิศอีกครั้ง",
                   "One caution: fifty-seven clips from a single platform over six months, gathered in twenty twenty-two, before Thai cannabis policy changed direction again.",
                   "57 คลิป แพลตฟอร์มเดียว 6 เดือน · ข้อมูลปี 2565 ก่อนนโยบายเปลี่ยนอีกครั้ง",
                   "57 clips, one platform, six months · data from 2022, before policy shifted again"),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "negwom", "batch": 2,
        "slug": "negative-wom-advertising-moderation",
        "name_th": "รีวิวลบกับโฆษณาเปรียบเทียบ",
        "name_en": "Negative reviews and comparative advertising",
        "label": {"th": "งานวิจัย · การตลาดและโฆษณา", "en": "Research · Marketing and advertising"},
        "scenes": [
            {
                "role": "hook", "secs": (9, 9), "image": "existing",
                "narr": {"th": "เจอรีวิวลบที่เอาสินค้าเราไปเทียบกับคู่แข่ง ควรตอบโต้ด้วยโฆษณาเปรียบเทียบไหม … งานนี้บอกว่าอย่า",
                         "en": "When a negative review compares your product with a rival, should you hit back with a comparative ad? … This study says don't."},
                "label": {"th": "งานวิจัย · การตลาดและโฆษณา", "en": "Research · Marketing and advertising"},
                "text": {"th": "รีวิวลบที่เทียบกับคู่แข่ง ไม่ได้ทำร้ายแบรนด์ มากกว่ารีวิวลบธรรมดา และการตอบโต้ ด้วยโฆษณาเปรียบเทียบ กลับได้ผลแย่ที่สุด",
                         "en": "A negative review that compares you with a rival does no more damage than a plain one. Answering it with a comparative ad works worst of all"},
                "visual_th": "ภาพประจำบทความ (มีแล้ว): แผ่นกระดาษสี่แผ่นวางเป็นตารางสองคูณสอง มีแผ่นหนึ่งยกขึ้น — สี่เงื่อนไขของการทดลอง",
                "subject": None,
            },
            {
                "role": "method", "secs": (17, 17), "image": "new",
                "narr": {"th": "ทีมวิจัยทดลองกับนักศึกษามหาวิทยาลัยในปากีสถานหนึ่งร้อยคน แต่ละคนอ่านรีวิวลบของหูฟังยี่ห้อสมมติหนึ่งข้อความ แบบเทียบคู่แข่ง หรือไม่เทียบ แล้วดูโฆษณาของยี่ห้อนั้นหนึ่งชิ้น แบบเทียบคู่แข่ง หรือไม่เทียบเช่นกัน ก่อนให้คะแนนว่ารู้สึกกับสินค้าอย่างไร",
                         "en": "The research team ran an experiment with one hundred university students in Pakistan. Each read one negative review of a fictitious headset brand, either comparing it with a rival or not, then saw one advertisement for that brand, again comparative or not, before rating how they felt about the product."},
                "label": {"th": "ทำอะไร", "en": "What was done"},
                "text": {"th": "นักศึกษา 100 คน · รีวิวลบ 1 ข้อความ × โฆษณา 1 ชิ้น · เทียบคู่แข่ง หรือไม่เทียบ",
                         "en": "100 students · 1 negative review × 1 ad · comparative or not"},
                "visual_th": "หูฟังกระดาษหนึ่งชิ้น — แถบโค้งกับแผ่นกลมสองข้าง",
                "subject": "ONE paper headset: a single curved paper arch with a small paper disc attached at each end, standing upright. One object, nothing else.",
            },
            {
                "role": "finding", "secs": (11, 11), "image": "new",
                "narr": {"th": "ข้อแรก รีวิวลบแบบเทียบคู่แข่ง กับแบบไม่เทียบ ทำให้คนรู้สึกกับสินค้าไม่ต่างกัน สิ่งที่คนจับได้คือความลบ ไม่ใช่โครงสร้างของข้อความ",
                         "en": "First: a comparative negative review and a plain one left people feeling the same about the product. What registered was the negativity, not the structure of the message."},
                "label": {"th": "พบอะไร", "en": "What was found"},
                "text": {"th": "รีวิวลบเทียบคู่แข่ง = รีวิวลบธรรมดา · คนจับที่ความลบ ไม่ใช่รูปแบบ",
                         "en": "Comparative = plain negative review · people react to the negativity, not the format"},
                "visual_th": "ลูกบาศก์กระดาษสองก้อนขนาดเท่ากันเป๊ะ วางคู่กัน — ไม่ต่างกัน",
                "subject": "exactly TWO paper cubes of identical size standing side by side with a small gap. Two objects, nothing else.",
            },
            {
                "role": "finding", "secs": (13, 13), "image": "new",
                "narr": {"th": "ข้อสอง โฆษณาเปลี่ยนผลได้จริง แต่ไปคนละทางกับที่ทีมวิจัยคาด หลังรีวิวลบแบบเทียบคู่แข่ง โฆษณาที่พูดถึงคุณสมบัติของตัวเองอย่างตรงไปตรงมา ให้ทัศนคติดีกว่าโฆษณาที่เทียบกลับ",
                         "en": "Second: advertising did change the outcome, but in the opposite direction to what the team expected. After a comparative negative review, an ad that simply talked about the product's own features did better than one that compared back."},
                "label": {"th": "กลับทางที่คาด", "en": "The other way round"},
                "text": {"th": "โฆษณาเปลี่ยนผลได้ แต่กลับทาง · พูดถึงตัวเองตรงไปตรงมา ดีกว่าเทียบกลับ",
                         "en": "Ads change the outcome, but the other way round · talking about yourself beats comparing back"},
                "visual_th": "ลูกศรกระดาษดัดเป็นรูปกลับรถ — ไปคนละทางกับที่คาด",
                "subject": "ONE paper arrow bent into a U-turn shape, lying flat, its head pointing back the way it came. One object, nothing else.",
            },
            {
                "role": "finding", "secs": (13, 13), "image": "new",
                "narr": {"th": "คู่ที่ได้ผลดีที่สุด คือรีวิวลบธรรมดา ตามด้วยโฆษณาที่ไม่เทียบใคร ได้คะแนนห้าจากเจ็ด ส่วนคู่ที่แย่ที่สุด คือรีวิวลบธรรมดาเหมือนกัน แต่ตามด้วยโฆษณาเปรียบเทียบ เหลือแค่สองจากเจ็ด",
                         "en": "The best pairing was a plain negative review followed by a non-comparative ad, scoring five out of seven. The worst was the same review followed by a comparative ad, down to two."},
                "label": {"th": "คู่ที่ดีสุดและแย่สุด", "en": "Best and worst pairings"},
                "text": {"th": "ดีสุด: รีวิวลบธรรมดา + โฆษณาไม่เทียบ 5.07 จาก 7 · แย่สุด: รีวิวลบธรรมดา + โฆษณาเปรียบเทียบ 2.15",
                         "en": "Best: plain review + non-comparative ad 5.07 of 7 · worst: plain review + comparative ad 2.15"},
                "visual_th": "แท่งกระดาษสูงหนึ่งแท่ง กับแท่งเตี้ยมากหนึ่งแท่ง — ห้าจากเจ็ด กับสองจากเจ็ด",
                "subject": "exactly TWO upright paper columns standing side by side: one tall, one very short, less than half the height of the first. Two objects, nothing else.",
            },
            {
                "role": "lesson", "secs": (18, 18), "image": "new",
                "narr": {"th": "บทเรียนสำหรับแบรนด์ที่เจอรีวิวลบคือ การตอบว่าเราดีกว่าคู่แข่งตรงไหน อาจตอกย้ำกรอบเชิงลบแทนที่จะลบล้าง โฆษณาที่พูดถึงคุณสมบัติของตัวเองอย่างตรงไปตรงมา ทำงานได้ดีกว่าชัดเจน และก่อนใช้โฆษณาเปรียบเทียบในตลาดไหน ควรตรวจก่อนว่าคนที่นั่นมองว่าปกติ หรือไม่เหมาะสม",
                         "en": "For a brand facing a negative review, the lesson is that answering with why you beat the competitor may reinforce the negative frame instead of dispelling it. An ad that speaks plainly about your own product works clearly better. And before running comparative ads in any market, check whether people there see the format as normal or as improper."},
                "label": {"th": "บทเรียน", "en": "The lesson"},
                "text": {"th": "อย่าตอบโต้ด้วย เราดีกว่าคู่แข่ง · พูดถึงตัวเองตรงไปตรงมา · ตรวจวัฒนธรรมของตลาดก่อนเทียบ",
                         "en": "Don't answer with 'we beat them' · talk plainly about your own product · check the market's norms first"},
                "visual_th": "โทรโข่งกระดาษหนึ่งอัน — พูดถึงตัวเองอย่างตรงไปตรงมา",
                "subject": "ONE paper megaphone: a wide paper cone with a small paper cylinder at its narrow end, lying on its side. One object, nothing else.",
            },
            caveat("ข้อควรระวัง ผู้เข้าร่วมเป็นนักศึกษาหนึ่งร้อยคนจากมหาวิทยาลัยเดียวในปากีสถาน ราวยี่สิบห้าคนต่อเงื่อนไข สินค้าเป็นหูฟังยี่ห้อสมมติ และในตลาดที่โฆษณาเปรียบเทียบเป็นเรื่องปกติ ผลอาจต่างออกไปมาก",
                   "One caution: the participants were one hundred students from a single university in Pakistan, about twenty-five per condition, and the product was a fictitious headset. In markets where comparative advertising is routine, the results could differ a great deal.",
                   "นักศึกษา 100 คน มหาวิทยาลัยเดียวในปากีสถาน · สินค้าสมมติ · ตลาดอื่นอาจต่างมาก",
                   "100 students, one university in Pakistan · fictitious product · other markets may differ a lot", secs=(11, 11)),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "migrant", "batch": 2,
        "slug": "migrant-worker-exercise-codesign",
        "name_th": "ออกแบบท่าบริหารร่วมกับแรงงานข้ามชาติ",
        "name_en": "Co-designing exercises with migrant workers",
        "label": {"th": "งานวิจัย · การสื่อสารสุขภาพ", "en": "Research · Health communication"},
        "scenes": [
            {
                "role": "hook", "secs": (9, 9), "image": "existing",
                "narr": {"th": "แรงงานข้ามชาติในโรงงานอาหารทะเล เจ็บจากงานซ้ำทุกวัน แต่โปรแกรมสุขภาพทั่วไปเข้าไม่ถึงพวกเขา … ถ้าให้คนทำงานออกแบบเองล่ะ",
                         "en": "Migrant workers in seafood plants are hurt by the same movements every day, yet ordinary health programmes never reach them … so what if the workers designed it themselves?"},
                "label": {"th": "งานวิจัย · การสื่อสารสุขภาพ", "en": "Research · Health communication"},
                "text": {"th": "ถามคนทำงานก่อนออกแบบ จึงได้ท่าบริหารที่ทำได้จริง ในห้องพักและนอกเวลางาน",
                         "en": "Ask the workers first, and you get exercises that fit a dormitory room and the hours they actually have"},
                "visual_th": "ภาพประจำบทความ (มีแล้ว): แผ่นกระดาษพับใหญ่ กับกล่องเล็กที่มีของพับพอดีอยู่ข้างใน — โปรแกรมที่ออกแบบให้พอดีกับพื้นที่จริง",
                "subject": None,
            },
            {
                "role": "method", "secs": (17, 17), "image": "new",
                "narr": {"th": "ทีมวิจัยจัดวงสนทนากับแรงงานชาวเมียนมายี่สิบเก้าคน จากโรงงานเดียวกัน แบ่งสามกลุ่มตามอายุงาน คุยด้วยภาษาเมียนมา และจัดเวลาให้เข้ากับกะทำงานสิบสองชั่วโมง คุยกับฝ่ายบุคคลและหัวหน้าสายการผลิตห้าคน แล้วส่งท่าที่ออกแบบได้ ให้นักกายภาพบำบัดสี่คนตรวจ",
                         "en": "The research team held discussion sessions with twenty-nine Myanmar workers from one factory, in three groups by length of service, in the Myanmar language and scheduled around twelve-hour shifts. They also consulted five HR managers and line supervisors, and had four physical therapists check the exercises that came out."},
                "label": {"th": "ทำอะไร", "en": "What was done"},
                "text": {"th": "แรงงานเมียนมา 29 คน · 3 กลุ่มตามอายุงาน · คุยภาษาเมียนมา นอกกะ 12 ชั่วโมง · นักกายภาพบำบัด 4 คนตรวจ",
                         "en": "29 Myanmar workers · 3 groups by service length · in Myanmar language, around 12-hour shifts · checked by 4 physical therapists"},
                "visual_th": "วงกลมกระดาษสามวงขนาดต่างกันซ้อนเหลื่อมกันเล็กน้อย — สามกลุ่มสนทนา",
                "subject": "exactly THREE flat paper circles of slightly different sizes, overlapping one another a little, lying flat. Three objects, nothing else.",
            },
            {
                "role": "finding", "secs": (14, 14), "image": "new",
                "narr": {"th": "ทั้งยี่สิบเก้าคนมีอาการที่มือ ชา เสียว หรือปวด ยี่สิบสามคนซื้อยาแก้ปวดกินเองอย่างน้อยสัปดาห์ละครั้ง บางคนกลับไปทำงานแบบเดิมทันทีหลังผ่าตัด พวกเขาดูแลตัวเองอยู่แล้ว แต่ด้วยวิธีที่เสี่ยง",
                         "en": "All twenty-nine had hand symptoms: numbness, tingling or pain. Twenty-three bought painkillers at least once a week, and some went straight back to the same work after surgery. They were already looking after themselves, but in risky ways."},
                "label": {"th": "พบอะไร", "en": "What was found"},
                "text": {"th": "29 จาก 29 มีอาการที่มือ · 23 คน ซื้อยาแก้ปวดกินเอง ทุกสัปดาห์",
                         "en": "29 of 29 had hand symptoms · 23 bought painkillers weekly"},
                "visual_th": "ขวดยากระดาษหนึ่งขวด กับเม็ดยากระดาษสามเม็ดที่หกออกมา",
                "subject": "ONE small paper bottle (a short cylinder with a little cap) lying on its side, with exactly THREE small flat paper discs spilling out of its mouth. Four pieces in total, nothing else.",
            },
            {
                "role": "finding", "secs": (15, 15), "image": "new",
                "narr": {"th": "ยี่สิบหกจากยี่สิบเก้าคนใช้เฟซบุ๊กทุกวัน และเลือกช่องทางนี้ เพราะเปิดดูเรื่องสุขภาพได้โดยหัวหน้าไม่เห็น พวกเขาขอเป็นวิดีโอสาธิต มากกว่าเอกสาร และปฏิเสธการอบรมแบบบังคับ ในวันหยุดวันเดียวของสัปดาห์",
                         "en": "Twenty-six of the twenty-nine used Facebook every day, and chose it because they could read about health without a supervisor seeing. They asked for demonstration videos rather than documents, and said no to compulsory workshops on their one day off."},
                "label": {"th": "ช่องทางที่พวกเขาเลือก", "en": "The channel they chose"},
                "text": {"th": "26 จาก 29 ใช้เฟซบุ๊กทุกวัน · ขอวิดีโอสาธิต ไม่เอาเอกสาร · ไม่เอาอบรมบังคับในวันหยุด",
                         "en": "26 of 29 on Facebook daily · videos, not documents · no compulsory workshops on the day off"},
                "visual_th": "แผ่นกระดาษตั้งเหมือนจอโทรศัพท์ มีสามเหลี่ยมกระดาษเล็กอยู่ตรงหน้า — วิดีโอบนมือถือ",
                "subject": "ONE flat paper rectangle with rounded corners standing upright like a phone screen, and ONE small paper triangle (a play symbol) standing in front of it. Two objects, nothing else.",
            },
            {
                "role": "finding", "secs": (19, 19), "image": "new",
                "narr": {"th": "เงื่อนไขที่แรงงานตั้งเอง กลายเป็นโจทย์ออกแบบ ท่าบริหารต้องทำได้ในพื้นที่แคบเท่าห้องพัก ไม่ใช้อุปกรณ์ ทำนอกเวลางาน และไม่ทำให้รายได้ลดลง ผลที่ได้คือชุดท่าบริหารสิบสองท่า สี่สัปดาห์ ที่ผู้เชี่ยวชาญให้คะแนนความตรงเชิงเนื้อหาในระดับสูง การฟังคนทำงาน ไม่ได้ทำให้คุณภาพทางคลินิกลดลง",
                         "en": "The workers' own conditions became the design brief: exercises that fit a dormitory-sized space, need no equipment, run outside working hours, and never cut earnings. The result was a twelve-exercise, four-week programme that experts rated highly for content validity. Listening to the workers cost nothing in clinical quality."},
                "label": {"th": "โจทย์ที่แรงงานตั้งเอง", "en": "The brief the workers set"},
                "text": {"th": "ทำได้ในห้องพัก · ไม่ใช้อุปกรณ์ · นอกเวลางาน · รายได้ไม่ลด → 12 ท่า 4 สัปดาห์ ผ่านผู้เชี่ยวชาญ",
                         "en": "Fits a dorm room · no equipment · off the clock · no lost pay → 12 exercises, 4 weeks, expert-validated"},
                "visual_th": "ห้องกระดาษเล็ก (ผนังสามด้านเปิดหน้า) มีลูกบาศก์ก้อนเล็กอยู่ข้างใน — ทำได้ในพื้นที่แคบ",
                "subject": "ONE small paper room: three paper walls forming an open-fronted box with no roof, and ONE small paper cube resting inside it. Two objects, nothing else.",
            },
            {
                "role": "lesson", "secs": (17, 17), "image": "new",
                "narr": {"th": "บทเรียนสำหรับงานสื่อสารสุขภาพทุกแบบคือ ข้อจำกัดที่คนหน้างานบอก ไม่ใช่สิ่งที่ต้องยอมแลกกับคุณภาพ แต่เป็นเงื่อนไขที่ทำให้โปรแกรมถูกใช้จริง และการเลือกช่องทางที่กลุ่มเป้าหมายใช้อยู่แล้ว และเปิดดูได้อย่างเป็นส่วนตัว สำคัญกว่าช่องทางที่องค์กรถนัด",
                         "en": "The lesson for any health communication work: the constraints people at the sharp end tell you about are not a trade-off against quality. They are the conditions under which a programme gets used at all. And a channel the audience already uses, and can use privately, matters more than the channel the organisation is comfortable with."},
                "label": {"th": "บทเรียน", "en": "The lesson"},
                "text": {"th": "ข้อจำกัดหน้างาน = เงื่อนไขที่ทำให้ใช้จริง · เลือกช่องทางที่คนใช้อยู่แล้ว ไม่ใช่ที่องค์กรถนัด",
                         "en": "Front-line constraints are what make it usable · pick the channel people already use, not the one you prefer"},
                "visual_th": "กุญแจกระดาษหนึ่งดอก วางข้างแผ่นกระดาษที่เจาะรูกุญแจ — ทำให้พอดีกับล็อกที่มีอยู่",
                "subject": "ONE flat paper key and ONE flat paper plate with a keyhole-shaped opening cut through it, lying side by side. Two objects, nothing else.",
            },
            caveat("ข้อควรระวัง งานนี้เป็นการออกแบบร่วม ไม่ใช่การทดสอบว่าท่าบริหารได้ผลจริง และเก็บข้อมูลจากโรงงานเดียว ยี่สิบเก้าคน จึงไม่ใช่ภาพแทนแรงงานข้ามชาติทั้งอุตสาหกรรม",
                   "One caution: this is a co-design study, not a test of whether the exercises work, and it draws on twenty-nine people from a single factory, so it does not stand for migrant workers across the industry.",
                   "ออกแบบร่วม ไม่ได้ทดสอบผลจริง · โรงงานเดียว 29 คน",
                   "Co-design, not an effectiveness test · one factory, 29 people"),
            closing(),
        ],
    },
]
