"""สตอรี่บอร์ดชุดที่ 3 — 5 เรื่อง × ไทย/อังกฤษ (4 ก.ย. 2569) — storyboard.py นำเข้าไฟล์นี้แล้วต่อท้าย CLIPS/PALETTE

กติกาเดียวกับชุดที่ 2 (ดูหัวไฟล์ storyboard_batch2.py) · ข้อเพิ่มของชุดนี้:
  · คลิปโควิดไม่เอ่ยชื่อบุคคล ยี่ห้อวัคซีน หรือบริษัท (กติกาข้อ 5 — บทสรุปบนเว็บก็ตัดออกแล้ว) และพูดว่า "รัฐบาล" ไม่ใช่ "ผู้นำรัฐบาล"
  · คลิปวีทูปเบอร์ไม่เอ่ยชื่ออินฟลูเอนเซอร์สองคนที่ใช้เป็นสิ่งเร้า
  · เลือกเรื่องคริปโต Reddit ออก เพราะบทสรุปบนเว็บบางเกินกว่าจะเล่า 8 ฉากได้ (ไม่มีตัวเลข) — สลับเป็นวีทูปเบอร์
"""
from storyboard_batch2 import CLOSING2, ASTERISK

CLOSING3 = CLOSING2

# คู่สีอ่านจากภาพประจำบทความของแต่ละเรื่อง (ดูภาพจริง frames/b3-illustrations.png) เพื่อให้ภาพใหม่กลมกลืนกับภาพ hook
PALETTE3 = {
    "covidcred": {"object": "soft coral pink", "shadow": "deep teal", "obj_hex": "#F3A498", "sh_hex": "#1F6B72",
                  "shadow_style": "clean flat-edged shadows to the lower right rendered as solid deep-teal shapes, like cut paper rather than soft photographic shadows"},
    "cruelty": {"object": "sage green", "shadow": "soft olive-grey", "obj_hex": "#8FB07A", "sh_hex": "#A8A48C",
                "shadow_style": "soft olive-grey shadows to the lower right, as in a real studio photograph of paper on a table"},
    "techno": {"object": "deep wine magenta", "shadow": "sage green", "obj_hex": "#8B1E4A", "sh_hex": "#9CA86E",
               "shadow_style": "soft sage-green shadows to the lower right, as in a real studio photograph of paper on a table"},
    "joox": {"object": "vivid rose pink", "shadow": "olive green", "obj_hex": "#E0578B", "sh_hex": "#9BA36A",
             "shadow_style": "clean flat-edged shadows to the lower right rendered as solid olive-green shapes, like cut paper rather than soft photographic shadows"},
    "vtuber": {"object": "olive green", "shadow": "soft rose pink", "obj_hex": "#8C9A4E", "sh_hex": "#E8A0B8",
               "shadow_style": "soft rose-pink shadows to the lower right, as in a real studio photograph of paper on a table"},
}


def closing():
    return {"role": "closing", "secs": (14, 14), "image": "logo", "narr": CLOSING3, "label": None, "text": None,
            "visual_th": "การ์ดปิดประจำชุด + ชื่อผู้เขียนทุกคน (ไม่ต้องเจนภาพ)", "subject": None}


def caveat(narr_th, narr_en, text_th, text_en, secs=(10, 10)):
    return {"role": "caveat", "secs": secs, "image": "new", "narr": {"th": narr_th, "en": narr_en},
            "label": {"th": "ข้อควรระวัง", "en": "One caution"}, "text": {"th": text_th, "en": text_en},
            "visual_th": "ดอกจันกระดาษพับหนึ่งดอก — สัญลักษณ์ประจำฉากข้อควรระวัง (คู่สีของคลิปนี้)", "subject": ASTERISK}


def scene(role, secs, narr_th, narr_en, label_th, label_en, text_th, text_en, visual_th, subject, image="new"):
    return {"role": role, "secs": (secs, secs), "image": image, "narr": {"th": narr_th, "en": narr_en},
            "label": {"th": label_th, "en": label_en}, "text": {"th": text_th, "en": text_en},
            "visual_th": visual_th, "subject": subject}


CLIPS3 = [
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "covidcred", "batch": 3,
        "slug": "covid-official-communication-credibility",
        "name_th": "ความน่าเชื่อถือของข้อความรัฐช่วงโควิด",
        "name_en": "Official COVID messaging and credibility",
        "label": {"th": "งานวิจัย · การสื่อสารในภาวะวิกฤต", "en": "Research · Crisis communication"},
        "scenes": [
            scene("hook", 9,
                  "ช่วงโควิด คนไทยเชื่อข้อความของรัฐมากแค่ไหน … คำตอบไม่ได้อยู่ที่ข้อความจริงหรือไม่จริง แต่อยู่ที่รัฐคุมโรคอยู่หรือเปล่า",
                  "During COVID, how far did Thais believe official messaging? … The answer had little to do with whether the message was true, and everything to do with whether the outbreak looked under control.",
                  "งานวิจัย · การสื่อสารในภาวะวิกฤต", "Research · Crisis communication",
                  "คนเชื่อข้อความของรัฐ ตราบเท่าที่เห็นว่ารัฐคุมโรคได้ พอมาตรการล้มเหลว ความเชื่อก็หายไปด้วย",
                  "People believed official messaging as long as the government seemed to be winning. Once measures failed, belief went with them",
                  "ภาพประจำบทความ (มีแล้ว): แถบกระดาษสองเส้นไต่ขึ้นถึงยอดแล้วลาดลงพร้อมกัน — ความเชื่อถือกับผลงานเดินไปด้วยกัน", None, image="existing"),
            scene("method", 17,
                  "คณะผู้วิจัยวิเคราะห์โพสต์และคอมเมนต์บนเฟซบุ๊กและทวิตเตอร์ ตั้งแต่ต้นปีสองพันห้าร้อยหกสิบสาม ถึงต้นปีสองพันห้าร้อยหกสิบห้า ค้นตามเดือนและแฮชแท็กของแต่ละช่วง ควบคู่กับสัมภาษณ์ผู้เชี่ยวชาญห้าสิบคน ทั้งผู้ตรวจสอบข้อเท็จจริง คนทำงานข้อมูลสุขภาพ สื่อมวลชน และนักประชาสัมพันธ์ แล้วอ่านเรื่องราวทั้งหมดเป็นสี่ช่วงของการระบาด",
                  "The authors analysed posts and comments on Facebook and Twitter from early twenty twenty to early twenty twenty-two, searching month by month through the hashtags of each period, and interviewed fifty experts: fact-checkers, health-information workers, journalists and public relations practitioners. They then read the whole story as four waves of the outbreak.",
                  "ทำอะไร", "What was done",
                  "โพสต์และคอมเมนต์ 2 ปี · ผู้เชี่ยวชาญ 50 คน · แบ่งเป็น 4 ช่วง",
                  "Two years of posts · 50 expert interviews · four waves",
                  "กรอบคำพูดกระดาษสี่ใบขนาดต่างกันเล็กน้อยวางเรียงหลวมๆ — วาทกรรมสี่ช่วง",
                  "exactly FOUR flat paper speech bubbles of slightly different sizes lying in a loose row. Four objects, nothing else."),
            scene("finding", 16,
                  "ช่วงแรกข้อความทางการสับสน คนจึงหันไปอ้างองค์การอนามัยโลกแทน แต่พอล็อกดาวน์ได้ผลกลางปีสองพันห้าร้อยหกสิบสาม ความเชื่อถือขึ้นสูงสุด การแถลงรายวันโดยแพทย์ได้รับความไว้วางใจ และคนไทยเลือกเชื่อรัฐเหนือองค์การอนามัยโลกเรื่องหน้ากาก ทั้งที่ตอนนั้นองค์การอนามัยโลกยังไม่แนะนำ",
                  "In the first weeks official messaging was confused, and people cited the World Health Organization instead. But once the lockdown worked in mid twenty twenty, credibility peaked. The daily briefings led by a doctor were trusted, and on masks Thais chose the government over WHO, which was not yet recommending them.",
                  "ช่วงที่คุมได้", "While it worked",
                  "ล็อกดาวน์ได้ผล · ความเชื่อถือสูงสุด · เรื่องหน้ากาก คนเชื่อรัฐ มากกว่า WHO",
                  "Lockdown worked · credibility peaked · on masks, people trusted the government over WHO",
                  "โล่กระดาษตั้งตรงหนึ่งใบ กับเครื่องหมายถูกกระดาษพิงอยู่ — ช่วงที่คุมได้และคนไว้ใจ",
                  "ONE upright paper shield shape and ONE small paper tick mark (check mark) leaning against it. Two objects, nothing else."),
            scene("finding", 20,
                  "แล้วระลอกที่สามก็มา เมษายนสองพันห้าร้อยหกสิบสี่ เดือนเดียวมีผู้ติดเชื้อใหม่กว่าสามหมื่นหกพันราย มากกว่ายอดสะสมทั้งหมดก่อนหน้า ขณะที่คนฉีดวัคซีนครบยังไม่ถึงหนึ่งเปอร์เซ็นต์ คำร้องออนไลน์ให้ปลดผู้รับผิดชอบได้สองแสนชื่อในไม่กี่วัน และคะแนนนิยมรัฐบาลร่วงจากกว่าเก้าสิบเปอร์เซ็นต์ เหลือไม่ถึงยี่สิบ ความเชื่อถือในข้อความของรัฐพังลงพร้อมกับผลงาน",
                  "Then the third wave came. In April twenty twenty-one alone there were more than thirty-six thousand new cases, more than the country's entire previous total, while under one percent of the population was fully vaccinated. An online petition gathered two hundred thousand signatures in days, and approval of the government fell from above ninety percent to below twenty. Credibility collapsed along with performance.",
                  "เมื่อผลงานตก", "When performance fell",
                  "เมษายน 2564 ติดเชื้อใหม่ 36,650 ราย · ฉีดครบไม่ถึง 1% · คะแนนนิยม 93% → 19%",
                  "April 2021: 36,650 new cases · under 1% fully vaccinated · approval 93% → 19%",
                  "แท่งกระดาษสองแท่ง แท่งหนึ่งสูง อีกแท่งเตี้ยไม่ถึงหนึ่งในสี่ — คะแนนนิยมที่ร่วง",
                  "exactly TWO upright paper columns standing side by side: one tall, the other less than a quarter of its height. Two objects, nothing else."),
            scene("finding", 16,
                  "และทิศทางกลับหัวกับตะวันตก ที่นั่นคนที่ไม่เชื่อรัฐใช้โซเชียลต่อต้านวัคซีน แต่ในไทย คนที่ไม่เชื่อรัฐกลับเรียกร้องวัคซีนรุ่นใหม่ และหยิบข้อมูลเปรียบเทียบจากองค์การอนามัยโลกและซีดีซี มาโต้ทางเลือกของรัฐ สิ้นปีสองพันห้าร้อยหกสิบสี่ คนที่ฉีดแล้วหรือยินดีฉีดสูงถึงเก้าสิบเปอร์เซ็นต์",
                  "And the direction was the reverse of the West. There, sceptics used social media to oppose vaccines. In Thailand, those who distrusted the government demanded newer vaccines, and used WHO and CDC comparisons to contest the government's choices. By the end of twenty twenty-one, ninety percent had been vaccinated or were willing to be.",
                  "กลับทางกับตะวันตก", "The reverse of the West",
                  "คนไม่เชื่อรัฐ ไม่ได้ต้านวัคซีน แต่เรียกร้องวัคซีนรุ่นใหม่ · ปลายปี 2564 ยินดีฉีด 90%",
                  "Sceptics did not reject vaccines, they demanded newer ones · by late 2021, 90% vaccinated or willing",
                  "ลูกศรกระดาษสองอันวางคู่กัน ชี้คนละทาง — ทิศทางที่กลับกัน",
                  "exactly TWO flat paper arrows lying side by side and pointing in opposite directions. Two objects, nothing else."),
            scene("lesson", 24,
                  "บทเรียนสำหรับการสื่อสารในภาวะวิกฤตคือ ความน่าเชื่อถือเป็นผลของผลงานที่คนมองเห็น ไม่ใช่ของความจริงหรือความโปร่งใสอย่างเดียว อธิบายดีแค่ไหนก็ไม่พอ ถ้าสิ่งที่คนเห็นสวนทาง เมื่อความเชื่อร่วง คนไม่ได้เลิกหาข้อมูล แต่ย้ายไปหาแหล่งที่เขาเชื่อกว่า การสื่อสารของรัฐที่อ้างอิงองค์กรสากลอย่างเปิดเผย จึงยืมความน่าเชื่อถือนั้นมาได้ และการควบคุมข้อมูลในช่วงที่ความเชื่อถือต่ำอยู่แล้ว ให้ผลตรงข้าม เพราะถูกอ่านว่ามีอะไรต้องปิด",
                  "The lesson for crisis communication is that credibility follows the performance people can see, not truthfulness or transparency alone. Explaining well is not enough when the results point the other way. When trust falls, people do not stop looking for information; they move to sources they trust more. Official communication that openly cites international bodies can borrow that credibility. And controlling information when trust is already low backfires, because it reads as having something to hide.",
                  "บทเรียน", "The lesson",
                  "ความน่าเชื่อถือตามผลงานที่คนเห็น · อ้างองค์กรสากลอย่างเปิดเผย · คุมข้อมูลตอนคนไม่เชื่อ ยิ่งเสีย",
                  "Credibility follows visible results · cite international bodies openly · controlling information when trust is low backfires",
                  "แถบกระดาษโค้งเป็นสะพานพาดบนบล็อกกระดาษเล็กสองก้อน — ยืมความน่าเชื่อถือข้ามไป",
                  "ONE long paper strip arched like a bridge, its two ends resting on TWO small paper blocks. Three pieces in total, nothing else."),
            caveat("ข้อควรระวัง งานนี้เป็นการวิเคราะห์เชิงคุณภาพและการตีความ ไม่ได้นับจำนวนโพสต์ ความสัมพันธ์ระหว่างคะแนนนิยมกับความเชื่อถือ อ่านจากลำดับเหตุการณ์ ไม่ใช่การวัดทางสถิติ และคลิปนี้ตั้งใจไม่เอ่ยชื่อบุคคล ยี่ห้อวัคซีน หรือบริษัทใด เพราะบทเรียนอยู่ที่กลไก ไม่ใช่ตัวบุคคล",
                   "One caution: this is a qualitative, interpretive analysis. It counts no posts, and the link between approval and trust is read from the sequence of events, not measured statistically. This clip deliberately names no individuals, vaccine brands or companies, because the lesson lies in the mechanism, not in who was involved.",
                   "วิเคราะห์เชิงคุณภาพ ไม่ได้นับโพสต์ · อ่านจากลำดับเหตุการณ์ · ไม่เอ่ยชื่อบุคคล ยี่ห้อ หรือบริษัท",
                   "Qualitative, no post counts · read from the sequence of events · no names, brands or companies", secs=(12, 12)),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "cruelty", "batch": 3,
        "slug": "genz-cruelty-free-purchase",
        "name_th": "เจนซีกับสินค้าที่ไม่ทดลองกับสัตว์",
        "name_en": "Gen Z and cruelty-free products",
        "label": {"th": "งานวิจัย · พฤติกรรมผู้บริโภค", "en": "Research · Consumer behaviour"},
        "scenes": [
            scene("hook", 8,
                  "เจนซีไทยเลือกสินค้าที่ไม่ทดลองกับสัตว์เพราะค่านิยม … แต่พอราคาขึ้น ค่านิยมพาไปถึงการจ่ายเงินไหม",
                  "Thai Gen Z choose cruelty-free products out of their values … but when the price goes up, do values carry them to the checkout?",
                  "งานวิจัย · พฤติกรรมผู้บริโภค", "Research · Consumer behaviour",
                  "เจนซีเลือกสินค้าไม่ทดลองกับสัตว์ เพราะค่านิยม แต่สิ่งที่ทำนายการซื้อได้แรงที่สุด คือความภักดี ซึ่งหายไปเมื่อราคาขึ้น",
                  "Gen Z buy cruelty-free out of values. The strongest predictor of purchase is loyalty, and loyalty falls away when the price rises",
                  "ภาพประจำบทความ (มีแล้ว): ขั้นบันไดสามขั้น ขั้นบนสุดหลุดลอยห่างออกไป — ขั้นสุดท้ายที่ไปไม่ถึง", None, image="existing"),
            scene("method", 15,
                  "ทีมวิจัยสำรวจออนไลน์คนไทยอายุสิบแปดถึงยี่สิบหกปี สี่ร้อยคน ที่รู้จักแบรนด์ซึ่งประกาศว่าไม่ทดลองกับสัตว์ วัดสี่ด้าน คือค่านิยม ทัศนคติต่อเครื่องมือสื่อสารการตลาด ความภักดีต่อแบรนด์ และความตั้งใจซื้อ แล้ววิเคราะห์ว่าด้านไหนทำนายความตั้งใจซื้อได้จริง",
                  "The research team surveyed four hundred Thais aged eighteen to twenty-six who knew a brand that declares itself cruelty-free, measuring four things: values, attitudes toward marketing communication tools, brand loyalty and purchase intention, then tested which of them actually predicts the intention to buy.",
                  "ทำอะไร", "What was done",
                  "400 คน อายุ 18–26 ปี · วัด 4 ด้าน · ค่านิยม ทัศนคติ ความภักดี ความตั้งใจซื้อ",
                  "400 people aged 18–26 · four measures · values, attitudes, loyalty, purchase intention",
                  "กระดาษสี่เหลี่ยมเล็กสี่แผ่นขนาดเท่ากัน วางเป็นตารางสองคูณสอง — สี่ด้านที่วัด",
                  "exactly FOUR small square paper tiles of identical size lying flat in a neat two-by-two grid with equal gaps. Four objects, nothing else."),
            scene("finding", 12,
                  "ค่านิยมที่ได้คะแนนสูงสุดคือค่านิยมสากลนิยม สี่จุดหกห้าจากห้า ผู้ตอบให้น้ำหนักกับการดูแลสัตว์และธรรมชาติ มากกว่าการได้รับการยอมรับจากคนรอบตัว ซึ่งได้เพียงสามจุดสามหก",
                  "The value that scored highest was universalism, at four point six five out of five. Respondents weighted care for animals and nature far above recognition from the people around them, which scored only three point three six.",
                  "ค่านิยม", "The values",
                  "ดูแลสัตว์และธรรมชาติ 4.65 · การยอมรับจากคนรอบตัว 3.36 (จาก 5)",
                  "Care for animals and nature 4.65 · recognition from others 3.36 (out of 5)",
                  "หัวใจกระดาษหนึ่งดวงวางราบ มีใบไม้กระดาษใบเล็กวางอยู่บนนั้น — ค่านิยมเรื่องสัตว์และธรรมชาติ",
                  "ONE flat paper heart shape lying on the table with ONE small paper leaf resting on top of it. Two objects, nothing else."),
            scene("finding", 13,
                  "แต่ตัวที่ทำนายความตั้งใจซื้อได้แรงที่สุด ไม่ใช่ค่านิยม แต่เป็นความภักดีต่อแบรนด์ ตามด้วยทัศนคติ ส่วนค่านิยมมาเป็นอันดับสาม ทั้งสามด้านรวมกันอธิบายความตั้งใจซื้อได้ราวหกสิบสามเปอร์เซ็นต์",
                  "But the strongest predictor of purchase intention was not values. It was brand loyalty, followed by attitude, with values a distant third. Together the three explained about sixty-three percent of purchase intention.",
                  "อะไรทำนายการซื้อ", "What predicts buying",
                  "ความภักดี β .49 · ทัศนคติ β .30 · ค่านิยม β .12 · อธิบายได้ 63%",
                  "Loyalty β .49 · attitude β .30 · values β .12 · 63% explained",
                  "แท่งกระดาษสามแท่งเรียงกัน สูง กลาง เตี้ย — ความภักดีนำ",
                  "exactly THREE upright paper columns standing in a row, descending in height from left to right: tall, medium, short. Three objects, nothing else."),
            scene("finding", 16,
                  "และในหมวดความภักดี ข้อที่ได้คะแนนต่ำที่สุดคือ จะซื้อแบรนด์นี้ต่อแม้ราคาขึ้น ขณะที่ข้อการบอกต่อได้คะแนนสูงสุด สี่จุดสี่ ยินดีเชียร์ให้คนอื่น แต่ไม่ยินดีจ่ายเพิ่มเอง และข้อที่ต่ำสุดในหมวดความตั้งใจซื้อ คือจะซื้อแม้ไม่มีขายใกล้ตัว",
                  "And within loyalty, the lowest-scoring item was keeping on buying the brand if the price went up, while recommending it to others scored highest at four point four. Happy to cheer for it, unwilling to pay more for it. The lowest purchase-intention item was buying it even when it is not available nearby.",
                  "ช่องว่างที่พบ", "The gap",
                  "บอกต่อ 4.40 สูงสุด · จ่ายแพงขึ้น ต่ำสุด · ซื้อแม้หาซื้อยาก 3.60",
                  "Recommend 4.40, highest · pay more, lowest · buy even if hard to find 3.60",
                  "ป้ายราคากระดาษหนึ่งใบ กับเหรียญกระดาษเล็กหนึ่งเหรียญวางข้างกัน — เชียร์ได้ แต่ไม่จ่ายเพิ่ม",
                  "ONE flat paper price tag (a rectangle with one corner cut off and a small round hole) and ONE small flat paper coin lying beside it. Two objects, nothing else."),
            scene("lesson", 22,
                  "บทเรียนสำหรับแบรนด์และคนทำแคมเปญคือ ค่านิยมพาคนมาถึงหน้าร้าน แต่ไม่ได้พาไปถึงการจ่ายเงินเมื่อราคาต่างกัน แบรนด์ที่สื่อสารแต่เรื่องคุณค่า จะได้เสียงเชียร์ที่ดัง แต่ยอดขายที่บาง ข้อมูลชุดเดียวกันบอกว่าการส่งเสริมการขายเป็นเครื่องมือที่ชอบที่สุด และการประชาสัมพันธ์ที่ให้ความรู้ตามมาเป็นอันดับสอง ทั้งสองจึงต้องมาคู่กัน และการกระจายสินค้าให้หาซื้อได้สะดวก เป็นเงื่อนไขที่ตัดออกไม่ได้",
                  "The lesson for brands and campaigners is that values bring people to the shelf, but they do not carry them across a price difference. A brand that communicates only on values earns loud advocacy and thin sales. The same data shows sales promotion as the best-liked tool, with public relations that educates second, so the two have to run together. And distribution, so the product is actually within reach, is not optional.",
                  "บทเรียน", "The lesson",
                  "ค่านิยมพามาถึงหน้าร้าน ไม่ถึงการจ่ายเงิน · โปรโมชันคู่กับการให้ความรู้ · ต้องหาซื้อได้สะดวก",
                  "Values bring people to the shelf, not past the price · promotion with education · keep it within reach",
                  "ตะกร้ากระดาษใบเล็กมีหูหิ้วโค้ง กับลูกบาศก์กระดาษเล็กหนึ่งก้อนอยู่ข้างใน — ถึงตะกร้าจริง",
                  "ONE small open paper basket (an open box with a paper handle arched over it) with ONE small paper cube resting inside it. Two objects, nothing else."),
            caveat("ข้อควรระวัง ผู้ตอบเป็นผู้หญิงถึงแปดสิบห้าเปอร์เซ็นต์ ตัวเลขทั้งหมดจึงสะท้อนกลุ่มนี้เป็นหลัก สินค้ากลุ่มนี้ในไทยส่วนใหญ่เป็นเครื่องสำอางและของใช้ส่วนตัว และเป็นความตั้งใจซื้อที่ผู้ตอบแจ้งเอง ไม่ใช่ยอดซื้อจริง",
                   "One caution: eighty-five percent of respondents were women, so every figure mainly describes that group. Cruelty-free products in Thailand are mostly cosmetics and personal care, and these are self-reported intentions, not observed purchases.",
                   "ผู้ตอบเป็นหญิง 85% · ส่วนใหญ่เป็นเครื่องสำอาง · ความตั้งใจซื้อ ไม่ใช่ยอดซื้อจริง",
                   "85% women · mostly cosmetics · intentions, not purchases"),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "techno", "batch": 3,
        "slug": "first-year-online-learning-technostress",
        "name_th": "เทคโนสเตรสของนิสิตปีหนึ่ง",
        "name_en": "Technostress among first-year students",
        "label": {"th": "งานวิจัย · การศึกษา", "en": "Research · Education"},
        "scenes": [
            scene("hook", 8,
                  "นิสิตปีหนึ่งที่ต้องย้ายมาเรียนออนไลน์กลางคัน เครียดกับเทคโนโลยี … แต่ไม่ใช่เพราะมันยาก",
                  "First-year students pushed online mid-course were stressed by the technology … but not because it was hard.",
                  "งานวิจัย · การศึกษา", "Research · Education",
                  "ความเครียดของนิสิตปีหนึ่ง ไม่ได้มาจากเทคโนโลยียาก แต่มาจากปริมาณ ที่ต้องรับมือพร้อมกัน",
                  "First-year stress did not come from technology being hard. It came from how much of it arrived at once",
                  "ภาพประจำบทความ (มีแล้ว): กองแผ่นบางซ้อนสูงจนทรุด ข้างแผ่นหนาแผ่นเดียวที่ตั้งมั่นคง — ปริมาณ ไม่ใช่ความยาก", None, image="existing"),
            scene("method", 20,
                  "ผู้วิจัยใช้แบบสอบถามออนไลน์สี่สิบห้าข้อ กับนิสิตปีหนึ่งของมหาวิทยาลัยแห่งหนึ่ง แปดร้อยสามคน ในปีการศึกษาสองพันห้าร้อยหกสิบสาม วัดมุมมองต่อการเรียนสองแบบ คือเรียนสดกับเรียนจากสิ่งที่บันทึกไว้ และวัดความเครียดจากเทคโนโลยีสี่ด้าน คือปริมาณงานล้น ความซับซ้อน ความไม่มั่นคงของระบบ และความไม่แน่นอนของเทคโนโลยีที่เปลี่ยนบ่อย แล้วเทียบนิสิตสายวิทย์กับสายที่ไม่ใช่วิทย์",
                  "The researcher gave a forty-five-item online questionnaire to eight hundred and three first-year students at one university in the twenty twenty academic year, measuring views of two learning modes, live sessions and recorded material, and four kinds of technology stress: overload, complexity, unreliable systems, and technology that keeps changing. Science students were then compared with non-science students.",
                  "ทำอะไร", "What was done",
                  "นิสิตปีหนึ่ง 803 คน · เรียนสด กับ เรียนจากที่บันทึกไว้ · ความเครียด 4 ด้าน · สายวิทย์ กับ สายอื่น",
                  "803 first-years · live vs recorded · four kinds of stress · science vs non-science",
                  "แล็ปท็อปกระดาษใบเล็ก ฐานแบนกับจอบางตั้งขึ้น — ห้องเรียนที่ย้ายมาอยู่บนจอ",
                  "ONE small paper laptop: a flat paper base with a thin paper screen hinged upright along its back edge. One object, nothing else."),
            scene("finding", 15,
                  "ความเครียดด้านปริมาณงานล้น สูงกว่าอีกสามด้านชัดเจนในทั้งสองกลุ่ม สายวิทย์สามจุดห้าสอง สายที่ไม่ใช่วิทย์สามจุดหกสี่ จากห้า ส่วนความซับซ้อน ความไม่มั่นคงของระบบ และความไม่แน่นอน อยู่ระดับกลางค่อนไปทางต่ำทั้งหมด ราวสองจุดเจ็ดถึงสาม",
                  "Overload stood clearly above the other three in both groups: three point five two among science students and three point six four among the rest, out of five. Complexity, unreliable systems and uncertainty all sat in the middle-to-low range, around two point seven to three.",
                  "ด้านที่สูง", "The high one",
                  "ปริมาณงานล้น 3.5–3.6 · ความซับซ้อน ระบบไม่มั่นคง ความไม่แน่นอน 2.7–3.0 (จาก 5)",
                  "Overload 3.5–3.6 · complexity, unreliability, uncertainty 2.7–3.0 (out of 5)",
                  "แท่งกระดาษสี่แท่งเรียงกัน แท่งแรกสูง อีกสามแท่งเตี้ยเท่ากัน — ด้านเดียวที่โดดขึ้นมา",
                  "exactly FOUR upright paper columns standing in a row: the first tall, the other three short and equal in height. Four objects, nothing else."),
            scene("finding", 11,
                  "สายวิทย์กับสายอื่นต่างกันอย่างมีนัยสำคัญเพียงด้านเดียว คือความไม่แน่นอนของเทคโนโลยี ส่วนความซับซ้อนและความไม่มั่นคงของระบบ ไม่พบความต่างเลย",
                  "Science and non-science students differed significantly on only one kind of stress, uncertainty about changing technology. On complexity and unreliable systems there was no difference at all.",
                  "สองกลุ่มต่างกันไหม", "Did the groups differ",
                  "ต่างกันด้านเดียว คือความไม่แน่นอน · ความซับซ้อนและระบบไม่มั่นคง ไม่ต่าง",
                  "Differed on one thing only, uncertainty · no difference on complexity or reliability",
                  "วงกลมกระดาษสองวงขนาดเท่ากัน ซ้อนเหลื่อมกันเล็กน้อย — สองกลุ่มที่แทบเหมือนกัน",
                  "exactly TWO flat paper circles of identical size lying on the table and overlapping each other slightly. Two objects, nothing else."),
            scene("finding", 14,
                  "เรื่องมุมมองต่อการเรียน นิสิตสายที่ไม่ใช่วิทย์เป็นบวกกว่าทั้งสองแบบ แต่ต่างอย่างมีนัยสำคัญเฉพาะแบบเรียนจากสิ่งที่บันทึกไว้ และคะแนนมุมมองต่อการเรียนออนไลน์ของทุกกลุ่ม อยู่ราวสามจากห้าเท่านั้น คืออยู่ตรงกลาง ไม่ได้ชอบ และไม่ได้เกลียด",
                  "On views of the modes, non-science students were more positive about both, but significantly so only for recorded material. And every group rated online learning at around three out of five: right in the middle, neither liked nor disliked.",
                  "ชอบเรียนออนไลน์ไหม", "Did they like it",
                  "มุมมองต่อการเรียนออนไลน์ ราว 3 จาก 5 ทุกกลุ่ม · สายอื่นชอบ แบบบันทึกไว้ มากกว่า",
                  "Online learning rated about 3 of 5 by every group · non-science preferred recorded material",
                  "วงแหวนกระดาษหนึ่งวง มีสามเหลี่ยมกระดาษเล็กอยู่ข้างใน — ปุ่มเล่นของบทเรียนที่บันทึกไว้",
                  "ONE flat paper ring lying on the table with ONE small paper triangle (a play symbol) resting inside it. Two objects, nothing else."),
            scene("lesson", 20,
                  "บทเรียนคือ เมื่อด้านที่สูงคือปริมาณ ส่วนด้านความซับซ้อนกลับต่ำ การอบรมให้ใช้เครื่องมือเป็น จึงไม่ใช่คำตอบ สิ่งที่ต้องจัดการคือจำนวนแพลตฟอร์ม และจำนวนกำหนดส่งที่วิ่งเข้ามาพร้อมกันจากหลายวิชา ผู้วิจัยเสนอให้ลดจำนวนระบบที่ใช้ในหลักสูตรเดียวกัน และเพิ่มสัดส่วนการเรียนจากสิ่งที่บันทึกไว้ ให้ผู้เรียนจัดจังหวะเองได้",
                  "The lesson: when the high score is quantity and complexity is low, training people to use the tools is not the answer. What has to be managed is the number of platforms, and the number of deadlines arriving together from different courses. The researcher recommends fewer systems within a single programme, and more recorded material so that students can set their own pace.",
                  "บทเรียน", "The lesson",
                  "อบรมใช้เครื่องมือ ไม่ใช่คำตอบ · ลดจำนวนระบบในหลักสูตร · เพิ่มการเรียนจากที่บันทึกไว้ ให้จัดจังหวะเอง",
                  "Tool training is not the answer · fewer systems per programme · more recorded material, self-paced",
                  "ลูกบาศก์กระดาษใหญ่หนึ่งก้อน ข้างลูกบาศก์เล็กสามก้อนเรียงแถว — หลายระบบยุบเหลือหนึ่ง",
                  "ONE large paper cube standing beside exactly THREE much smaller paper cubes lined up in a row. Four objects, nothing else."),
            caveat("ข้อควรระวัง เก็บจากมหาวิทยาลัยเดียวและนิสิตรุ่นเดียว ในช่วงที่ต้องย้ายมาเรียนออนไลน์ทั้งหมด เป็นความรู้สึกที่รายงานเอง ไม่ใช่ภาระงานที่วัดจริง และผู้วิจัยเสนอให้ทำสัมภาษณ์เชิงลึกต่อ",
                   "One caution: one university, one cohort, during a period of fully online teaching. These are self-reported feelings, not measured workload, and the researcher calls for interviews as a follow-up.",
                   "มหาวิทยาลัยเดียว รุ่นเดียว · ช่วงเรียนออนไลน์ทั้งหมด · ความรู้สึกที่รายงานเอง ไม่ใช่ภาระงานจริง",
                   "One university, one cohort · fully online period · self-reported, not measured workload"),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "joox", "batch": 3,
        "slug": "joox-rooms-relational-bonds",
        "name_th": "ห้องไลฟ์ของแฟนเพลง รักศิลปินหรือรักแพลตฟอร์ม",
        "name_en": "Live rooms: loving the artist or the platform",
        "label": {"th": "งานวิจัย · สื่อบันเทิงและแพลตฟอร์ม", "en": "Research · Entertainment platforms"},
        "scenes": [
            scene("hook", 9,
                  "ห้องไลฟ์ที่แฟนเพลงคุยกับศิลปินได้ทันที อะไรทำให้คนผูกพันกับแพลตฟอร์ม … และเขารักศิลปิน หรือรักแอป",
                  "A live room where fans can talk to artists in real time. What makes people attach to the platform … and is it the artist they love, or the app?",
                  "งานวิจัย · สื่อบันเทิงและแพลตฟอร์ม", "Research · Entertainment platforms",
                  "แฟนเพลงแยกไม่ออก ว่ารักศิลปินหรือรักแพลตฟอร์ม และนั่นคือข้อค้นพบ ไม่ใช่ความบกพร่องของแบบวัด",
                  "Fans could not separate loving the artist from loving the platform. That is the finding, not a flaw in the instrument",
                  "ภาพประจำบทความ (มีแล้ว): รูปทรงมนสองรูปซ้อนกันเกือบสนิท — สองสิ่งที่แยกจากกันไม่ได้", None, image="existing"),
            scene("method", 19,
                  "ทีมวิจัยสำรวจออนไลน์ผู้ใช้ห้องไลฟ์ จูกซ์ รูมส์ ในไทย ช่วงเมษายนถึงพฤษภาคมสองพันห้าร้อยหกสิบเจ็ด ได้ข้อมูลที่ใช้ได้หนึ่งร้อยเจ็ดสิบห้าคน แล้ววิเคราะห์ด้วยโมเดลสมการโครงสร้าง แยกสายสัมพันธ์สามแบบ คือด้านการเงิน เช่นส่วนลดและเหรียญในระบบ ด้านสังคม เช่นแชตสดและการตอบกลับของศิลปิน และด้านโครงสร้าง เช่นระบบที่ใช้ได้จริงและการตอบอย่างมืออาชีพ",
                  "The research team surveyed users of JOOX Rooms in Thailand in April and May twenty twenty-four, keeping one hundred and seventy-five usable responses, and analysed them with structural equation modelling, separating three kinds of bond: financial, such as discounts and in-app coins; social, such as live chat and artists responding; and structural, such as a reliable service and professional replies.",
                  "ทำอะไร", "What was done",
                  "ผู้ใช้ 175 คน · สายสัมพันธ์ 3 แบบ · การเงิน สังคม โครงสร้าง",
                  "175 users · three bonds · financial, social, structural",
                  "ริบบิ้นกระดาษสามเส้นยาวเท่ากัน ผูกรวมปลายหนึ่งแล้วบานออก — สายสัมพันธ์สามแบบ",
                  "exactly THREE flat paper ribbons of equal length, joined together at one end in a small knot and fanning apart toward the other end. Three pieces, nothing else."),
            scene("finding", 14,
                  "สายสัมพันธ์ทั้งสามแบบ เพิ่มความผูกพันทางอารมณ์กับแพลตฟอร์ม และความผูกพันนั้นทำนายความตั้งใจจะใช้ต่อและบอกต่อ แต่ไม่มีสายไหนผลักดันพฤติกรรมโดยตรง ทั้งหมดส่งผลผ่านความรู้สึกผูกพันเท่านั้น",
                  "All three bonds increased emotional attachment to the platform, and that attachment predicted intentions to keep using it and to recommend it. But none of the bonds drove behaviour directly. Everything worked through how users felt.",
                  "ผ่านความรู้สึกเท่านั้น", "Only through feeling",
                  "3 สายสัมพันธ์ → ความผูกพัน → ใช้ต่อและบอกต่อ · ไม่มีทางลัด ที่ข้ามความรู้สึก",
                  "3 bonds → attachment → keep using and recommend · no shortcut past feeling",
                  "ลูกศรกระดาษสั้นสามอันชี้เข้าหาหัวใจกระดาษดวงเดียวตรงกลาง — ทุกทางผ่านความรู้สึก",
                  "exactly THREE short flat paper arrows pointing inward toward ONE paper heart shape at the centre. Four pieces in total, nothing else."),
            scene("finding", 18,
                  "แต่ข้อค้นพบที่น่าสนใจที่สุด มาจากตัวแปรที่ต้องตัดทิ้ง ความผูกพันกับศิลปิน กับความผูกพันกับแพลตฟอร์ม สัมพันธ์กันสูงถึงจุดแปดเก้า จนโมเดลคำนวณไม่ได้ ทีมวิจัยจึงต้องตัดตัวแปรศิลปินออก สมมติฐานทุกข้อที่เกี่ยวกับศิลปิน จึงทดสอบไม่ได้ ไม่ใช่ไม่พบผล",
                  "But the most interesting finding came from a variable that had to be dropped. Attachment to artists and attachment to the platform correlated at point eight nine, so tightly that the model could not be estimated. The team had to remove the artist variable. Every hypothesis about artists is therefore untested, not disproved.",
                  "ตัวแปรที่ต้องตัดทิ้ง", "The variable that had to go",
                  "ผูกพันกับศิลปิน กับ ผูกพันกับแพลตฟอร์ม สัมพันธ์กันสูงถึง .89 · แยกวัดไม่ได้ · ทดสอบไม่ได้ ไม่ใช่ไม่พบ",
                  "Artist vs platform attachment r = .89 · could not be separated · untested, not disproved",
                  "วงกลมกระดาษสองวงซ้อนกันจนเกือบเป็นรูปเดียว — สองความรู้สึกที่แยกไม่ออก",
                  "exactly TWO flat paper circles lying on the table and overlapping so far that they almost form a single shape. Two objects, nothing else."),
            scene("finding", 14,
                  "แต่ละสายสัมพันธ์สร้างความผูกพันคนละชนิด ส่วนลดสร้างความผูกพันแบบแลกเปลี่ยน แชตสดสร้างความใกล้ชิด ระบบที่เสถียรสร้างความไว้วางใจ ถ้าเลือกทำแต่ด้านราคา จะได้ยอดใช้งานระยะสั้นที่ไม่มีความลึก",
                  "Each bond produces a different kind of attachment. Discounts produce a transactional bond, live chat produces closeness, a reliable service produces trust. Build on price alone and you get short-term activity with no depth.",
                  "สามชนิดของความผูกพัน", "Three kinds of attachment",
                  "ส่วนลด = แลกเปลี่ยน · แชตสด = ใกล้ชิด · ระบบเสถียร = ไว้วางใจ",
                  "Discounts = transaction · live chat = closeness · reliability = trust",
                  "เหรียญกระดาษ กรอบคำพูดกระดาษ และโล่กระดาษ วางเรียงกัน — สามชนิดของความผูกพัน",
                  "ONE small flat paper coin, ONE small flat paper speech bubble and ONE small flat paper shield lying in a row. Three objects, nothing else."),
            scene("lesson", 19,
                  "บทเรียนสำหรับแพลตฟอร์มและค่ายเพลงคือ ต้องลงทุนทั้งสามด้านพร้อมกัน และข้อค้นพบที่ทำให้ต้องตัดตัวแปรทิ้ง กลับมีนัยเชิงปฏิบัติมากที่สุด ถ้าผู้ฟังแยกความรู้สึกที่มีต่อศิลปิน ออกจากแพลตฟอร์มไม่ได้ การย้ายแพลตฟอร์มก็มีต้นทุนทางความรู้สึกติดอยู่ด้วย ไม่ใช่แค่ต้นทุนการเปลี่ยนแอป",
                  "The lesson for platforms and labels is to invest in all three bonds at once. And the finding that forced a variable out of the model is the most practical of all: if listeners cannot separate what they feel about an artist from what they feel about the platform, then switching platforms carries an emotional cost, not merely the cost of installing another app.",
                  "บทเรียน", "The lesson",
                  "ลงทุนทั้ง 3 ด้านพร้อมกัน · ย้ายแพลตฟอร์ม มีต้นทุนทางความรู้สึก ไม่ใช่แค่เปลี่ยนแอป",
                  "Invest in all three bonds · switching platforms costs feeling, not just an app install",
                  "หัวใจกระดาษหนึ่งดวง มีแม่กุญแจกระดาษเล็กวางอยู่บนนั้น — ความรู้สึกที่ล็อกไว้กับแพลตฟอร์ม",
                  "ONE flat paper heart shape lying on the table with ONE small paper padlock resting on top of it. Two objects, nothing else."),
            caveat("ข้อควรระวัง เก็บตัวอย่างแบบบอกต่อ จึงเอนไปทางผู้ใช้ที่ผูกพันสูงอยู่แล้ว วัดครั้งเดียวจึงบอกลำดับเวลาไม่ได้ และเก็บจากแพลตฟอร์มเดียวในประเทศเดียว งานนี้ไม่ได้บอกว่าศิลปินไม่สำคัญ แต่บอกว่าเครื่องมือชุดนี้ วัดแยกจากแพลตฟอร์มไม่ได้",
                   "One caution: snowball sampling skews toward users who were already highly engaged, a single survey cannot establish sequence, and it covers one platform in one country. The study does not say artists do not matter. It says this instrument could not separate them from the platform.",
                   "เอนไปทางผู้ใช้ที่ผูกพันสูง · วัดครั้งเดียว · แพลตฟอร์มเดียว · ไม่ได้แปลว่า ศิลปินไม่สำคัญ",
                   "Skewed to engaged users · one survey · one platform · not that artists do not matter", secs=(11, 11)),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "vtuber", "batch": 3,
        "slug": "vtuber-streamer-purchase-intention",
        "name_th": "วีทูปเบอร์ สตรีมเมอร์ และความน่าเชื่อถือ",
        "name_en": "VTubers, streamers and credibility",
        "label": {"th": "งานวิจัย · การตลาดอินฟลูเอนเซอร์", "en": "Research · Influencer marketing"},
        "scenes": [
            scene("hook", 8,
                  "อินฟลูเอนเซอร์สายเกมสองแบบ ตัวละครเสมือน กับคนจริง … อะไรทำให้ผู้ชมอยากซื้อของที่เขาแนะนำ",
                  "Two kinds of gaming influencer, a virtual character and a real person … what makes viewers want to buy what they recommend?",
                  "งานวิจัย · การตลาดอินฟลูเอนเซอร์", "Research · Influencer marketing",
                  "ความน่าเชื่อถือคนละแบบ ได้ผลกับคนละกลุ่ม ความเชี่ยวชาญ ขายของให้แฟนตัวจริง หน้าตา ขายให้คนทั่วไป",
                  "Different kinds of credibility work on different audiences. Expertise sells to true fans, looks sell to everyone else",
                  "ภาพประจำบทความ (มีแล้ว): ตาชั่งสองอัน ลูกบาศก์กับลูกกลมเอียงคนละทาง — น้ำหนักที่ต่างกันตามกลุ่ม", None, image="existing"),
            scene("method", 19,
                  "ทีมวิจัยสำรวจออนไลน์ผู้เล่นเกมหญิงชาวไทย หกร้อยแปดสิบหกคน ที่ติดตามอินฟลูเอนเซอร์สายเกมหญิงอย่างน้อยหนึ่งคน ในจำนวนนี้ระบุตนเองว่าเป็นโอตาคุ หนึ่งร้อยห้าคน ใช้อินฟลูเอนเซอร์จริงสองคนเป็นสิ่งเร้า คนหนึ่งเป็นวีทูปเบอร์ที่เป็นตัวละครเสมือน อีกคนเป็นสตรีมเมอร์ที่เป็นคนจริง แล้ววัดความน่าเชื่อถือสามด้าน คือความเชี่ยวชาญ ความน่าดึงดูด และความน่าไว้วางใจ",
                  "The research team surveyed six hundred and eighty-six Thai women gamers who follow at least one female gaming influencer, one hundred and five of whom identified as otaku. Two real influencers served as stimuli, a VTuber who is a virtual character and a streamer who is a real person, and viewers rated three kinds of credibility: expertise, attractiveness and trustworthiness.",
                  "ทำอะไร", "What was done",
                  "ผู้เล่นเกมหญิง 686 คน · โอตาคุ 105 คน · วีทูปเบอร์ กับ สตรีมเมอร์ · ความน่าเชื่อถือ 3 ด้าน",
                  "686 women gamers · 105 otaku · VTuber vs streamer · three kinds of credibility",
                  "จอยเกมกระดาษแบนหนึ่งอัน มีปุ่มกลมเล็กสองปุ่ม — ผู้ชมสายเกม",
                  "ONE flat paper game controller shape (a rounded rectangle with two small round paper buttons on its right side) lying on the table. One object, nothing else."),
            scene("finding", 12,
                  "เมื่อรวมทั้งสองแบบ ทั้งสามด้านทำนายความตั้งใจซื้อได้ ความเชี่ยวชาญมาก่อน ตามด้วยความน่าไว้วางใจ และความน่าดึงดูด แต่พอแยกดูทีละแบบ ภาพกลับต่างกันชัด",
                  "Taken together, all three predicted purchase intention: expertise first, then trustworthiness, then attractiveness. But separate the two influencers, and the picture changed completely.",
                  "ภาพรวม", "Overall",
                  "รวมสองแบบ ทำนายได้ทั้ง 3 ด้าน · เชี่ยวชาญ .33 · ไว้วางใจ .24 · ดึงดูด .19",
                  "Combined, all three predict · expertise .33 · trust .24 · attractiveness .19",
                  "วงกลมกระดาษสามวงขนาดลดหลั่นเรียงแถว — สามด้านที่มีน้ำหนักต่างกัน",
                  "exactly THREE flat paper circles of decreasing size lying in a row from large to small. Three objects, nothing else."),
            scene("finding", 16,
                  "สำหรับวีทูปเบอร์ ตัวทำนายคือความเชี่ยวชาญและความน่าไว้วางใจ ส่วนความน่าดึงดูดไม่มีนัยสำคัญ แต่สำหรับสตรีมเมอร์กลับตรงข้าม ตัวทำนายคือความน่าไว้วางใจและความน่าดึงดูด ส่วนความเชี่ยวชาญไม่มีนัยสำคัญเลย",
                  "For the VTuber, the predictors were expertise and trustworthiness, and attractiveness did not matter. For the streamer it was the other way round: trustworthiness and attractiveness predicted buying, and expertise did not matter at all.",
                  "ตัวละครเสมือน กับ คนจริง", "Virtual vs real",
                  "วีทูปเบอร์: เชี่ยวชาญ .42 ไว้วางใจ .26 · สตรีมเมอร์: ไว้วางใจ .44 ดึงดูด .23",
                  "VTuber: expertise .42, trust .26 · streamer: trust .44, attractiveness .23",
                  "ลูกบาศก์กระดาษกับลูกกลมกระดาษขนาดเท่ากันวางคู่กัน — ตัวละครเสมือนกับคนจริง",
                  "ONE small paper cube and ONE paper sphere of the same size standing side by side with a small gap between them. Two objects, nothing else."),
            scene("finding", 15,
                  "กลุ่มโอตาคุให้คะแนนความเชี่ยวชาญสูงกว่า และมีความตั้งใจซื้อสูงกว่ากลุ่มอื่นอย่างชัดเจน สำหรับพวกเขา ความเชี่ยวชาญสำคัญที่สุด ส่วนคนที่ไม่ใช่โอตาคุ ความน่าดึงดูดมีอิทธิพลมากที่สุด และความน่าไว้วางใจไม่มีนัยสำคัญ",
                  "Otaku rated expertise higher and had clearly stronger purchase intentions than other viewers. For them, expertise mattered most. For non-otaku, attractiveness carried the most weight, and trustworthiness did not matter.",
                  "แฟนตัวจริง กับ คนทั่วไป", "True fans vs everyone else",
                  "โอตาคุ: เชี่ยวชาญมาก่อน · ไม่ใช่โอตาคุ: ดึงดูดมาก่อน ไว้วางใจไม่มีผล",
                  "Otaku: expertise first · non-otaku: attractiveness first, trust no effect",
                  "ดาวกระดาษหนึ่งดวงกับหัวใจกระดาษหนึ่งดวงวางคู่กัน — ฝีมือกับความชอบ",
                  "ONE flat paper star shape and ONE flat paper heart shape lying side by side. Two objects, nothing else."),
            scene("lesson", 19,
                  "บทเรียนสำหรับแบรนด์คือ ใช้ข้อค้นพบนี้เลือกคนและเลือกสารให้ตรงขึ้น ถ้ากลุ่มเป้าหมายเป็นแฟนตัวจริงของหมวดนั้น สิ่งที่ต้องพิสูจน์คือความรู้จริงในเรื่องนั้น ไม่ใช่ภาพลักษณ์ เนื้อหาจึงควรให้เห็นฝีมือและความเข้าใจสินค้า แต่ถ้าเป็นผู้ชมทั่วไป ความรู้สึกชอบและความคุ้นเคยทำงานมากกว่า",
                  "The lesson for brands is to use this to choose the person and the message more precisely. If the audience are true fans of the category, what has to be proven is real knowledge of it, not image, so the content should show skill and understanding of the product. If the audience is general, liking and familiarity do more of the work.",
                  "บทเรียน", "The lesson",
                  "แฟนตัวจริง: พิสูจน์ความรู้จริง ไม่ใช่ภาพลักษณ์ · คนทั่วไป: ความชอบและความคุ้นเคย",
                  "True fans: prove real knowledge, not image · general audience: liking and familiarity",
                  "ถ้วยรางวัลกระดาษใบเล็กมีหูสองข้างตั้งอยู่ — ฝีมือที่พิสูจน์ได้",
                  "ONE small paper trophy cup with two small paper handles, standing upright on a short paper base. One object, nothing else."),
            caveat("ข้อควรระวัง เก็บจากผู้เล่นเกมหญิงในไทยเท่านั้น กลุ่มโอตาคุมีเพียงหนึ่งร้อยห้าคน เทียบกับอีกกลุ่มห้าร้อยแปดสิบเอ็ดคน ใช้อินฟลูเอนเซอร์เพียงสองคนเป็นสิ่งเร้า และเป็นความตั้งใจซื้อที่รายงานเอง ไม่ใช่การซื้อจริง",
                   "One caution: the sample was Thai women gamers only, the otaku group had just one hundred and five people against five hundred and eighty-one, only two influencers served as stimuli, and these are self-reported intentions, not actual purchases.",
                   "ผู้เล่นเกมหญิงในไทยเท่านั้น · โอตาคุ 105 คน กับ 581 คน · สิ่งเร้า 2 คน · ความตั้งใจ ไม่ใช่การซื้อจริง",
                   "Thai women gamers only · 105 otaku vs 581 · two stimuli · intentions, not purchases", secs=(11, 11)),
            closing(),
        ],
    },
]
