"""สตอรี่บอร์ดชุดที่ 6 — 5 เรื่อง × ไทย/อังกฤษ (5 ก.ย. 2569 · รอผู้ใช้อนุมัติงบหลัง 10 ก.ย.) — storyboard.py นำเข้าไฟล์นี้แล้วต่อท้าย CLIPS/PALETTE

กติกาเดียวกับชุดที่ 2–5 (บทพากย์เป็นภาษาพูด ผ่าน check_narration.py ก่อนอัด · ศูนย์ฯ เป็นผู้เล่า ไม่ใช่ผู้ทำ · ภาพนับวัตถุไม่เกินสี่ชิ้น) · ข้อเพิ่มของชุดนี้:
  · ทั้งห้าเรื่องเป็นงานไทยจาก ThaiJO ที่ทะเบียนเพิ่งได้ `citation` จาก meta tag ของ OJS (5 ก.ย.) การ์ดปิดจึงใส่ชื่อผู้เขียนได้แล้ว
    (คลิปความปลอดภัยบนเครื่องบินเคยถูกสลับออกจากชุดที่ 2 เพราะเหตุนี้)
  · สามเรื่อง (ลดเค็ม · แอปเรียกบริการ · รายการเล่าเรื่องผี) ต่อยอดจากวิทยานิพนธ์ของนิสิตที่ ผศ.ดร.ธีรดา เป็นที่ปรึกษา (ระบุในเชิงอรรถของบทความ)
    บทจึงมีประโยค "งานนี้ต่อยอดจากผลงานวิจัยของนิสิตคณะนิเทศศาสตร์ โดยมีอาจารย์ของศูนย์คอมอินโนเป็นที่ปรึกษา" ตามถ้อยคำที่ผู้ใช้เลือก
  · กติกาข้อ 5: ชื่อแอป (ไลน์แมน แกร็บ) ชื่อรายการ (เดอะโกสต์เรดิโอ อังคารคลุมโปง) ชื่อผู้เดินและมูลนิธิในเรื่องแม่วงก์ เอ่ยได้เพราะเป็นขอบเขตของงาน
    ไม่ใช่เป้าของข้อวิจารณ์ และฉากข้อควรระวังบอกผู้ชมเช่นนั้น · สถานีโทรทัศน์ที่ระงับสารคดีเรื่องแม่วงก์ **ไม่เอ่ยชื่อ** (บทความระบุ) · นักการเมืองไม่เอ่ยชื่อ
  · ตัวเลขทุกตัวมาจากตารางผลของบทความ (papers6/*.txt สกัดจาก PDF ทางการของ ThaiJO) ไม่ใช่จากบทคัดย่อ
"""
from storyboard_batch2 import CLOSING2, ASTERISK

CLOSING6 = CLOSING2

# คู่สีอ่านจากภาพประจำบทความของแต่ละเรื่อง (นับพิกเซลที่อิ่มสีของไฟล์ -800.webp แล้วดูภาพจริงว่าสีไหนเป็นวัตถุ สีไหนเป็นเงา)
PALETTE6 = {
    "flight": {"object": "warm golden yellow", "shadow": "soft salmon pink", "obj_hex": "#F4C463", "sh_hex": "#F19381",
               "shadow_style": "clean flat-edged shadows to the lower right rendered as solid salmon-pink shapes, like cut paper rather than soft photographic shadows"},
    "sodium": {"object": "olive green", "shadow": "light sky blue", "obj_hex": "#9FA065", "sh_hex": "#8FBAD6",
               "shadow_style": "clean flat-edged shadows to the lower right rendered as solid light-sky-blue shapes, like cut paper rather than soft photographic shadows"},
    "ondemand": {"object": "light sky blue", "shadow": "muted raspberry pink", "obj_hex": "#92BFE0", "sh_hex": "#B8607F",
                 "shadow_style": "clean flat-edged shadows to the lower right rendered as solid muted-raspberry shapes, like cut paper rather than soft photographic shadows"},
    "horror": {"object": "deep raspberry", "shadow": "olive khaki", "obj_hex": "#A8345B", "sh_hex": "#8E8A5C",
               "shadow_style": "clean flat-edged shadows to the lower right rendered as solid olive-khaki shapes, like cut paper rather than soft photographic shadows"},
    "maewong": {"object": "olive green", "shadow": "pale sky blue", "obj_hex": "#7C7A48", "sh_hex": "#A9C7E3",
                "shadow_style": "clean flat-edged shadows to the lower right rendered as solid pale-sky-blue shapes, like cut paper rather than soft photographic shadows"},
}

STUDENT_TH = "งานนี้ต่อยอดจากผลงานวิจัยของนิสิตคณะนิเทศศาสตร์ โดยมีอาจารย์ของศูนย์คอมอินโนเป็นที่ปรึกษา"
STUDENT_EN = "The study grew out of a student's research project at the Faculty of Communication Arts, supervised by a ComInno Center lecturer."


def closing():
    return {"role": "closing", "secs": (14, 14), "image": "logo", "narr": CLOSING6, "label": None, "text": None,
            "visual_th": "การ์ดปิดประจำชุด + ชื่อผู้เขียนทุกคน (ไม่ต้องเจนภาพ)", "subject": None}


def caveat(narr_th, narr_en, text_th, text_en, secs=(11, 11)):
    return {"role": "caveat", "secs": secs, "image": "new", "narr": {"th": narr_th, "en": narr_en},
            "label": {"th": "ข้อควรระวัง", "en": "One caution"}, "text": {"th": text_th, "en": text_en},
            "visual_th": "ดอกจันกระดาษพับหนึ่งดอก — สัญลักษณ์ประจำฉากข้อควรระวัง (คู่สีของคลิปนี้)", "subject": ASTERISK}


def scene(role, secs, narr_th, narr_en, label_th, label_en, text_th, text_en, visual_th, subject, image="new"):
    return {"role": role, "secs": (secs, secs), "image": image, "narr": {"th": narr_th, "en": narr_en},
            "label": {"th": label_th, "en": label_en}, "text": {"th": text_th, "en": text_en},
            "visual_th": visual_th, "subject": subject}


CLIPS6 = [
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "flight", "batch": 6,
        "slug": "slow-paced-flight-safety-videos",
        "name_th": "วิดีโอความปลอดภัยบนเครื่องบินแบบช้าและเรียบง่าย",
        "name_en": "Slow, simple in-flight safety videos",
        "label": {"th": "งานวิจัย · สื่อสารความปลอดภัย", "en": "Research · Safety communication"},
        "scenes": [
            scene("hook", 9,
                  "ผู้โดยสารแค่สามสิบถึงสี่สิบเปอร์เซ็นต์ที่ตั้งใจฟังสาธิตความปลอดภัยก่อนเครื่องขึ้น … แล้ววิดีโอที่ช้าและเรียบง่าย จะทำให้วัยรุ่นที่ไม่เคยขึ้นเครื่องรู้เรื่องได้แค่ไหน",
                  "Only thirty to forty percent of passengers pay attention to the safety briefing … so how much can a slow, simple video teach teenagers who have never flown?",
                  "งานวิจัย · สื่อสารความปลอดภัย", "Research · Safety communication",
                  "ช้า เรียบง่าย ไม่มีสิ่งรบกวน แล้ววัยรุ่นได้คะแนนเกือบเต็ม",
                  "Slow, simple, no distractions, and teenagers scored almost full marks",
                  "ภาพประจำบทความ (มีแล้ว): แท่งกระดาษสองแท่ง แผ่นกระดาษพาดบนแท่งสูงเหมือนฝา — คะแนนที่ชนเพดาน", None, image="existing"),
            scene("method", 17,
                  "ทีมวิจัยทดลองกับนักเรียนอาสาสมัครร้อยยี่สิบแปดคน อายุสิบสี่ถึงสิบหกปี ในโรงเรียนรัฐแห่งหนึ่งใกล้กรุงเทพที่ไม่มีสนามบิน ครึ่งหนึ่งเคยขึ้นเครื่องบิน อีกครึ่งไม่เคย ทุกคนทำข้อสอบถูกผิดยี่สิบข้อเรื่องความปลอดภัยก่อน แล้วจับคู่ตามคะแนนแบ่งเป็นสองกลุ่ม กลุ่มหนึ่งดูวิดีโอความปลอดภัยยาวห้านาทีครึ่ง ที่พูดช้ากว่าร้อยสี่สิบคำต่อนาทีและตัดสิ่งรบกวนออก อีกกลุ่มดูคลิปตลกยาวเท่ากัน แล้วทำข้อสอบชุดเดิมอีกครั้ง",
                  "The research team ran an experiment with one hundred and twenty-eight student volunteers aged fourteen to sixteen at a state school near Bangkok, in a town with no airport. Half had flown before, half never had. Everyone took a twenty-item true-or-false safety test first, then was matched by score into two groups. One group watched a five-and-a-half-minute safety video spoken at under one hundred and forty words a minute with distractions stripped out. The other watched a comedy clip of the same length. Then both took the same test again.",
                  "ทำอะไร", "What was done",
                  "นักเรียน 128 คน อายุ 14–16 ปี · เคยบิน 64 คน ไม่เคย 64 คน · ข้อสอบ 20 ข้อ ก่อนและหลัง · วิดีโอ 5 นาทีครึ่ง พูดช้า",
                  "128 students aged 14–16 · 64 had flown, 64 had not · 20-item test before and after · one slow 5½-minute video",
                  "จอกระดาษหนึ่งจอ มีปุ่มเล่นสามเหลี่ยมกลางจอ — วิดีโอที่ให้ดู",
                  "ONE flat rectangular paper screen lying on the surface with ONE small flat paper triangle at its centre like a play button. Two objects, nothing else."),
            scene("finding", 16,
                  "ทุกกลุ่มได้คะแนนรอบสองสูงขึ้น แม้แต่กลุ่มที่ดูคลิปตลก เพราะทำข้อสอบชุดเดิมซ้ำ แต่ขนาดของผลต่างกันหลายเท่า กลุ่มที่ดูวิดีโอความปลอดภัยได้เกือบเต็ม เฉลี่ยสิบเก้าจุดสี่ถึงสิบเก้าจุดห้า จากยี่สิบคะแนน ส่วนกลุ่มดูคลิปตลกได้สิบห้าจุดหกถึงสิบหกจุดสี่ ทั้งที่ก่อนดูทั้งสองกลุ่มอยู่ที่ราวสิบสี่ถึงสิบห้าเท่ากัน",
                  "Every group scored higher the second time, even the comedy group, simply because they took the same test again. But the size of the gain was several times apart. The group that watched the safety video came close to a perfect score, averaging nineteen point four to nineteen point five out of twenty. The comedy group reached fifteen point six to sixteen point four. Before the videos, both groups sat at around fourteen to fifteen.",
                  "พบอะไร", "What was found",
                  "ก่อนดู ราว 14–15 คะแนน · ดูวิดีโอ → 19.4–19.5 · ดูคลิปตลก → 15.6–16.4 · เต็ม 20",
                  "Both start around 14–15 · safety video → 19.4–19.5 · comedy → 15.6–16.4 · out of 20",
                  "ลูกศรกระดาษสองอันชี้ขึ้น อันหนึ่งสูงมาก อีกอันเตี้ย — สองกลุ่มขึ้นไม่เท่ากัน",
                  "ONE tall folded paper arrow pointing straight up and ONE much shorter paper arrow pointing up beside it, both standing on the surface. Two objects, nothing else."),
            scene("finding", 15,
                  "ที่น่าสนใจคือ ประสบการณ์บินไม่ทำให้ต่างกันเลย คนที่ไม่เคยขึ้นเครื่องสักครั้ง ขึ้นจากสิบสี่มาเป็นสิบเก้าจุดห้า ไม่ต่างจากคนที่เคยบิน และเพศก็ไม่มีผล นักเรียนชายได้สิบเจ็ดจุดแปด นักเรียนหญิงได้สิบเจ็ดจุดเจ็ด เท่ากันในทางปฏิบัติ",
                  "The interesting part is that flying experience made no difference at all. Students who had never been on a plane went from fourteen to nineteen point five, on a par with those who had. Gender made no difference either: boys averaged seventeen point eight, girls seventeen point seven, the same for practical purposes.",
                  "ใครได้ผล", "Who it worked for",
                  "ไม่เคยบิน 14.1 → 19.5 เท่ากับคนเคยบิน · ชาย 17.8 หญิง 17.7 ไม่ต่างกัน",
                  "Never flown 14.1 → 19.5, same as those who had · boys 17.8, girls 17.7, no difference",
                  "เครื่องบินกระดาษพับสองลำเหมือนกันวางเคียงกัน ชี้ทางเดียวกัน — ใครก็ได้ผลเท่ากัน",
                  "exactly TWO identical small folded paper airplanes lying side by side on the surface, both pointing the same way. Two objects, nothing else."),
            scene("finding", 15,
                  "ในวงสนทนาหลังดู นักเรียนบอกว่าวิดีโอน่าสนใจ ไม่น่าเบื่อ และไม่มีอะไรอยากให้แก้ แต่ทีมวิจัยชี้ว่ามีสองโจทย์ที่ต้องแยกกัน หนึ่งคือดึงให้คนหันมาดู สองคือรักษาความสนใจไว้จนความรู้ส่งถึง วิดีโอช้าและเรียบง่ายทำข้อสองได้ดีมาก แต่อาจแพ้ในข้อแรก",
                  "In the discussion afterwards, students called the video interesting rather than boring, and had nothing they wanted changed. But the team points to two separate problems. One is getting people to look in the first place. The other is holding their attention long enough for the knowledge to land. A slow, simple video does the second very well, and may lose on the first.",
                  "สองโจทย์ที่ต้องแยก", "Two separate problems",
                  "โจทย์ที่ 1 ดึงให้คนหันมาดู · โจทย์ที่ 2 รักษาความสนใจ จนความรู้ส่งถึง · วิดีโอช้าทำโจทย์ที่ 2 ได้ดี",
                  "Problem 1: get people to look · problem 2: hold attention until the knowledge lands · slow video wins problem 2",
                  "ดวงตากระดาษหนึ่งดวง มีวงกลมเล็กเป็นตาดำ — ความสนใจ",
                  "ONE flat paper almond-shaped eye outline lying on the surface with ONE small flat paper disc inside it as the pupil. Two objects, nothing else."),
            scene("lesson", 22,
                  "บทเรียนสำหรับคนทำสื่อสอนเรื่องความปลอดภัย หรือสื่อการเรียนทุกชนิดก็คือ จังหวะช้า พูดทีละเรื่อง ไม่มีอะไรรบกวน ส่งความรู้ได้เกือบสมบูรณ์ แม้กับคนที่ไม่มีพื้นเลย และไม่ต้องทำเวอร์ชันแยกชายหญิง แต่ต้องออกแบบทางเข้าด้วย ว่าจะทำอย่างไรให้คนหันมาดูก่อน เพราะข้อมูลที่สอนดีแค่ไหน ก็ไร้ค่าถ้าไม่มีใครมอง ทีมวิจัยเสนอเป็นสมมติฐานที่ยังไม่ได้ทดสอบว่า เปิดด้วยเนื้อหาเร้าใจดึงคนเข้ามาก่อน แล้วค่อยสอนด้วยจังหวะช้า",
                  "The lesson for anyone making safety videos, or teaching videos of any kind, is that a slow pace, one point at a time and nothing to distract delivered the knowledge almost completely, even to people with no background at all, and no separate versions for boys and girls were needed. But the way in has to be designed too: how do you get people to look in the first place? However well the information is taught, it is worth nothing if nobody is watching. The team's suggestion, as a hypothesis still to be tested, is to open with something engaging to draw people in, then teach at a slow pace.",
                  "บทเรียน", "The lesson",
                  "ช้า · ทีละเรื่อง · ไม่มีสิ่งรบกวน · ความรู้ส่งถึงเกือบครบ · แต่ต้องออกแบบทางเข้า ให้คนหันมาดูก่อน",
                  "Slow · one point at a time · nothing to distract · knowledge lands · but design the way in first",
                  "แถบกระดาษยาวหนึ่งเส้นวางเป็นคลื่นช้าโค้งเดียว — จังหวะช้า",
                  "ONE long flat paper strip lying on the surface in a single slow, gentle S-curve. One object, nothing else."),
            caveat("ข้อควรระวัง ทดลองในหอประชุมโรงเรียน ไม่ใช่บนเครื่องบิน นักเรียนถูกผู้ใหญ่บอกให้ดู จึงตั้งใจกว่าผู้โดยสารจริงมาก ไม่มีเสียงรบกวนในห้องโดยสาร ทดสอบรูปแบบเดียว ดูครั้งเดียว วัดความรู้ ไม่ได้วัดว่าจะทำตามจริงเมื่อเกิดเหตุ และเก็บข้อมูลปีสองพันห้าร้อยห้าสิบแปด ตีพิมพ์ปีสองพันห้าร้อยหกสิบสี่",
                   "One caution: this ran in a school hall, not on a plane. The students were told by adults to watch, so they paid far more attention than real passengers do. There was no cabin noise. Only one format was tested, watched once. It measured knowledge, not whether anyone would act on it in an emergency. And the data was collected in twenty fifteen and published in twenty twenty-one.",
                   "หอประชุม ไม่ใช่เครื่องบิน · รูปแบบเดียว ดูครั้งเดียว · วัดความรู้ ไม่ใช่การทำตาม · เก็บข้อมูลปี 2558",
                   "A school hall, not a plane · one format, one viewing · knowledge, not action · data from 2015", secs=(12, 12)),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "sodium", "batch": 6,
        "slug": "retirees-sodium-campaign",
        "name_th": "คนวัยเกษียณกับแคมเปญลดเค็ม",
        "name_en": "Retirees and the salt-reduction campaign",
        "label": {"th": "งานวิจัย · สื่อสารสุขภาพ", "en": "Research · Health communication"},
        "scenes": [
            scene("hook", 9,
                  "รณรงค์ให้คนวัยเกษียณกินเค็มน้อยลง ควรไปหาเขาที่ไหน … ทีมวิจัยถามคนวัยเกษียณในกรุงเทพสี่ร้อยคน แล้วพบว่าช่องทางที่แคมเปญยังทุ่มงบอยู่ กลับเป็นช่องทางที่พวกเขาเจอน้อยที่สุด",
                  "Where should a campaign to cut salt reach retired people? … The research team asked four hundred retirees in Bangkok, and found the channels campaigns still spend on were the ones they saw least.",
                  "งานวิจัย · สื่อสารสุขภาพ", "Research · Health communication",
                  "เจอบนเฟซบุ๊กมากที่สุด เจอทางวิทยุน้อยที่สุด",
                  "Seen most on Facebook, least on radio",
                  "ภาพประจำบทความ (มีแล้ว): กรวยกระดาษห้าอัน อันหนึ่งกว้างกว่าที่เหลือมาก — ช่องทางเดียวที่รับได้กว้าง", None, image="existing"),
            scene("method", 17,
                  "ทีมวิจัยส่งแบบสอบถามออนไลน์ถึงคนวัยเกษียณอายุห้าสิบเอ็ดถึงเจ็ดสิบปีที่อาศัยในกรุงเทพ สี่ร้อยคน แบ่งสัดส่วนตามช่วงอายุจากประชากรจริง ถามสี่เรื่อง เจอสื่อรณรงค์ลดเค็มจากช่องทางไหนบ่อยแค่ไหน ชอบข้อความโน้มน้าวแบบไหน เชื่อเรื่องความเสี่ยงและการป้องกันอย่างไร และคนที่ต่างกันทางเพศ อายุ การศึกษา รายได้ เชื่อต่างกันไหม " + STUDENT_TH,
                  "The research team sent an online questionnaire to four hundred retirees aged fifty-one to seventy living in Bangkok, in proportion to the real population by age band. It asked four things: how often they met salt-reduction campaign messages on each channel, what kind of persuasive message they liked, what they believed about the risk and about protecting themselves, and whether people who differed by gender, age, education or income believed differently. " + STUDENT_EN,
                  "ทำอะไร", "What was done",
                  "วัยเกษียณ 51–70 ปี ในกรุงเทพ 400 คน · แบบสอบถามออนไลน์ · ถาม 4 เรื่อง ช่องทาง ข้อความ ความเชื่อ ความต่าง",
                  "400 Bangkok retirees aged 51–70 · online survey · asked about channels, messages, beliefs, differences",
                  "ขวดเกลือกระดาษพับหนึ่งขวดตั้งอยู่ — เรื่องเค็ม",
                  "ONE small folded paper salt shaker standing upright on the surface. One object, nothing else."),
            scene("finding", 15,
                  "ช่องทางที่คนวัยเกษียณเจอแคมเปญลดเค็มมากที่สุดคือเฟซบุ๊ก รองลงมาคือเว็บไซต์กับยูทูบ ส่วนที่เจอน้อยที่สุดคือวิทยุ ตามด้วยสื่อกิจกรรมและโปสเตอร์ แต่โดยรวมแล้วการเจอสื่อยังอยู่แค่ระดับปานกลาง",
                  "The channel where retirees met the salt campaign most was Facebook, then websites and YouTube. The ones they met least were radio, then events and posters. Overall, though, exposure was only moderate.",
                  "เจอที่ไหน", "Where they saw it",
                  "เจอมากสุด เฟซบุ๊ก · รองลงมา เว็บไซต์ ยูทูบ · เจอน้อยสุด วิทยุ กิจกรรม โปสเตอร์",
                  "Most: Facebook · then websites, YouTube · least: radio, events, posters",
                  "สัญลักษณ์กระดาษยกนิ้วโป้งหนึ่งอันวางแบน — เฟซบุ๊ก",
                  "ONE flat paper thumbs-up shape lying on the surface. One object, nothing else."),
            scene("finding", 16,
                  "ข้อความที่คนวัยเกษียณอยากได้ ชัดมาก คืออยากให้บอกว่าโรคร้ายแรงแค่ไหน และเอาไปใช้ในชีวิตประจำวันได้จริง สิ่งที่พวกเขารับรู้แรงที่สุดคือ กินเค็มประจำเสี่ยงเป็นโรคไต และถ้าเป็นแล้วชีวิตจะกระทบหนัก ส่วนความชอบต่อข้อความแบบนี้ ก็ไปด้วยกันกับความเชื่อเรื่องความเสี่ยงและการป้องกันในระดับปานกลาง",
                  "What retirees wanted from a message was clear: tell them how serious the disease is, and make it something they can use in daily life. What they recognised most strongly was that eating salty food regularly risks kidney disease, and that kidney disease would hit their lives hard. Liking that kind of message went together, moderately, with their beliefs about risk and about protecting themselves.",
                  "ข้อความแบบไหน", "What message",
                  "อยากให้บอกว่าโรคร้ายแรงแค่ไหน · เอาไปใช้ได้จริง · รับรู้แรงสุด กินเค็ม → โรคไต",
                  "Say how serious it is · make it usable · salt → kidney disease believed most",
                  "ป้ายเตือนกระดาษสามเหลี่ยมหนึ่งป้ายตั้งอยู่ — ข้อความบอกความรุนแรง",
                  "ONE flat triangular paper warning sign standing upright on a short paper stand. One object, nothing else."),
            scene("finding", 16,
                  "แล้วใครเชื่อต่างจากใคร จากแปดเรื่องที่ทดสอบ มีแค่สองเรื่องที่ทำให้ความเชื่อด้านสุขภาพต่างกัน คือระดับการศึกษา กับแหล่งรายได้หลัก ส่วนเพศ อายุ สถานภาพ การทำงาน รายได้ต่อเดือน และการอยู่อาศัย ไม่ทำให้ต่างกันเลย และการเจอสื่อบ่อยขึ้น ก็เกี่ยวกับความเชื่อในระดับต่ำถึงต่ำมากทุกด้าน",
                  "So who believes differently? Of eight things tested, only two made health beliefs differ: education, and the main source of income. Gender, age, marital status, working status, monthly income and living arrangement made no difference at all. And seeing the campaign more often was only weakly linked to belief, low to very low on every count.",
                  "ใครต่างจากใคร", "Who differs",
                  "ต่างกันเพราะ การศึกษา · แหล่งรายได้ · อีก 6 เรื่อง ไม่ต่าง · เจอสื่อบ่อยขึ้น เกี่ยวกับความเชื่อน้อยมาก",
                  "Education and income source matter · 6 other traits don't · more exposure, only a weak link to belief",
                  "หนังสือกระดาษพับปิดหนึ่งเล่ม กับเหรียญกระดาษหนึ่งเหรียญวางข้างกัน — การศึกษาและแหล่งรายได้",
                  "ONE small closed folded paper book and ONE flat round paper coin lying beside it. Two objects, nothing else."),
            scene("lesson", 22,
                  "บทเรียนสำหรับคนวางแคมเปญสุขภาพก็คือ อย่าเหมาว่าคนวัยเกษียณอยู่ที่วิทยุกับโปสเตอร์ อย่างน้อยในกรุงเทพ พวกเขาเจอแคมเปญบนเฟซบุ๊กมากที่สุด งบที่ยังทุ่มไปทางเดิมจึงอาจไปไม่ถึง และเพราะกลุ่มที่เชื่อเรื่องสุขภาพน้อยกว่าคือคนที่จบมัธยมหรือต่ำกว่า ทีมวิจัยจึงเสนอให้ส่งข้อความโน้มน้าวไปที่กลุ่มนี้ก่อน ด้วยข้อความที่บอกทั้งความร้ายแรงของโรค และวิธีที่เอาไปทำได้จริงในชีวิตประจำวัน",
                  "The lesson for anyone planning a health campaign is not to assume retirees live on radio and posters. In Bangkok at least, they met the campaign most on Facebook, so money still spent the old way may never reach them. And because the group with weaker health beliefs was people educated to secondary level or below, the team's proposal is to aim persuasive messages at that group first, with messages that say how serious the disease is and how to act on it in everyday life.",
                  "บทเรียน", "The lesson",
                  "ไปหาที่เฟซบุ๊ก ไม่ใช่วิทยุ · เริ่มที่กลุ่มจบมัธยมหรือต่ำกว่า · บอกความร้ายแรง + วิธีทำจริง",
                  "Go to Facebook, not radio · start with secondary education or below · severity and practical steps",
                  "เป้ากระดาษวงกลมซ้อนสามชั้นหนึ่งอันวางแบน — เล็งกลุ่มให้ตรง",
                  "ONE flat paper target of three concentric rings lying on the surface. One object, nothing else."),
            caveat("ข้อควรระวัง เก็บข้อมูลด้วยแบบสอบถามออนไลน์และการบอกต่อ จึงถึงเฉพาะคนวัยเกษียณที่ใช้อินเทอร์เน็ตอยู่แล้ว ซึ่งอธิบายได้ส่วนหนึ่งว่าทำไมเฟซบุ๊กมาเป็นที่หนึ่ง ศึกษาเฉพาะกรุงเทพ และวัดความเชื่อกับความชอบ ไม่ได้วัดว่ากินเค็มน้อยลงจริงหรือไม่",
                   "One caution: the data came from an online questionnaire passed on by word of mouth, so it reached only retirees already online, which partly explains why Facebook came first. It covers Bangkok alone, and it measured beliefs and preferences, not whether anyone actually ate less salt.",
                   "ถามออนไลน์ จึงถึงเฉพาะคนที่ใช้เน็ต · เฉพาะกรุงเทพ · วัดความเชื่อ ไม่ได้วัดการกินจริง",
                   "Online survey reaches only those online · Bangkok only · beliefs measured, not actual eating"),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "ondemand", "batch": 6,
        "slug": "on-demand-app-loyalty",
        "name_th": "ความภักดีต่อแอปเรียกบริการ",
        "name_en": "Loyalty to on-demand service apps",
        "label": {"th": "งานวิจัย · การตลาดดิจิทัล", "en": "Research · Digital marketing"},
        "scenes": [
            scene("hook", 9,
                  "แอปสั่งอาหารและเรียกรถแข่งกันด้วยโฆษณาและส่วนลด … แต่พอทีมวิจัยถามผู้ใช้สี่ร้อยคนว่าอะไรทำให้ติดใจ คำตอบไม่ใช่โฆษณาเลย",
                  "Food-delivery and ride-hailing apps compete on advertising and discounts … but when the research team asked four hundred users what keeps them loyal, advertising was not the answer at all.",
                  "งานวิจัย · การตลาดดิจิทัล", "Research · Digital marketing",
                  "บริการดีทำให้กลับมาใช้ซ้ำ โฆษณาเห็นบ่อยแค่ไหนก็ไม่ช่วย",
                  "Good service brings people back; seeing more ads does not",
                  "ภาพประจำบทความ (มีแล้ว): วัตถุที่ยึดด้วยสายหนาเส้นเดียว ท่ามกลางเส้นบางที่ไม่ยึดอะไร", None, image="existing"),
            scene("method", 17,
                  "ทีมวิจัยส่งแบบสอบถามออนไลน์ถึงคนในกรุงเทพอายุสิบแปดปีขึ้นไป ที่ใช้แอปเรียกบริการแบบครบวงจรอย่างน้อยสามครั้งในสามเดือน ได้มาสี่ร้อยคน เก็บข้อมูลเดือนตุลาคมสองพันห้าร้อยหกสิบสาม ขอบเขตอยู่ที่สองแอปคือไลน์แมนกับแกร็บ ถามว่าเห็นข้อมูลข่าวสารของแอปจากไหนบ่อยแค่ไหน คิดอย่างไรกับราคา โปรโมชัน ความสะดวก พอใจบริการแค่ไหน แล้วให้สามเรื่องนี้แข่งกันอธิบายว่าอะไรทำให้คนภักดี " + STUDENT_TH,
                  "The research team sent an online questionnaire to people in Bangkok aged eighteen and over who had used an all-in-one on-demand app at least three times in three months, and got four hundred answers, collected in October twenty twenty. The scope was two apps, LINE MAN and Grab. It asked where and how often they saw information about the apps, what they thought of the prices, promotions and convenience, how satisfied they were with the service, and then set the three against each other to see which explained loyalty. " + STUDENT_EN,
                  "ทำอะไร", "What was done",
                  "ผู้ใช้ในกรุงเทพ 400 คน · ใช้อย่างน้อย 3 ครั้งใน 3 เดือน · ตุลาคม 2563 · 3 เรื่อง แข่งกันอธิบายความภักดี",
                  "400 Bangkok users · at least three uses in three months · October 2020 · three factors compete to explain loyalty",
                  "กล่องพัสดุกระดาษพับหนึ่งกล่องปิดฝา — ของที่สั่งมาส่ง",
                  "ONE small closed folded paper delivery box with a folded lid, seen from a slight angle. One object, nothing else."),
            scene("finding", 15,
                  "ความภักดีอยู่ในระดับสูงมาก สี่จุดสองหกจากห้า ข้อที่สูงสุดคือจะกลับมาใช้อีก สี่จุดสี่สาม และจะแนะนำคนอื่น สี่จุดสองเจ็ด เหตุผลที่คนเลือกใช้มากที่สุดคือความสะดวก สามสิบห้าเปอร์เซ็นต์ ตามด้วยส่วนลด และแอปใช้ง่าย บริการที่ใช้มากสุดคือสั่งอาหาร สี่สิบสองเปอร์เซ็นต์ แล้วก็เรียกรถ",
                  "Loyalty was very high, four point two six out of five. The top items were coming back to use it again, at four point four three, and recommending it to others, at four point two seven. The main reason people used the apps was convenience, thirty-five percent, then discounts and ease of use. The most-used service was food delivery, forty-two percent, then rides.",
                  "ติดใจแค่ไหน", "How loyal",
                  "ภักดี 4.26 จาก 5 · กลับมาใช้อีก 4.43 · แนะนำคนอื่น 4.27 · เหตุผลหลัก สะดวก 35%",
                  "Loyalty 4.26 of 5 · reuse 4.43 · recommend 4.27 · convenience first, 35%",
                  "ลูกศรกระดาษวนเป็นวงกลมหนึ่งอันวางแบน — กลับมาใช้ซ้ำ",
                  "ONE flat paper circular arrow, a ring with a single arrowhead, lying on the surface. One object, nothing else."),
            scene("finding", 16,
                  "พอให้สามเรื่องแข่งกันอธิบายความภักดี คุณภาพการให้บริการชนะขาด ค่าน้ำหนักจุดสี่เก้า ส่วนประสมทางการตลาดอย่างราคาและโปรโมชัน ตามมาห่างมากที่จุดหนึ่งสาม ด้านบริการที่คนพอใจสูงสุดคือความมั่นใจว่าใช้แล้วปลอดภัย เห็นราคาก่อนใช้ และบริการรวดเร็วตรงเวลา ส่วนที่คะแนนต่ำสุดคือบุคลิกและการแต่งกายของพนักงาน กับจำนวนพนักงานที่มีให้บริการ",
                  "When the three were set against each other, service quality won by a wide margin, with a weight of point four nine. The marketing mix, prices and promotions, trailed far behind at point one three. On service, people were most satisfied with feeling safe using it, seeing the price before ordering, and speed and punctuality. The lowest marks went to the appearance and manners of staff, and to whether there were enough of them.",
                  "อะไรทำให้ภักดี", "What drives loyalty",
                  "คุณภาพบริการ .49 · ราคาและโปรโมชัน .13 · พอใจสุด ปลอดภัย เห็นราคาก่อน ตรงเวลา · ต่ำสุด พนักงาน",
                  "Service quality .49 · price/promotions .13 · happiest: safety, price shown, on time · lowest: staff",
                  "แท่งกระดาษสองแท่งสูงต่างกันมากตั้งข้างกัน — บริการนำห่าง",
                  "TWO folded paper bars standing side by side, one much taller than the other. Two objects, nothing else."),
            scene("finding", 15,
                  "แล้วโฆษณาล่ะ คนเห็นข้อมูลข่าวสารของแอปในระดับปานกลาง มากที่สุดจากตัวแอปเอง กับเพจเฟซบุ๊ก แต่การเห็นบ่อยแค่ไหน อธิบายความภักดีไม่ได้เลย ค่าน้ำหนักจุดศูนย์สี่ ซึ่งเท่ากับไม่มีผล ทั้งที่ถ้าดูแยกเดี่ยว มันไปด้วยกันกับความภักดีอยู่ สามเรื่องรวมกันอธิบายความภักดีได้ราวสามสิบหกเปอร์เซ็นต์ ที่เหลือมาจากสิ่งที่งานนี้ไม่ได้วัด",
                  "And advertising? People saw information about the apps at a moderate level, mostly from the app itself and its Facebook page. But how often they saw it explained nothing about loyalty: a weight of point zero four, which amounts to no effect, even though on its own it did move together with loyalty. The three factors together explained about thirty-six percent of loyalty; the rest comes from things this study did not measure.",
                  "แล้วโฆษณาล่ะ", "And advertising?",
                  "เห็นข้อมูลบ่อยแค่ไหน อธิบายความภักดีไม่ได้ (.04) · 3 เรื่องรวมกัน อธิบายได้ 36%",
                  "Exposure explains nothing (.04) · the three together explain 36%",
                  "ป้ายโฆษณากระดาษว่างเปล่าหนึ่งป้ายบนเสาบางสองต้น — โฆษณาที่ไม่ได้ซื้อใจ",
                  "ONE small blank rectangular paper billboard standing on TWO thin paper posts. One object, nothing else."),
            scene("lesson", 22,
                  "บทเรียนสำหรับคนทำการตลาดแพลตฟอร์มก็คือ งบที่ทุ่มให้คนเห็นแบรนด์บ่อยขึ้น ไม่ได้ซื้อความภักดีกลับมา สิ่งที่ซื้อได้คือประสบการณ์ตอนใช้บริการจริง ความน่าเชื่อถือ ความปลอดภัย ราคาที่เห็นก่อน และพนักงานที่มีพอให้บริการ ส่วนลดกับโปรโมชันมีผลอยู่บ้าง แต่เป็นตัวรอง ถ้าต้องเลือกว่าจะลงทุนตรงไหน ผลนี้ชี้ไปที่ตัวบริการ ไม่ใช่ที่ป้ายโฆษณา",
                  "The lesson for anyone marketing a platform is that money spent on being seen more often does not buy loyalty back. What does is the experience of the service itself: reliability, safety, a price shown up front, and enough staff to serve. Discounts and promotions do count, but as the supporting act. If you have to choose where to invest, this result points at the service, not the billboard.",
                  "บทเรียน", "The lesson",
                  "ลงทุนที่ตัวบริการ · เชื่อถือได้ ปลอดภัย เห็นราคาก่อน พนักงานพอ · โปรโมชันเป็นตัวรอง",
                  "Invest in the service · reliable, safe, price up front, enough staff · promotions are the supporting act",
                  "กระดิ่งเรียกบริการกระดาษพับหนึ่งอัน มีปุ่มกลมด้านบน — ตัวบริการ",
                  "ONE small folded paper service bell, a dome with ONE small round paper button on top. One object, nothing else."),
            caveat("ข้อควรระวัง คนตอบสี่ร้อยคนอยู่ในกรุงเทพและไม่ได้สุ่มจากประชากรทั้งหมด เก็บข้อมูลเดือนตุลาคมสองพันห้าร้อยหกสิบสาม ช่วงโควิดที่คนสั่งอาหารออนไลน์ผิดจากปกติ และงานนี้ดูแค่สองแอป ผลจึงอาจไม่เหมือนกันกับแอปอื่นหรือช่วงเวลาอื่น",
                   "One caution: the four hundred people surveyed were in Bangkok and were not a random sample. The data was collected in October twenty twenty, during the pandemic, when online food ordering was far from normal. And the study looked at two apps only, so the result may not hold for other apps or other times.",
                   "กรุงเทพ ไม่ได้สุ่ม · ตุลาคม 2563 ช่วงโควิด · แค่ 2 แอป",
                   "Bangkok, not random · October 2020, mid-pandemic · only two apps"),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "horror", "batch": 6,
        "slug": "horror-storytelling-engagement",
        "name_th": "แฟนรายการเล่าเรื่องผีกับการมีส่วนร่วม",
        "name_en": "Horror-storytelling fans and engagement",
        "label": {"th": "งานวิจัย · การตลาดคอนเทนต์", "en": "Research · Content marketing"},
        "scenes": [
            scene("hook", 9,
                  "แฟนรายการเล่าเรื่องผีเชื่อใจรายการมาก และพร้อมบอกต่อ … แต่พอถึงเรื่องควักเงินสนับสนุน ตัวเลขร่วงลงแทบถึงพื้น",
                  "Fans of horror storytelling shows trust them deeply and happily pass them on … but when it comes to paying to support them, the numbers drop almost to the floor.",
                  "งานวิจัย · การตลาดคอนเทนต์", "Research · Content marketing",
                  "เชื่อใจสูง บอกต่อได้ แต่แทบไม่ควักเงิน",
                  "High trust, will share, almost never pay",
                  "ภาพประจำบทความ (มีแล้ว): ชามใหญ่เต็มปรี่ต่อด้วยด้ายบางไปยังชามจิ๋วที่มีชิ้นเดียว", None, image="existing"),
            scene("method", 17,
                  "ทีมวิจัยส่งแบบสอบถามออนไลน์ถึงคนอายุสิบแปดปีขึ้นไปที่ติดตามหรือเคยติดตามรายการเล่าเรื่องสยองขวัญ ได้มาสี่ร้อยคน ส่วนใหญ่เป็นผู้ชาย และอายุยี่สิบหกถึงสามสิบห้าปี รายการที่คนติดตามมากที่สุดคือเดอะโกสต์เรดิโอ กับอังคารคลุมโปง แบบสอบถามวัดสามอย่างที่รายการสร้างกับแฟน คือความเชื่อใจ ความผูกพัน และการสื่อสารสองทาง แล้วเทียบกับสิ่งที่แฟนทำจริง ทั้งแบบไม่เสียเงิน และแบบเสียเงิน " + STUDENT_TH,
                  "The research team sent an online questionnaire to people aged eighteen and over who follow or have followed horror storytelling shows, and got four hundred answers, mostly men aged twenty-six to thirty-five. The shows they followed most were The Ghost Radio and Angkhan Khlum Pong. The questionnaire measured three things a show builds with its fans, trust, attachment and two-way communication, and set them against what fans actually do, both the free things and the things that cost money. " + STUDENT_EN,
                  "ทำอะไร", "What was done",
                  "ผู้ติดตาม 400 คน · ชาย 61% · วัด 3 อย่าง เชื่อใจ ผูกพัน สื่อสาร · เทียบกับสิ่งที่ทำจริง",
                  "400 followers · 61% men · three measures: trust, attachment, communication · against what fans actually do",
                  "ไมโครโฟนกระดาษพับหนึ่งอันตั้งอยู่ — รายการเล่าเรื่อง",
                  "ONE small folded paper microphone standing upright on a round paper base. One object, nothing else."),
            scene("finding", 15,
                  "ความคิดเห็นต่อรายการโดยรวมอยู่ระดับปานกลาง สามจุดสามหก แต่ด้านความเชื่อใจสูงที่สุด สามจุดห้าหก ข้อที่แฟนให้คะแนนสูงสุดคือ เชื่อว่ารายการให้ข้อมูลที่เป็นความจริงและน่าเชื่อถือ สามจุดแปดหนึ่ง และมีแนวโน้มจะแนะนำรายการให้เพื่อนหรือครอบครัว สามจุดห้าหนึ่ง",
                  "Opinion of the shows overall was moderate, three point three six, but trust was the highest part, at three point five six. The single item fans rated highest was believing the show gives truthful and credible information, at three point eight one, followed by being likely to recommend it to friends or family, at three point five one.",
                  "เชื่อใจแค่ไหน", "How much trust",
                  "ความเชื่อใจ 3.56 สูงสุด · เชื่อว่าให้ข้อมูลจริง 3.81 · จะแนะนำเพื่อน 3.51",
                  "Trust 3.56, the highest · believe it tells the truth 3.81 · would recommend 3.51",
                  "โล่กระดาษพับหนึ่งอันตั้งอยู่ — ความเชื่อใจ",
                  "ONE folded paper shield shape standing upright on the surface. One object, nothing else."),
            scene("finding", 16,
                  "แต่สิ่งที่แฟนทำจริงอยู่ระดับต่ำ สองจุดสี่ห้า เรื่องที่ไม่เสียเงินทำกันมาก คอมเมนต์ใต้คลิปหรือในไลฟ์ สามจุดยี่สิบแปด แชร์คลิป สามจุดยี่สิบห้า พอเป็นเรื่องที่ต้องจ่าย สูงสุดคือเคยซื้อตั๋วหนังที่สร้างจากเรื่องในรายการ สามจุดยี่สิบหก ส่วนการโดเนทเงินได้แค่หนึ่งจุดเจ็ดห้า และการไปทริปกับรายการ หนึ่งจุดสี่หนึ่ง ต่ำที่สุด",
                  "But what fans actually do sits low, at two point four five. The free things are common: commenting under clips or during live streams, three point two eight, and sharing clips, three point two five. Once money is involved, the highest is having bought a ticket to a film made from a story on the show, three point two six. Donating money scores only one point seven five, and joining a trip with the show one point four one, the lowest of all.",
                  "ทำอะไรจริง", "What fans actually do",
                  "คอมเมนต์ 3.28 · แชร์ 3.25 · ซื้อตั๋วหนัง 3.26 · โดเนท 1.75 · ไปทริป 1.41",
                  "Comment 3.28 · share 3.25 · film ticket 3.26 · donate 1.75 · trip 1.41",
                  "ลูกโป่งคำพูดกระดาษหนึ่งอัน กับกระเป๋าสตางค์กระดาษพับปิดสนิทหนึ่งใบ — คอมเมนต์ได้ แต่กระเป๋าปิด",
                  "ONE flat paper speech bubble and ONE small closed folded paper wallet lying side by side. Two objects, nothing else."),
            scene("finding", 15,
                  "ความคิดเห็นที่ดีกับสิ่งที่ทำจริง ไปด้วยกันก็จริง แต่น้อยมาก ค่าความสัมพันธ์แค่จุดหนึ่งเจ็ด ชอบรายการมากขึ้นจึงแทบไม่บอกว่าจะมีส่วนร่วมมากขึ้น กลุ่มอายุสี่สิบหกปีขึ้นไปมองรายการเป็นบวกกว่ากลุ่มอายุสิบแปดถึงสามสิบห้า ส่วนคนที่มีส่วนร่วมมากกว่ากลุ่มอื่นคือข้าราชการและพนักงานรัฐวิสาหกิจ กับคนรายได้หนึ่งหมื่นถึงสามหมื่นบาท",
                  "Good opinion and real action do go together, but only just: the link is point one seven. Liking a show more barely says anything about taking part more. People aged forty-six and over saw the shows more positively than the eighteen-to-thirty-five group. And the people who took part most were civil servants and state enterprise staff, and those earning ten to thirty thousand baht a month.",
                  "ช่องว่างระหว่างใจกับมือ", "The gap",
                  "ชอบมากขึ้น ≠ ทำมากขึ้น (r = .17) · 46 ปีขึ้นไป มองบวกกว่า · ข้าราชการ รายได้ 1–3 หมื่น มีส่วนร่วมมากกว่า",
                  "Liking more ≠ doing more (r = .17) · most positive: 46+ · most active: civil servants on 10–30k baht",
                  "ซุ้มโค้งกระดาษสองครึ่งที่ไม่บรรจบกัน เว้นช่องกลาง — ช่องว่างระหว่างใจกับมือ",
                  "TWO folded paper arch halves standing on the surface facing each other with a clear gap in the middle where they do not meet. Two objects, nothing else."),
            scene("lesson", 22,
                  "บทเรียนสำหรับคนทำคอนเทนต์ก็คือ ความเชื่อใจกับการบอกต่อ ไม่ได้แปลงเป็นเงินสนับสนุนโดยอัตโนมัติ งานนี้ใส่ตัวเลขให้ช่องว่างที่คนทำรายการเจอกันบ่อย แฟนเชื่อใจ แฟนแชร์ แต่กระเป๋ายังปิด ทางที่ผลชี้คือออกแบบเป็นขั้นบันได จากสิ่งที่แฟนทำอยู่แล้วโดยไม่เสียเงิน อย่างคอมเมนต์และแชร์ ไต่ไปสู่การสนับสนุนที่จับต้องได้ทีละขั้น อย่างตั๋วหนังที่แฟนยอมจ่ายอยู่แล้ว แทนที่จะกระโดดไปขอโดเนทตั้งแต่แรก",
                  "The lesson for anyone making content is that trust and word of mouth do not turn into paid support on their own. This study puts numbers on a gap show-makers keep running into: fans trust, fans share, but the wallet stays shut. What the results point to is a ladder. Start from what fans already do for free, commenting and sharing, and climb one step at a time towards support they can hold, like the film tickets they already pay for, instead of jumping straight to asking for donations.",
                  "บทเรียน", "The lesson",
                  "เชื่อใจ ≠ จ่าย · เป็นขั้นบันได คอมเมนต์ แชร์ ตั๋ว แล้วค่อยสนับสนุน · ไม่กระโดดไปขอโดเนท",
                  "Trust ≠ paying · ladder: comment, share, ticket, then support · no jump to donations",
                  "บันไดกระดาษแบนหนึ่งอันมีสี่ขั้นวางราบ — ขั้นบันไดของการมีส่วนร่วม",
                  "ONE flat paper ladder with four rungs lying on the surface. One object, nothing else."),
            caveat("ข้อควรระวัง ทีมวิจัยระบุเองสองข้อ พฤติกรรมบางอย่างวัดจากคำตอบในแบบสอบถาม อาจต่างจากที่ทำจริง และคนตอบสี่ร้อยคนยังเล็กเมื่อเทียบกับคนที่ตามรายการแบบนี้ทั้งหมด ผลจึงยังไม่ครอบคลุมทุกคน และชื่อรายการที่เอ่ยเป็นขอบเขตของงาน ไม่ใช่การประเมินรายการ",
                   "One caution, stated by the authors themselves: some behaviour was measured from questionnaire answers and may differ from what people really do, and four hundred is still small against everyone who follows shows like these, so the result does not yet cover them all. The show names are the scope of the study, not a judgement of the shows.",
                   "วัดจากคำตอบ ไม่ใช่การกระทำจริง · 400 คน ยังเล็ก · ชื่อรายการเป็นขอบเขต ไม่ใช่การประเมิน",
                   "Answers, not observed acts · 400 is still small · show names are scope, not verdicts"),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "maewong", "batch": 6,
        "slug": "nodam-maewong-framing",
        "name_th": "แคมเปญค้านเขื่อนแม่วงก์บนโซเชียลมีเดีย",
        "name_en": "The Mae Wong dam campaign on social media",
        "label": {"th": "งานวิจัย · การสื่อสารรณรงค์", "en": "Research · Campaign communication"},
        "scenes": [
            scene("hook", 9,
                  "ปีสองพันห้าร้อยห้าสิบหก ชายคนหนึ่งเดินเท้าสามร้อยแปดสิบแปดกิโลเมตร เพื่อค้านเขื่อน … ทีมวิจัยอ่านข้อความบนทวิตเตอร์ตลอดเส้นทาง แล้วพบว่าคนรณรงค์ สื่อ และประชาชน เล่าเรื่องเดียวกันคนละแบบ แต่แคมเปญก็ยังสำเร็จ",
                  "In twenty thirteen, one man walked three hundred and eighty-eight kilometres to oppose a dam … The research team read the Twitter messages along the way, and found the campaigners, the news and the public each told the story differently. The campaign worked anyway.",
                  "งานวิจัย · การสื่อสารรณรงค์", "Research · Campaign communication",
                  "สามฝ่ายเล่าคนละกรอบ แต่แคมเปญสำเร็จ",
                  "Three sides, three frames, and the campaign still worked",
                  "ภาพประจำบทความ (มีแล้ว): วัตถุสามชิ้นคนละรูปทรงทอดเงารวมเป็นเงาเดียว", None, image="existing"),
            scene("method", 17,
                  "ทีมวิจัยวิเคราะห์กรอบการเล่าเรื่องจากข้อความบนทวิตเตอร์ของมูลนิธิสืบนาคะเสถียร และของนายศศิน เฉลิมลาภ เลขาธิการมูลนิธิ ผู้เดินเท้าจากพื้นที่สร้างเขื่อนแม่วงก์มาถึงกรุงเทพในเดือนกันยายน พร้อมข้อความที่ติดแฮชแท็กแม่วงก์ทั้งไทยและอังกฤษ แบ่งเป็นสามช่วง ก่อนเดิน ระหว่างเดิน และหลังเดิน แล้วเทียบกรอบของผู้รณรงค์ กับกรอบที่ปรากฏในข่าว และในข้อความของคนทั่วไป",
                  "The research team analysed the framing of Twitter messages from the Seub Nakhasathien Foundation and from its secretary, Sasin Chalermlarp, who walked from the Mae Wong dam site to Bangkok that September, together with every message carrying the Mae Wong hashtag in Thai and English, split into before, during and after the walk. Then it compared the campaigners' frame with the frames that appeared in the news and in the public's own messages.",
                  "ทำอะไร", "What was done",
                  "ทวิตเตอร์ของมูลนิธิ ผู้เดิน และแฮชแท็กแม่วงก์ · 3 ช่วง ก่อน ระหว่าง หลัง · เทียบ 3 ฝ่าย",
                  "Twitter: Foundation, walker, Mae Wong hashtag · before, during, after · 3 sides compared",
                  "รอยเท้ากระดาษสองรอยเรียงต่อกัน — การเดินเท้า",
                  "exactly TWO flat paper footprint shapes lying one ahead of the other as if walking. Two objects, nothing else."),
            scene("finding", 16,
                  "สามฝ่ายเล่าคนละกรอบ ประชาชนพูดถึงตัวเขื่อน ด้วยข้อมูลวิทยาศาสตร์และเรื่องอนุรักษ์ป่า ผู้รณรงค์เล่าเรื่องการเดินและเรื่องของตัวผู้เดิน ด้วยถ้อยคำเชิงอารมณ์ ส่วนข่าวโยงไปที่นักการเมืองและนโยบายพัฒนาประเทศ ทั้งที่เรื่องเดียวกัน แต่แต่ละฝ่ายมองเห็นคนละมุม",
                  "The three sides framed it three ways. The public talked about the dam itself, in scientific terms and about protecting the forest. The campaigners told the story of the walk and of the man walking, in emotional language. The news tied it to politicians and to national development policy. One issue, three different angles.",
                  "สามกรอบ", "Three frames",
                  "ประชาชน: ตัวเขื่อน ป่า วิทยาศาสตร์ · ผู้รณรงค์: การเดิน ตัวบุคคล อารมณ์ · ข่าว: การเมือง นโยบาย",
                  "Public: dam, forest, science · campaigners: walk, walker, emotion · news: politics and policy",
                  "ลูกโป่งคำพูดกระดาษสามอันคนละรูปทรงเรียงกัน ว่างเปล่าทั้งหมด — สามฝ่าย สามแบบ",
                  "exactly THREE flat paper speech bubbles of three different shapes lying in a row, all empty. Three objects, nothing else."),
            scene("finding", 16,
                  "ผู้รณรงค์ใช้ความเห็นใจและความอบอุ่นโน้มน้าว แต่สิ่งที่คนรีทวีต กดถูกใจ และแชร์จริง กลับเป็นข้อความที่มีข้อเท็จจริงและหลักฐานว่าทำไมต้องยกเลิกเขื่อน ข้อความที่ถูกรีทวีตสูงสุดของมูลนิธิได้เจ็ดร้อยห้าสิบเอ็ดครั้ง ว่าถ้าเขื่อนนี้สร้างได้ จะมีเขื่อนในป่าอนุรักษ์ตามมาอีก ส่วนของนายศศินได้หกร้อยห้าสิบเก้าครั้ง เป็นข้อความหลังสถานีโทรทัศน์แห่งหนึ่งระงับสารคดีเรื่องนี้ แล้วทีมงานเอาไปลงยูทูบแทน",
                  "The campaigners leaned on sympathy and warmth, but what people actually retweeted, liked and shared were the messages carrying facts and evidence for why the dam should be cancelled. The Foundation's most-shared message, seven hundred and fifty-one retweets, warned that if this dam went ahead, more dams in protected forest would follow. Sasin's, at six hundred and fifty-nine, came after a television channel pulled the documentary about the walk and the team put it on YouTube instead.",
                  "คนส่งต่ออะไร", "What people passed on",
                  "คนแชร์ข้อเท็จจริง ไม่ใช่อารมณ์ · รีทวีตสูงสุด 751 ครั้ง และ 659 ครั้ง · สารคดีถูกระงับ → ยูทูบ",
                  "People shared facts, not feelings · top retweets 751 and 659 · documentary pulled → YouTube",
                  "แผ่นเอกสารกระดาษหนึ่งแผ่นใหญ่ กับหัวใจกระดาษเล็กหนึ่งดวงข้างกัน — ข้อเท็จจริงใหญ่กว่าอารมณ์",
                  "ONE flat rectangular paper sheet and ONE much smaller flat paper heart lying beside it. Two objects, nothing else."),
            scene("finding", 15,
                  "แรงกดดันจากโลกออนไลน์ออกมาถึงโลกจริง รายชื่อค้านเขื่อนบนเว็บล่ารายชื่อขึ้นถึงหนึ่งแสนชื่อ สูงที่สุดของคำร้องในไทยตอนนั้น ที่ส่วนใหญ่ไปถึงแค่หลักหมื่น วันสุดท้ายมีคนมารวมตัวกลางกรุงเทพ และรัฐมนตรีกระทรวงทรัพยากรธรรมชาติและสิ่งแวดล้อมส่งเลขานุการมารับข้อเรียกร้อง พร้อมระบุว่าจะตรวจสอบรายงานผลกระทบอย่างรอบคอบ ไม่เร่งรัดการก่อสร้าง",
                  "Pressure online turned into pressure in the street. The anti-dam petition reached one hundred thousand signatures, the most any Thai petition had drawn at the time, when most reached the tens of thousands. On the final day people gathered in central Bangkok, and the Minister of Natural Resources and Environment sent his secretary to receive the demands, stating the ministry would review the impact report carefully and would not rush to build.",
                  "ผลที่ตามมา", "What followed",
                  "ลงชื่อค้าน 100,000 ชื่อ สูงสุดของไทยตอนนั้น · รัฐมนตรีส่งเลขานุการ รับข้อเรียกร้อง · ไม่เร่งสร้าง",
                  "100,000 signatures, a Thai record then · the minister's secretary received the demands · no rush to build",
                  "ปากกากระดาษหนึ่งด้ามวางพาดบนแผ่นกระดาษหนึ่งแผ่น — การลงชื่อ",
                  "ONE small folded paper pen lying diagonally across ONE flat blank paper sheet. Two objects, nothing else."),
            scene("lesson", 22,
                  "บทเรียนสำหรับคนทำแคมเปญสิ่งแวดล้อมก็คือ กรอบที่ไม่ตรงกันไม่ได้แปลว่าแคมเปญล้มเหลว และเมื่อประชาชนเลือกส่งต่อข้อเท็จจริงมากกว่าความรู้สึก แคมเปญจึงควรเตรียมทั้งสองอย่างไว้คู่กัน อารมณ์ดึงคนเข้ามา ข้อเท็จจริงทำให้คนส่งต่อ อีกบทเรียนคือ สารคดีที่ถูกระงับจากโทรทัศน์ พอย้ายไปยูทูบกลับได้คนดูมากกว่าเดิม โซเชียลมีเดียจึงเป็นทางเลี่ยงการปิดกั้นได้จริง ถ้ามีคนที่ทุ่มเทและวางแผนการสื่อสารไว้ครบ",
                  "The lesson for anyone running an environmental campaign is that mismatched frames do not mean a failed campaign. And since the public chose to pass on facts rather than feelings, a campaign should prepare both: emotion draws people in, facts make them share. The other lesson is that when the documentary was kept off television, moving it to YouTube reached more people than the broadcast would have. Social media really can route around a block, when there is someone committed behind it and a communication plan in place.",
                  "บทเรียน", "The lesson",
                  "กรอบไม่ตรงกัน ≠ ล้มเหลว · อารมณ์ดึงคนเข้ามา ข้อเท็จจริงทำให้ส่งต่อ · ถูกปิดกั้น → ย้ายช่องทาง",
                  "Mismatched frames ≠ failure · emotion draws in, facts get shared · blocked? move channel",
                  "แถบกระดาษสองเส้นถักเข้าด้วยกันหลวมๆ วางราบ — อารมณ์กับข้อเท็จจริงไปด้วยกัน",
                  "TWO flat paper strips loosely braided together lying on the surface. Two objects, nothing else."),
            caveat("ข้อควรระวัง เป็นกรณีศึกษาเดียวจากข้อมูลปีสองพันห้าร้อยห้าสิบหก วิเคราะห์จากทวิตเตอร์เป็นหลัก และตัดสินว่าสำเร็จจากผลเชิงนโยบายที่ตามมา ไม่ได้วัดว่าคนรับสารเปลี่ยนความคิดจริงหรือไม่ ชื่อบุคคลและมูลนิธิที่เอ่ยเป็นผู้จัดแคมเปญที่ศึกษา ไม่ใช่เป้าของข้อวิจารณ์",
                   "One caution: this is a single case from twenty thirteen, read mainly through Twitter, and it judges success by the policy response that followed, not by measuring whether anyone changed their mind. The person and foundation named ran the campaign under study; they are not the object of any criticism.",
                   "กรณีเดียว ปี 2556 · ทวิตเตอร์เป็นหลัก · วัดผลนโยบาย ไม่ได้วัดใจคน · ชื่อที่เอ่ยคือผู้จัดแคมเปญ",
                   "One case, 2013 · mainly Twitter · policy outcome, not minds changed · names are the campaigners"),
            closing(),
        ],
    },
]
