"""สตอรี่บอร์ดชุดที่ 4 — 5 เรื่อง × ไทย/อังกฤษ (5 ก.ย. 2569) — storyboard.py นำเข้าไฟล์นี้แล้วต่อท้าย CLIPS/PALETTE

กติกาเดียวกับชุดที่ 2–3 (ดูหัวไฟล์ storyboard_batch2.py · บทพากย์เป็นภาษาพูด ผ่าน check_narration.py ก่อนอัด) · ข้อเพิ่มของชุดนี้:
  · คลิปสื่อจีนไม่เอ่ยชื่อสำนักข่าวทั้งสี่ (บทสรุปบนเว็บก็ไม่เอ่ย เพราะข้อค้นพบเรื่องไม่อ้างแหล่งผูกกับสำนักข่าวรายแห่ง)
  · คลิปจุดยืนแบรนด์ไม่เอ่ยชื่อแบรนด์ที่ใช้เป็นกรณีศึกษา ("แบรนด์อสังหาริมทรัพย์รายหนึ่ง") — ไม่ใช่การวิจารณ์ แต่ผลบวกที่เอ่ยชื่อจะอ่านเป็นการรับรองได้
  · คลิปห้องเรียนออนไลน์ไม่เอ่ยชื่อแพลตฟอร์ม (ควิซแข่งขัน · ระบบเรียนออนไลน์ · เว็บนำเสนอ) และบอกในข้อควรระวังว่าผู้วิจัยหลักเป็นผู้สอนเอง
  · คลิปจัดการความรู้เอ่ย "กรมควบคุมโรค" ได้ เพราะเป็นขอบเขตของงาน ไม่ใช่เป้าของข้อวิจารณ์ (ข้อยกเว้นของกติกาข้อ 5 แบบเดียวกับชื่อยูทูบเบอร์ใน #45)
  · เลือกจากบทสรุปที่เหลือซึ่งเป็นงานเชิงประจักษ์และทะเบียนมี citation ครบ 15 เรื่อง — ตัดงานที่บทสรุปไม่มีตัวเลขพอเล่า 8 ฉาก (คริปโต Reddit · บิตคอยน์) งานที่แตะเรื่องอ่อนไหวสูง (แอปหาคู่ × เอชไอวี/สารเสพติด · สื่อรัสเซีย · โฆษณาเหยียดสีผิว) และงานที่ซ้ำแนวกับชุดก่อน (อินฟลูเอนเซอร์เกม ซ้ำวีทูปเบอร์)
"""
from storyboard_batch2 import CLOSING2, ASTERISK

CLOSING4 = CLOSING2

# คู่สีอ่านจากภาพประจำบทความของแต่ละเรื่อง (นับพิกเซลที่อิ่มสี frames/b4-illustrations.png) เพื่อให้ภาพใหม่กลมกลืนกับภาพ hook
PALETTE4 = {
    "cnmedia": {"object": "deep rose pink", "shadow": "olive green", "obj_hex": "#D04878", "sh_hex": "#78784A",
                "shadow_style": "clean flat-edged shadows to the lower right rendered as solid olive-green shapes, like cut paper rather than soft photographic shadows"},
    "fansub": {"object": "deep wine magenta", "shadow": "soft grey-mauve", "obj_hex": "#8E1A4A", "sh_hex": "#B9A3AE",
               "shadow_style": "soft grey-mauve shadows to the lower right, as in a real studio photograph of paper on a table"},
    "stance": {"object": "sage green", "shadow": "deep magenta", "obj_hex": "#7E9450", "sh_hex": "#8E1A4A",
               "shadow_style": "clean flat-edged shadows to the lower right rendered as solid deep-magenta shapes, like cut paper rather than soft photographic shadows"},
    "cogload": {"object": "deep teal", "shadow": "warm amber", "obj_hex": "#2E6E7A", "sh_hex": "#D9A84A",
                "shadow_style": "clean flat-edged shadows to the lower right rendered as solid warm-amber shapes, like cut paper rather than soft photographic shadows"},
    "ksharing": {"object": "soft sky blue", "shadow": "rose pink", "obj_hex": "#9EC1DC", "sh_hex": "#C24A7A",
                 "shadow_style": "clean flat-edged shadows to the lower right rendered as solid rose-pink shapes, like cut paper rather than soft photographic shadows"},
}


def closing():
    return {"role": "closing", "secs": (14, 14), "image": "logo", "narr": CLOSING4, "label": None, "text": None,
            "visual_th": "การ์ดปิดประจำชุด + ชื่อผู้เขียนทุกคน (ไม่ต้องเจนภาพ)", "subject": None}


def caveat(narr_th, narr_en, text_th, text_en, secs=(10, 10)):
    return {"role": "caveat", "secs": secs, "image": "new", "narr": {"th": narr_th, "en": narr_en},
            "label": {"th": "ข้อควรระวัง", "en": "One caution"}, "text": {"th": text_th, "en": text_en},
            "visual_th": "ดอกจันกระดาษพับหนึ่งดอก — สัญลักษณ์ประจำฉากข้อควรระวัง (คู่สีของคลิปนี้)", "subject": ASTERISK}


def scene(role, secs, narr_th, narr_en, label_th, label_en, text_th, text_en, visual_th, subject, image="new"):
    return {"role": role, "secs": (secs, secs), "image": image, "narr": {"th": narr_th, "en": narr_en},
            "label": {"th": label_th, "en": label_en}, "text": {"th": text_th, "en": text_en},
            "visual_th": visual_th, "subject": subject}


CLIPS4 = [
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "cnmedia", "batch": 4,
        "slug": "chinese-media-thailand-cannabis",
        "name_th": "สื่อจีนกับภาพไทยหลังปลดล็อกกัญชา",
        "name_en": "Chinese media and Thailand after cannabis legalisation",
        "label": {"th": "งานวิจัย · ภาพลักษณ์ประเทศ", "en": "Research · Nation image"},
        "scenes": [
            scene("hook", 9,
                  "หลังไทยปลดล็อกกัญชา สื่อภาษาจีนรายงานเรื่องไทยแบบกลาง ไม่บวกไม่ลบ … แต่คนอ่านกลับสรุปกันเองว่า ไม่ไปแล้ว",
                  "After Thailand legalised cannabis, Chinese-language media reported it in a neutral tone … yet readers came away saying, I'm not going.",
                  "งานวิจัย · ภาพลักษณ์ประเทศ", "Research · Nation image",
                  "ข่าวรายงานกลาง แต่ช่องความเห็นไม่กลาง และปลายทางคือ ไม่ไปแล้ว",
                  "The coverage was neutral. The comment threads were not, and they ended at: I'm not going",
                  "ภาพประจำบทความ (มีแล้ว): ริบบิ้นเรียบลอดช่องแคบแล้วออกมายับและโค้งลง — ข่าวที่กลางออกมาเป็นความรู้สึกที่ไม่กลาง", None, image="existing"),
            scene("method", 17,
                  "ทีมวิจัยเก็บโพสต์บนเว่ยป๋อ หนึ่งร้อยยี่สิบแปดโพสต์ ตั้งแต่ปีสองพันห้าร้อยหกสิบสอง ถึงสองพันห้าร้อยหกสิบห้า จากสำนักข่าวภาษาจีนสี่แห่ง สามแห่งอยู่ในจีน อีกแห่งเป็นหนังสือพิมพ์ภาษาจีนในกรุงเทพ แล้วให้คนอ่านสามคนแยกกันจัดประเภทว่า แต่ละโพสต์เล่ามุมไหน น้ำเสียงเป็นอย่างไร และอ้างแหล่งข่าวจากที่ใด",
                  "The research team collected one hundred and twenty-eight posts on Weibo, from twenty nineteen to twenty twenty-two, by four Chinese-language outlets: three based in China and one Chinese-language newspaper in Bangkok. Three coders independently classified each post by the angle it took, its tone, and where it said its information came from.",
                  "ทำอะไร", "What was done",
                  "โพสต์บนเว่ยป๋อ 128 โพสต์ · สำนักข่าว 4 แห่ง · ปี 2562–2565 · คนจัดประเภท 3 คน",
                  "128 Weibo posts · four outlets · 2019–2022 · three coders",
                  "การ์ดกระดาษสี่ใบวางคลี่เป็นพัดหลวมๆ — สำนักข่าวสี่แห่ง",
                  "exactly FOUR flat paper rectangular cards of the same size lying in a loose fan, each slightly rotated from the last. Four objects, nothing else."),
            scene("finding", 18,
                  "น้ำเสียงของข่าวส่วนใหญ่เป็นกลาง คนอ่านทั้งสามคนจัดว่าเป็นข้อความกลาง ราวแปดสิบถึงเก้าสิบห้าเปอร์เซ็นต์ ส่วนที่ชวนให้มาเที่ยวมีไม่ถึงสามเปอร์เซ็นต์ มุมที่เล่ามากที่สุดคืออธิบายตัวนโยบาย กว่าครึ่ง รองลงมาคือข่าวเชิงลบเกี่ยวกับการปลดล็อก ราวหนึ่งในสาม ส่วนข่าวเชิงบวกมีไม่ถึงห้าเปอร์เซ็นต์ และโพสต์พุ่งสูงสุดในเดือนที่นโยบายมีผล",
                  "The tone was mostly neutral. All three coders put between eighty and ninety-five percent of the posts down as plain statements, and fewer than three percent encouraged anyone to visit. The most common angle was explaining the policy itself, more than half of the posts, then negative news about legalisation, about a third. Positive news was under five percent, and the posts peaked in the month the policy took effect.",
                  "น้ำเสียงและมุมข่าว", "Tone and angle",
                  "ข้อความกลาง 83–95% · อธิบายนโยบาย 55.5% · ข่าวลบ 36.7% · ข่าวบวก 4.7%",
                  "Neutral 83–95% · explaining the policy 55.5% · negative news 36.7% · positive 4.7%",
                  "หน้าปัดกระดาษกลมหนึ่งใบ เข็มกระดาษชี้ตรงขึ้นกลางหน้าปัด — น้ำเสียงที่อยู่ตรงกลาง",
                  "ONE flat paper circle like a dial, with ONE thin paper needle lying on it and pointing straight up to the top of the circle. Two objects, nothing else."),
            scene("finding", 16,
                  "แต่ช่องความเห็นไปคนละทางกับตัวข่าว ทีมวิจัยพบความเห็นกลุ่มใหญ่ที่บอกว่าไม่ไปไทยแล้ว ด้วยเหตุผลสามอย่าง กลัวเผลอกินอาหารที่มีกัญชาผสม ไม่มั่นใจว่าหลังปลดล็อกแล้วจะมีใครดูแล และมองว่าไทยทำตามชาติตะวันตก ข่าวที่กลาง ไม่ได้ทำให้คนอ่านรู้สึกกลางตาม",
                  "But the comment threads ran the other way. The team found a large cluster of comments saying they would not go to Thailand, for three reasons: they might eat food with cannabis in it without knowing, they did not trust that anyone would keep watch after legalisation, and they saw the policy as copying the West. Neutral coverage did not leave readers feeling neutral.",
                  "ความเห็นของคนอ่าน", "What readers said",
                  "ไม่ไปแล้ว · กลัวเผลอกินอาหารผสมกัญชา · ไม่มั่นใจการกำกับดูแล · มองว่าทำตามตะวันตก",
                  "Not going · afraid of eating cannabis by accident · no trust in oversight · seen as copying the West",
                  "กระเป๋าเดินทางกระดาษใบเล็กปิดสนิทตั้งอยู่ — ไม่ไปแล้ว",
                  "ONE small closed paper suitcase standing upright, with a small paper handle on top. One object, nothing else."),
            scene("finding", 17,
                  "และหนึ่งในสามของโพสต์ ไม่บอกเลยว่าเอาข้อมูลมาจากไหน ที่อ้างสื่อไทยมีราวหกสิบเปอร์เซ็นต์ ที่สื่อเรียบเรียงเองมีไม่ถึงสิบเปอร์เซ็นต์ ที่น่าสนใจคือ โพสต์ที่ห้ามปรามชัดที่สุด ไม่ใช่ความเห็นของสื่อ แต่เป็นการส่งต่อประกาศของสถานทูตจีนในไทย ที่ห้ามนำผลิตภัณฑ์กัญชากลับประเทศ",
                  "And a third of the posts gave no source at all. About sixty percent drew on Thai media, and under ten percent were the outlets' own reporting. Tellingly, the posts that discouraged travel most strongly were not editorial opinion. They were forwarded notices from the Chinese embassy in Thailand, telling citizens not to bring cannabis products home.",
                  "แหล่งที่มา", "Where it came from",
                  "ไม่ระบุแหล่ง 33.6% · อ้างสื่อไทย 58.6% · เรียบเรียงเอง 7.8% · โพสต์ที่ห้ามปรามชัดที่สุด คือประกาศสถานทูต",
                  "No source 33.6% · Thai media 58.6% · own reporting 7.8% · the strongest warnings were embassy notices",
                  "กระดาษสี่เหลี่ยมสามแผ่นเรียงกัน แผ่นที่สามเจาะรูกลมตรงกลาง — หนึ่งในสามที่ไม่มีแหล่ง",
                  "exactly THREE flat paper squares of the same size lying in a row; the third square has a round hole cut out of its centre. Three objects, nothing else."),
            scene("lesson", 24,
                  "บทเรียนสำหรับงานสื่อสารภาพลักษณ์ประเทศก็คือ การนับว่าข่าวเป็นกลางกี่เปอร์เซ็นต์ ไม่ได้บอกเลยว่าคนอ่านรู้สึกอย่างไร ความหมายถูกตัดสินกันในช่องความเห็น และข่าวที่กลาง แต่ไม่ตอบคำถามที่คนกังวลจริง เช่น กินอาหารข้างทางแล้วจะเจอกัญชาไหม กลับประเทศแล้วจะผิดกฎหมายไหม ก็เปิดช่องให้ความกลัวเข้ามาเติมแทน หน่วยงานด้านการท่องเที่ยวจึงต้องออกแบบสารที่ตอบคำถามระดับชีวิตประจำวันของนักท่องเที่ยว ไม่ใช่แค่ประกาศนโยบายให้ครบ",
                  "The lesson for anyone working on a country's image is that counting how much of the coverage is neutral tells you nothing about how it lands. Meaning gets settled in the comment thread. And coverage that stays neutral but leaves the reader's real worry unanswered, such as will I find cannabis in street food, or will I be in trouble when I fly home, leaves a gap that fear fills instead. Tourism communication has to answer questions at the level of a traveller's day, not just announce the policy in full.",
                  "บทเรียน", "The lesson",
                  "นับข่าวกลางกี่เปอร์เซ็นต์ ไม่บอกว่าคนรู้สึกอย่างไร · ความหมายถูกตัดสินในช่องความเห็น · ตอบคำถามระดับชีวิตประจำวัน",
                  "Counting neutral coverage says nothing about how it lands · meaning is settled in the comments · answer the traveller's everyday questions",
                  "ชามกระดาษใบเล็กกับเครื่องบินกระดาษพับวางคู่กัน — อาหารข้างทางกับเที่ยวบินกลับบ้าน",
                  "ONE small paper bowl and ONE small folded paper airplane lying side by side with a small gap between them. Two objects, nothing else."),
            caveat("ข้อควรระวัง ระบบเซนเซอร์ทำให้เก็บข้อมูลได้ไม่ครบ ทีมวิจัยจำกัดที่เว่ยป๋อแพลตฟอร์มเดียว และคำว่ากัญชาถูกจำกัด สื่อจึงเลี่ยงไปใช้คำพ้องเสียงหรืออิโมจิ ส่วนระบบชื่อจริงก็ทำให้คนเซนเซอร์ตัวเอง ความเห็นที่เห็นจึงอาจไม่ใช่ทั้งหมดที่คิด และงานนี้ไม่ได้วัดว่าคนเลิกมาเที่ยวจริงหรือไม่ คลิปนี้ไม่เอ่ยชื่อสำนักข่าวทั้งสี่",
                   "One caution: censorship left the data incomplete. The team had to stay on Weibo alone, and because the word for cannabis is restricted, outlets dodged it with homophones and emoji, so the search cannot have caught everything. Weibo's real-name rule also makes people censor themselves, so the comments may not show all they think. And the study did not measure whether anyone actually cancelled a trip. This clip names none of the four outlets.",
                   "เก็บได้ไม่ครบเพราะเซนเซอร์ · คนเซนเซอร์ตัวเอง · ไม่ได้วัดว่าเลิกมาจริงไหม · ไม่เอ่ยชื่อสำนักข่าว",
                   "Incomplete because of censorship · self-censored comments · trips not measured · no outlets named", secs=(12, 12)),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "fansub", "batch": 4,
        "slug": "fansub-viewers-sponsorship",
        "name_th": "ผู้สนับสนุนคอร์สที่แฟนคลับแปลซับ",
        "name_en": "Sponsoring fan-subtitled courses",
        "label": {"th": "งานวิจัย · การสนับสนุนเนื้อหา", "en": "Research · Content sponsorship"},
        "scenes": [
            scene("hook", 9,
                  "คอร์สเรียนที่แฟนคลับแปลซับให้ดูฟรี มีแบรนด์เป็นผู้สนับสนุน … คนดูจะมองว่าเป็นโฆษณายัดเยียด หรือรู้สึกดีกับแบรนด์ไปด้วย",
                  "Online courses that fan groups subtitle for free, with a brand as sponsor … do viewers see it as an ad forced on them, or do they warm to the brand as well?",
                  "งานวิจัย · การสนับสนุนเนื้อหา", "Research · Content sponsorship",
                  "คนดูที่ชอบคอร์ส ที่แฟนคลับแปลให้ฟรี รู้สึกดีกับผู้สนับสนุนไปด้วย และไม่ได้มองว่า เป็นโฆษณายัดเยียด",
                  "Viewers who value the courses fan groups subtitle for free warm to the sponsors too, and do not read it as an ad forced on them",
                  "ภาพประจำบทความ (มีแล้ว): แผ่นสีหนึ่งแตะขอบอีกแผ่น สีซึมข้ามไปติดขอบข้างเคียง — ความรู้สึกดีที่ส่งต่อ", None, image="existing"),
            scene("method", 16,
                  "ทีมวิจัยโพสต์แบบสอบถามบนเว็บบอร์ดของกลุ่มแฟนซับกลุ่มหนึ่ง ได้คนตอบสองร้อยสิบหกคน เป็นผู้หญิงหนึ่งร้อยสามสิบสองคน ครึ่งหนึ่งอายุสิบแปดถึงยี่สิบห้าปี ถามความรู้สึกสามเรื่อง คือรู้สึกอย่างไรกับตัวคอร์ส กับการที่มีผู้สนับสนุน และกับตัวแบรนด์ผู้สนับสนุนเอง แล้วดูว่าสามเรื่องนี้เกี่ยวกันไหม",
                  "The research team posted a survey on the forum of one fansub group and got two hundred and sixteen answers, one hundred and thirty-two of them from women, half aged eighteen to twenty-five. They asked about three feelings: how people felt about the courses, about the fact that they were sponsored, and about the sponsoring brands themselves. Then they looked at whether the three moved together.",
                  "ทำอะไร", "What was done",
                  "คนตอบ 216 คน · ผู้หญิง 132 คน · ถาม 3 เรื่อง · ตัวคอร์ส การมีผู้สนับสนุน ตัวแบรนด์",
                  "216 people · 132 women · three feelings · the course, the sponsorship, the brand",
                  "กระดาษสี่เหลี่ยมใหญ่หนึ่งแผ่นกับแถบกระดาษแคบวางใต้ขอบล่าง — จอกับซับไตเติล",
                  "ONE large flat paper rectangle lying on the table with ONE narrow paper strip lying just below its bottom edge, like a subtitle under a screen. Two objects, nothing else."),
            scene("finding", 13,
                  "คนดูให้คะแนนตัวคอร์สสูงที่สุด ว่ามีคุณค่า สี่จุดสามห้าจากห้า ดี สี่จุดสองแปด และเป็นประโยชน์ สี่จุดสองห้า และความรู้สึกทั้งสามเรื่อง เป็นบวกชัดเจน ไม่ใช่แค่เฉย",
                  "Viewers rated the courses themselves highest: valuable at four point three five out of five, good at four point two eight, and useful at four point two five. And all three feelings came out clearly positive, not just neutral.",
                  "ตัวคอร์ส", "The courses",
                  "มีคุณค่า 4.35 · ดี 4.28 · เป็นประโยชน์ 4.25 (จาก 5) · ทั้ง 3 เรื่องเป็นบวกชัด",
                  "Valuable 4.35 · good 4.28 · useful 4.25 (out of 5) · all three clearly positive",
                  "หนังสือกระดาษพับเปิดกางหนึ่งเล่มวางราบ — ตัวคอร์ส",
                  "ONE folded paper book lying open on the table with its two pages spread flat. One object, nothing else."),
            scene("finding", 15,
                  "คนดูไม่ได้มองว่าคอร์สถูกทำให้เป็นการค้าเกินไป และเห็นว่าการที่แบรนด์มาสนับสนุน มีเหตุผลรองรับ สามจุดเก้า เข้ากับเนื้อหา สามจุดแปดสี่ และมาด้วยความจริงใจ สี่จุดศูนย์หนึ่ง ข้อที่ได้คะแนนสูงคือ เข้ากัน กับ จริงใจ",
                  "Viewers did not think the courses had been made too commercial. They agreed the sponsorship made sense, at three point nine, fitted the content, at three point eight four, and was sincerely meant, at four point oh one. The items that scored highest were fit and sincerity.",
                  "การมีผู้สนับสนุน", "The sponsorship",
                  "ไม่ได้เป็นการค้าเกินไป · มีเหตุผล 3.90 · เข้ากับเนื้อหา 3.84 · จริงใจ 4.01",
                  "Not over-commercial · makes sense 3.90 · fits the content 3.84 · sincere 4.01",
                  "กระดาษสี่เหลี่ยมสองแผ่นขนาดเท่ากันวางชิดขอบต่อกันพอดี — เข้ากัน",
                  "exactly TWO flat paper squares of the same size lying edge to edge so they touch along one full side and form one neat rectangle. Two objects, nothing else."),
            scene("finding", 18,
                  "ความรู้สึกดีต่อตัวแบรนด์มีจริง แต่ต่ำกว่าความรู้สึกต่อตัวคอร์ส ภาพลักษณ์ดีขึ้น สามจุดเจ็ดแปด ชอบมากกว่าเดิม สามจุดหกเก้า และเมื่อดูว่าสามเรื่องนี้ไปด้วยกันแค่ไหน คำตอบคือไปด้วยกันในระดับปานกลาง ความชอบต่อคอร์สกับความชอบต่อแบรนด์ สัมพันธ์กันแค่จุดสามหก ความรู้สึกดี ส่งต่อได้ แต่ส่งได้ไม่เต็ม",
                  "Goodwill toward the brands was real, but lower than toward the courses: a better image at three point seven eight, liking them more than before at three point six nine. And when the team checked how far the three feelings moved together, the answer was moderately. Liking the course and liking the brand went together at only point three six. Goodwill does carry over, but not in full.",
                  "ส่งต่อได้แค่ไหน", "How far it carries",
                  "ภาพลักษณ์ดีขึ้น 3.78 · ชอบมากกว่าเดิม 3.69 · คอร์สกับแบรนด์สัมพันธ์กัน r = .36 · ส่งต่อได้ แต่ไม่เต็ม",
                  "Better image 3.78 · liked more 3.69 · course and brand r = .36 · carries over, but not in full",
                  "วงกลมกระดาษสองวงวางซ้อนกันราวหนึ่งในสาม — ส่งต่อได้บางส่วน",
                  "exactly TWO flat paper circles of the same size lying side by side and overlapping by about a third of their width. Two objects, nothing else."),
            scene("lesson", 22,
                  "บทเรียนสำหรับแบรนด์ที่คิดจะสนับสนุนเนื้อหาที่ชุมชนทำกันเองก็คือ ความรู้สึกดีส่งต่อจากเนื้อหาไปถึงแบรนด์ได้จริง แต่อย่าหวังว่าคนชอบเนื้อหาแค่ไหน จะชอบแบรนด์เท่านั้น และสิ่งที่คนดูให้คะแนนสูงคือ ความเข้ากัน กับความจริงใจ ซึ่งตัดสินกันตั้งแต่ตอนเลือกว่าจะไปสนับสนุนอะไร ไม่ใช่สิ่งที่ซื้อสื่อเพิ่มทีหลังแล้วจะแก้ได้",
                  "The lesson for a brand thinking of sponsoring content a community makes for itself is that goodwill really does pass from the content to the brand, but do not expect people to like the brand as much as they like the content. And what viewers rated highest, fit and sincerity, is decided at the moment you choose what to sponsor. It is not something you fix afterwards by buying more media.",
                  "บทเรียน", "The lesson",
                  "ความรู้สึกดีส่งต่อได้ แต่ไม่หนึ่งต่อหนึ่ง · เข้ากันกับจริงใจ ตัดสินตอนเลือกว่าจะสนับสนุนอะไร",
                  "Goodwill carries over, but not one for one · fit and sincerity are settled when you choose what to sponsor",
                  "หัวใจกระดาษกับเหรียญกระดาษวางคู่กันเว้นช่องเล็กน้อย — เนื้อหากับเงินสนับสนุน",
                  "ONE flat paper heart shape and ONE small flat paper coin lying side by side with a small gap between them. Two objects, nothing else."),
            caveat("ข้อควรระวัง งานนี้ดูว่าอะไรไปด้วยกัน ไม่ได้พิสูจน์ว่าอะไรเป็นเหตุ คนตอบมาจากแฟนซับกลุ่มเดียว และเป็นคนที่ยังติดตามอยู่ คนที่ดูแล้วไม่ชอบก็เลิกติดตามไปก่อนแล้ว ทีมวิจัยจึงเรียกตัวเลขนี้ว่าเป็นการประมาณอย่างมีข้อมูล ไม่ใช่ความเห็นของสาธารณะ และยังไม่ได้วัดว่าความรู้สึกดีนำไปสู่การซื้อจริงไหม",
                   "One caution: this study shows what goes together, not what causes what. The people surveyed came from a single fansub group and were still following it; anyone who watched and disliked it had already left. That is why the authors call their figures an educated guess rather than public opinion. And whether goodwill leads to buying was not tested.",
                   "ดูว่าอะไรไปด้วยกัน ไม่ใช่เหตุและผล · แฟนซับกลุ่มเดียว คนที่ยังติดตาม · ยังไม่ได้วัดการซื้อ",
                   "What goes together, not cause · one fansub group, current followers · buying not tested"),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "stance", "batch": 4,
        "slug": "brand-attitude-congruence-purchase",
        "name_th": "จุดยืนของแบรนด์กับการอยากซื้อ",
        "name_en": "Brand stance and the intention to buy",
        "label": {"th": "งานวิจัย · จุดยืนของแบรนด์", "en": "Research · Brand stance"},
        "scenes": [
            scene("hook", 9,
                  "แบรนด์ควรประกาศจุดยืนต่อประเด็นสังคมไหม … คนรุ่นใหม่บอกว่า จุดยืนตรงกันแล้วอยากซื้อ แต่นั่นเป็นแค่ส่วนเสริม ไม่ใช่ตัวหลัก",
                  "Should a brand take a public stand on social issues? … Young consumers say a matching stance makes them want to buy, but it turns out to be a supplement, not the main road.",
                  "งานวิจัย · จุดยืนของแบรนด์", "Research · Brand stance",
                  "จุดยืนที่ตรงกัน ทำให้นิสิตอยากซื้อจริง แต่เป็นแค่ส่วนหนึ่งของเส้นทาง ไม่ใช่ทั้งหมด",
                  "A shared stance does move students toward buying, but it carries part of the route, not the whole of it",
                  "ภาพประจำบทความ (มีแล้ว): สะพานสองช่วงพาดระหว่างเสาคู่เดียวกัน ช่วงบนกว้างหนา ช่วงล่างแคบ — ทางหลักกับทางเสริม", None, image="existing"),
            scene("method", 19,
                  "ทีมวิจัยให้นิสิตนักศึกษาไทยอายุสิบแปดถึงยี่สิบสี่ปี จากหลายมหาวิทยาลัย สี่ร้อยสามสิบสี่คน ตอบแบบสอบถามเกี่ยวกับแบรนด์อสังหาริมทรัพย์รายหนึ่ง ถามว่าจุดยืนของแบรนด์ตรงกับของตัวเองแค่ไหน นึกถึงแบรนด์ได้ง่ายไหม ภาพลักษณ์เป็นอย่างไร เชื่อถือได้ไหม รู้สึกเป็นส่วนหนึ่งของชุมชนแบรนด์ไหม และตั้งใจจะซื้อไหม แล้ววิเคราะห์ด้วยแบบจำลองทางสถิติว่าจุดยืนที่ตรงกัน ส่งผลต่อการอยากซื้อผ่านทางไหน",
                  "The research team had four hundred and thirty-four Thai university students aged eighteen to twenty-four, from several universities, fill in a questionnaire about one property brand. It asked how far the brand's stance matched their own, how easily the brand came to mind, what its image was like, whether it could be trusted, whether they felt part of its community, and whether they intended to buy. A statistical model then traced which route a matching stance takes on the way to wanting to buy.",
                  "ทำอะไร", "What was done",
                  "นิสิต 434 คน อายุ 18–24 ปี · แบรนด์อสังหาริมทรัพย์ 1 แบรนด์ · มาตรวัด 7 ระดับ",
                  "434 students aged 18–24 · one property brand · seven-point scale",
                  "แผ่นรองเขียนกระดาษหนึ่งแผ่นมีคลิปเล็กที่ขอบบน — แบบสอบถาม",
                  "ONE flat paper clipboard: a rectangle with a small paper clip along its top edge, lying flat on the table. One object, nothing else."),
            scene("finding", 13,
                  "ข้อที่ได้คะแนนสูงที่สุดในแบบสอบถามทั้งชุดคือ จะซื้อจากแบรนด์ที่มีจุดยืนตรงกับเรามากกว่า ได้ห้าจุดเจ็ดสี่จากเจ็ด และคนตอบยังบอกด้วยว่า จะไม่ค่อยซื้อจากแบรนด์ที่มีจุดยืนตรงข้าม",
                  "The single highest-scoring item in the whole questionnaire was: I am more likely to buy from brands whose stance matches mine, at five point seven four out of seven. And people also said they would be less likely to buy from a brand that took the opposite position.",
                  "จุดยืนมีน้ำหนักจริง", "Stance carries weight",
                  "ซื้อจากแบรนด์ ที่จุดยืนตรงกัน 5.74 จาก 7 · สูงสุดทั้งชุด · จุดยืนตรงข้าม ซื้อน้อยลง",
                  "Buy from a brand with a matching stance 5.74 of 7 · highest item · opposite stance, less likely",
                  "ลูกศรกระดาษสองอันวางคู่กันชี้ไปทางเดียวกัน — จุดยืนที่ตรงกัน",
                  "exactly TWO flat paper arrows lying side by side and pointing in the same direction. Two objects, nothing else."),
            scene("finding", 17,
                  "แต่พอดูเส้นทางว่าจุดยืนที่ตรงกันพาไปถึงการอยากซื้อได้แค่ไหน ปรากฏว่าเป็นทางเสริม ทางอ้อมที่ผ่านจุดยืน ได้จุดสิบแปด ส่วนเส้นทางรวมทั้งหมด ได้จุดเก้าห้า แปลว่าคุณค่าของแบรนด์ยังพาคนไปถึงการอยากซื้อโดยตรงเป็นส่วนใหญ่ จุดยืนช่วย แต่ไม่ใช่ตัวหลัก",
                  "But when the team traced how much of the route to buying actually ran through a matching stance, it turned out to be a side road. The path through stance came to point one eight, against a total path of point nine five. So the value of the brand still carries people to buying mostly by the direct route. Stance helps, but it is not the main road.",
                  "ทางเสริม ไม่ใช่ทางหลัก", "A side road, not the main one",
                  "ทางอ้อมผ่านจุดยืน .18 · เส้นทางรวม .95 · คุณค่าแบรนด์ ยังพาไปโดยตรง เป็นส่วนใหญ่",
                  "Through stance .18 · total path .95 · brand value still mostly goes direct",
                  "แถบกระดาษกว้างหนึ่งเส้นกับแถบแคบอีกเส้นวางขนานกัน — ทางหลักกับทางเสริม",
                  "ONE wide flat paper strip and ONE much narrower paper strip of the same length lying parallel to each other with a small gap between them. Two objects, nothing else."),
            scene("finding", 16,
                  "สิ่งที่ได้คะแนนสูงคือเรื่องพื้นฐาน นึกถึงแบรนด์ได้ง่าย ห้าจุดสี่สอง ภาพลักษณ์ดี ห้าจุดหกสอง ทำได้ตามที่โฆษณาไว้ ห้าจุดสามหก ส่วนข้อที่ได้คะแนนต่ำที่สุด คือความรู้สึกว่าตัวเองเป็นส่วนหนึ่งของชุมชนแบรนด์ คนเห็นด้วยกับแบรนด์ แต่ไม่ได้รู้สึกว่าตัวเองเป็นสมาชิก",
                  "What scored high were the basics: the brand comes to mind easily, five point four two; a good image, five point six two; it delivers what its advertising promises, five point three six. What scored lowest was feeling part of the brand's community. People agreed with the brand, but did not feel they belonged to it.",
                  "เห็นด้วย ไม่เท่ากับเป็นสมาชิก", "Agreeing is not belonging",
                  "นึกถึงได้ง่าย 5.42 · ภาพลักษณ์ดี 5.62 · ทำตามที่โฆษณา 5.36 · ความรู้สึกเป็นชุมชน ต่ำสุด",
                  "Comes to mind 5.42 · good image 5.62 · delivers on ads 5.36 · sense of community lowest",
                  "วงแหวนกระดาษใหญ่หนึ่งวง กับวงกลมกระดาษเล็กวางอยู่นอกวง — เห็นด้วย แต่ไม่ได้อยู่ข้างใน",
                  "ONE large flat paper ring lying on the table and ONE small flat paper circle lying just outside the ring. Two objects, nothing else."),
            scene("lesson", 23,
                  "บทเรียนสำหรับแบรนด์ที่กำลังชั่งใจว่าจะแสดงจุดยืนไหมก็คือ จุดยืนที่ตรงกันมีน้ำหนักจริงกับคนรุ่นนี้ แต่มันทำงานเป็นส่วนเสริม ฐานที่ต้องมีก่อนคือ คนนึกถึงแบรนด์ได้ ภาพลักษณ์ดี และทำได้ตามที่โฆษณาไว้ และการที่คนเห็นด้วยกับจุดยืน ไม่ได้แปลว่าเขาอยากเป็นสมาชิกชุมชนของแบรนด์ สองอย่างนี้เป็นคนละเป้าหมาย และต้องออกแบบคนละแบบ",
                  "The lesson for a brand weighing whether to take a stand is that a matching stance genuinely carries weight with this generation, but it works as a supplement. The base that has to be there first is that people know the brand, think well of it, and see it deliver what it advertises. And agreeing with a brand's stance does not mean wanting to join its community. Those are two different goals, and they need two different designs.",
                  "บทเรียน", "The lesson",
                  "จุดยืนมีน้ำหนัก แต่เป็นส่วนเสริม · ฐานคือ รู้จัก ภาพลักษณ์ ทำตามที่โฆษณา · เห็นด้วย ไม่เท่ากับอยากเป็นสมาชิก",
                  "Stance matters, as a supplement · the base is awareness, image, delivering · agreeing is not joining",
                  "ลูกบาศก์กระดาษใหญ่หนึ่งก้อน มีลูกบาศก์เล็กวางอยู่ด้านบน — ฐานกับส่วนเสริม",
                  "ONE large paper cube standing on the table with ONE much smaller paper cube resting on top of it. Two objects, nothing else."),
            caveat("ข้อควรระวัง ทีมวิจัยระบุเองว่ากลุ่มตัวอย่างไม่ใหญ่ และทุกอย่างมาจากคำตอบของคนตอบเอง ค่าเส้นทางรวมที่จุดเก้าห้าสูงผิดปกติ ซึ่งมักเกิดเมื่อวัดทุกเรื่องด้วยแบบสอบถามชุดเดียวในคราวเดียว จึงควรอ่านขนาดของผลอย่างระวัง เป็นแบรนด์เดียวในหมวดอสังหาริมทรัพย์ กับนิสิตที่ส่วนใหญ่ยังไม่ใช่คนซื้อบ้านจริง และวัดความตั้งใจซื้อ ไม่ใช่การซื้อจริง",
                   "One caution: the authors themselves say the sample is modest and everything comes from what people said about themselves. The total path of point nine five is unusually high, which often happens when everything is measured with one questionnaire in one sitting, so read the size of the effect with care. It is one brand in one category, property, with students who are mostly not yet home buyers. And it measures intending to buy, not buying.",
                   "กลุ่มตัวอย่างไม่ใหญ่ · ค่า .95 สูงผิดปกติ · แบรนด์เดียว หมวดเดียว · นิสิตส่วนใหญ่ยังไม่ใช่ผู้ซื้อ · ความตั้งใจ ไม่ใช่การซื้อจริง",
                   "Modest sample · .95 unusually high · one brand, one category · mostly not yet buyers · intention, not purchase", secs=(12, 12)),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "cogload", "batch": 4,
        "slug": "online-class-cognitive-load-interactive-media",
        "name_th": "สื่อโต้ตอบในห้องเรียนออนไลน์",
        "name_en": "Interactive media in an online class",
        "label": {"th": "งานวิจัย · การสอนออนไลน์", "en": "Research · Online teaching"},
        "scenes": [
            scene("hook", 9,
                  "ห้องเรียนออนไลน์ที่มีทั้งเว็บนำเสนอ วิดีโอ ควิซแข่งขัน และสอบก่อนหลังทุกสัปดาห์ … ช่วยให้จำได้จริง แต่ยิ่งสอบซ้ำ คนยิ่งหาย",
                  "An online class with a presentation website, videos, competitive quizzes and tests before and after every week … it did help students remember. But every repeat lost more of the room.",
                  "งานวิจัย · การสอนออนไลน์", "Research · Online teaching",
                  "ควิซซ้ำในห้องเรียนออนไลน์ ช่วยความจำระยะสั้นจริง แต่ยิ่งซ้ำ นักศึกษายิ่งถอย และการเอาไปใช้ ต้องอาศัยการพูดคุย",
                  "Repeated quizzes online do lift short-term recall, but each repeat loses students, and applying the material takes conversation",
                  "ภาพประจำบทความ (มีแล้ว): แถบกระดาษพับจีบ จีบซ้ายสูงคม แล้วค่อยเตี้ยและหย่อนไปทางขวา — ผลที่ลดลงทุกรอบ", None, image="existing"),
            scene("method", 20,
                  "ผู้วิจัยสอนวิชาวางแผนการสื่อสารเชิงกลยุทธ์ให้นักศึกษาปริญญาโทปีหนึ่ง ยี่สิบสามคน ผ่านออนไลน์ทั้งภาคการศึกษา ในปีการศึกษาสองพันห้าร้อยหกสิบสี่ ทุกสัปดาห์มีแบบทดสอบก่อนและหลังเรียน มีสไลด์บนเว็บ วิดีโอบันทึกการสอน และควิซแข่งขันสองรอบ รอบสองใช้คำถามชุดเดิมทวนก่อนสอบปลายภาค คะแนนทั้งหมดไม่นับเป็นเกรด และบอกนักศึกษาไว้ก่อน แล้วสัมภาษณ์นักศึกษาตลอดสิบหกสัปดาห์",
                  "The researchers taught a strategic communication planning course to twenty-three first-year master's students, fully online for the whole term in the twenty twenty-one academic year. Every week there was a test before and after class, plus web slides, recorded lectures, and competitive quizzes in two rounds, the second reusing the same questions before the final exam. None of the scores counted towards grades, and the students knew that in advance. The team also interviewed them across the sixteen weeks.",
                  "ทำอะไร", "What was done",
                  "นักศึกษาปริญญาโท 23 คน · ออนไลน์ทั้งเทอม · สอบก่อนหลังทุกสัปดาห์ · ควิซแข่งขัน 2 รอบ · คะแนนไม่นับเกรด",
                  "23 master's students · fully online · weekly pre and post tests · two quiz rounds · scores did not count",
                  "กระดาษสี่เหลี่ยมหนึ่งแผ่นเป็นจอ กับวงกลมกระดาษเล็กสามวงเรียงอยู่ข้างใต้ — ห้องเรียนออนไลน์",
                  "ONE flat paper rectangle lying on the table like a screen, with exactly THREE small flat paper circles lying in a row just below it. Four objects in total, nothing else."),
            scene("finding", 16,
                  "คะแนนหลังใช้สื่อโต้ตอบสูงกว่าก่อนใช้ชัดเจน เฉลี่ยรวมจากหกจุดเจ็ดเจ็ด ขึ้นเป็นแปดจุดสอง แต่พอดูทีละสัปดาห์ ไม่ได้ผลทุกสัปดาห์ แบบทดสอบเรื่องการวางแผน ขึ้นชัดห้าจากสิบเอ็ดสัปดาห์ ส่วนแบบทดสอบคู่มือการตัดสินใจ ขึ้นชัดเจ็ดจากสิบครั้ง ที่เหลือคะแนนขึ้นบ้าง แต่ไม่ถึงกับชัด",
                  "Scores after the interactive media were clearly higher than before: the overall average went from six point seven seven to eight point two. But week by week it did not work every time. The planning tests rose clearly in five of eleven weeks, the decision-guide tests in seven of ten. The rest went up a little, but not by much.",
                  "จำได้มากขึ้น", "Better recall",
                  "เฉลี่ยรวม 6.77 → 8.20 · ขึ้นชัด 5 จาก 11 สัปดาห์ และ 7 จาก 10 ครั้ง",
                  "Overall 6.77 → 8.20 · clear gains in 5 of 11 weeks and 7 of 10 tests",
                  "แท่งกระดาษสองแท่งตั้งคู่กัน แท่งขวาสูงกว่าเล็กน้อย — คะแนนที่ขึ้น",
                  "exactly TWO upright paper columns standing side by side, the right one about a fifth taller than the left. Two objects, nothing else."),
            scene("finding", 20,
                  "แต่พอทวนซ้ำ กลับไม่ได้เพิ่มอีก ทำแบบทดสอบชุดเดิมรอบสอง ได้แปดจุดเจ็ดเจ็ด เทียบกับแปดจุดสิบเก้า ไม่ต่างกัน ควิซแข่งขันรอบสองได้หกจุดสาม เทียบกับหกจุดสี่หกในรอบแรก ก็ไม่ต่างกัน และคนที่มาเล่นลดจากราวสิบถึงยี่สิบคน เหลือสี่ถึงสิบคน ผู้วิจัยอ่านว่าเป็นความเบื่อจากการสอบซ้ำ และการที่คะแนนไม่นับเกรด",
                  "But repeating did not add more. The same test taken a second time scored eight point seven seven against eight point one nine, no real difference. The second quiz round scored six point three against six point four six the first time, again no difference. And the number of students turning up fell from around ten to twenty, to four to ten. The researchers read that as boredom with repeated testing, and the fact that the scores did not count.",
                  "ซ้ำแล้วไม่เพิ่ม", "Repeating adds nothing",
                  "รอบสอง 8.77 กับ 8.19 ไม่ต่าง · ควิซรอบสอง 6.30 กับ 6.46 ไม่ต่าง · คนมาเล่น 10–20 คน → 4–10 คน",
                  "Second run 8.77 vs 8.19, no difference · second quiz 6.30 vs 6.46 · turnout 10–20 → 4–10",
                  "แท่งกระดาษสูงหนึ่งแท่ง กับแท่งสูงครึ่งเดียวตั้งข้างกัน — คนมาเล่นเหลือครึ่ง",
                  "ONE tall upright paper column and ONE column half its height standing beside it with a small gap. Two objects, nothing else."),
            scene("finding", 21,
                  "นักศึกษาบอกเองว่า ควิซช่วยให้จำได้ในระยะสั้น แต่ไม่ได้ช่วยให้เอาไปใช้ทำโครงงาน สิ่งที่ช่วยเรื่องนั้นคือ การได้พูดคุยกับผู้สอนและเพื่อนแบบสด ตัวอย่างแผนและกรณีศึกษา และคำแนะนำตรงจากผู้สอน ที่น่าคิดคือ นักศึกษาขอสไลด์เป็นไฟล์ธรรมดามาจดโน้ต ทั้งที่มีเว็บนำเสนอที่ฝังวิดีโอและลิงก์ให้แล้ว สื่อที่ดึงความสนใจมากเกินไป กลับดึงสมองออกจากเนื้อหา",
                  "The students said it themselves: quizzes helped them remember in the short term, but not apply the material to their projects. What helped with that was talking live with the lecturer and classmates, sample plans and case studies, and direct feedback from the lecturer. And here is the telling part. They asked for the slides as plain files they could write notes on, even though a web presentation with videos and links was already there. Media that pulls too much attention pulls the mind away from the content.",
                  "จำ กับ เอาไปใช้", "Remembering versus applying",
                  "ควิซ = จำระยะสั้น · เอาไปใช้ = พูดคุยสด ตัวอย่างแผน คำแนะนำ · ขอสไลด์ไฟล์ธรรมดามาจดโน้ต",
                  "Quiz = short-term memory · applying = live talk, sample plans, feedback · asked for plain slides to take notes",
                  "กรอบคำพูดกระดาษสองใบหันเข้าหากัน — การพูดคุย",
                  "exactly TWO flat paper speech bubbles lying on the table facing each other, their tails pointing toward one another. Two objects, nothing else."),
            scene("lesson", 23,
                  "บทเรียนสำหรับคนสอนออนไลน์ก็คือ การทดสอบบ่อยใช้ได้กับการจำ แต่ผลตอบแทนลดลงเร็ว ควิซรอบสองแทบไม่เพิ่มอะไร และทำให้คนหายไปครึ่งห้อง การนำไปใช้เกิดจากการพูดคุยและงานจริงที่มีผู้สอนเป็นที่ปรึกษา ไม่ใช่จากสื่อที่ดูทันสมัย ผู้วิจัยจึงเสนอให้ลดการสอบวัดความจำ ใช้คำถามหลายแบบ รวมควิซไว้ที่เดียว และเปิดวงคุยสดทุกราวสามสิบนาทีระหว่างบรรยาย",
                  "The lesson for anyone teaching online is that frequent testing works for memory, but the returns fall off fast. The second quiz added almost nothing and lost half the room. Applying knowledge came from conversation and real work with the lecturer as adviser, not from media that looked sophisticated. So the researchers suggest fewer memory tests, more varied questions, one place for all the quizzes, and a live discussion about every thirty minutes of lecture.",
                  "บทเรียน", "The lesson",
                  "สอบบ่อยได้ผลกับการจำ แต่ลดลงเร็ว · การนำไปใช้มาจากการพูดคุย · เปิดวงคุยสดทุก 30 นาที",
                  "Frequent tests help memory, briefly · applying comes from conversation · a live discussion every 30 minutes",
                  "หน้าปัดนาฬิกากระดาษ วงกลมหนึ่งวงกับเข็มสั้นสองเข็ม — ทุกสามสิบนาที",
                  "ONE flat paper circle lying on the table like a clock face, with exactly TWO short paper strips lying on it as clock hands. Three pieces in total, nothing else."),
            caveat("ข้อควรระวัง กลุ่มเดียวยี่สิบสามคน ไม่มีกลุ่มเปรียบเทียบ จึงแยกไม่ได้ว่าคะแนนที่ขึ้นมาจากสื่อโต้ตอบ หรือจากการเรียนตามปกติ ผู้วิจัยหลักเป็นผู้สอนวิชานี้เอง ซึ่งบทความระบุเป็นข้อจำกัด และมีผู้ช่วยวิจัยร่วมตรวจ หลายสัปดาห์มีคนทำแบบทดสอบแค่สิบถึงสิบเก้าคน และที่วัดคือความจำระยะสั้น ไม่ใช่ความจำระยะยาว",
                   "One caution: a single group of twenty-three with no comparison group, so the gains cannot be separated from ordinary learning over the term. The lead researcher was also the course lecturer, which the article names as a limitation, with research assistants checking the work. In many weeks only ten to nineteen students took the tests. And what was measured is short-term recall, not what stays in memory later.",
                   "กลุ่มเดียว 23 คน ไม่มีกลุ่มเปรียบเทียบ · ผู้วิจัยเป็นผู้สอนเอง · หลายสัปดาห์ทำสอบแค่ 10–19 คน · วัดความจำระยะสั้น",
                   "One group of 23, no comparison · researcher was the lecturer · 10–19 took the tests some weeks · short-term recall only", secs=(12, 12)),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "ksharing", "batch": 4,
        "slug": "health-officers-knowledge-sharing",
        "name_th": "เจ้าหน้าที่สาธารณสุขกับการแลกเปลี่ยนความรู้",
        "name_en": "Health officers and knowledge sharing",
        "label": {"th": "งานวิจัย · การจัดการความรู้", "en": "Research · Knowledge management"},
        "scenes": [
            scene("hook", 9,
                  "ราชการกำหนดให้ทุกหน่วยงานจัดการความรู้ … แต่พอถามคนหน้างานว่าติดตรงไหน คำตอบอันดับหนึ่งคือ ไม่คุ้นเครื่องมือใหม่",
                  "Every Thai government office is required to run knowledge management … but ask the officers who have to do it where they get stuck, and the top answer is: unfamiliar new tools.",
                  "งานวิจัย · การจัดการความรู้", "Research · Knowledge management",
                  "อุปสรรคใหญ่ที่สุด คือไม่คุ้นเครื่องมือใหม่ เจ้าหน้าที่จึงเลือก เครื่องมือที่ใช้อยู่ทุกวัน กับการเจอหน้ากัน",
                  "The biggest obstacle was unfamiliar technology, so the staff chose the tool they already used daily, and each other",
                  "ภาพประจำบทความ (มีแล้ว): ประตูบานใหม่ปิดอยู่ ข้างบานเก่าที่เปิดค้างและมีร่องรอยใช้งาน — เครื่องมือใหม่กับของที่ใช้อยู่", None, image="existing"),
            scene("method", 19,
                  "ทีมวิจัยส่งแบบสอบถามทางไปรษณีย์ ถึงเจ้าหน้าที่กรมควบคุมโรคที่รับผิดชอบงานสื่อสารสุขภาพทั่วประเทศ หนึ่งร้อยสิบเอ็ดคน ได้กลับมาครบทุกคน เพราะผู้บริหารกำหนดให้ต้องตอบ ใช้เรื่องการสื่อสารป้องกันเบาหวานเป็นกรณีตั้งต้น ถามว่าติดขัดตรงไหน อยากแลกเปลี่ยนความรู้กันด้วยวิธีไหน บนช่องทางใด และอยากอยู่ในกลุ่มแบบไหน เลือกตอบได้มากกว่าหนึ่งข้อ",
                  "The research team mailed a questionnaire to one hundred and eleven officers in charge of health communication at the Department of Disease Control across the country, and every one of them replied, because senior management required it. Diabetes prevention was the reference topic. The questions asked where they got stuck, how they would rather share what they know, on which channel, and in what kind of group. People could pick more than one answer.",
                  "ทำอะไร", "What was done",
                  "เจ้าหน้าที่ 111 คน ทั่วประเทศ · ตอบครบ 100% เพราะผู้บริหารกำหนด · เลือกตอบได้หลายข้อ",
                  "111 officers nationwide · 100% replied, because management required it · more than one answer allowed",
                  "ซองจดหมายกระดาษหนึ่งซองวางราบ ฝาปิด — แบบสอบถามทางไปรษณีย์",
                  "ONE flat paper envelope lying on the table with its flap closed. One object, nothing else."),
            scene("finding", 18,
                  "อุปสรรคอันดับหนึ่งคือ ไม่คุ้นเคยกับเทคโนโลยีใหม่ ห้าสิบสี่เปอร์เซ็นต์ รองลงมาคือ มักแบ่งปันเรื่องที่ไม่เกี่ยว สี่สิบสามเปอร์เซ็นต์ และประสานงานไม่สะดวก สี่สิบเปอร์เซ็นต์ ส่วนที่ไม่อยากเปิดเผยข้อมูลมีสามสิบเจ็ดเปอร์เซ็นต์ ไม่มีแรงจูงใจสามสิบสองเปอร์เซ็นต์ และหนึ่งในสี่บอกว่า ปัญหาคือการถูกบังคับให้เข้าร่วมนั่นแหละ",
                  "The number one obstacle was unfamiliarity with new technology, at fifty-four percent. Next came a habit of sharing things that were not relevant, forty-three percent, and awkward coordination, forty percent. Thirty-seven percent did not want to disclose information, thirty-two percent had no motivation, and one in four said the problem was being made to take part in the first place.",
                  "ติดตรงไหน", "Where they got stuck",
                  "ไม่คุ้นเทคโนโลยีใหม่ 54.1% · แบ่งปันเรื่องไม่เกี่ยว 43.2% · ประสานงานไม่สะดวก 40.5% · ถูกบังคับเข้าร่วม 25.2%",
                  "Unfamiliar technology 54.1% · irrelevant sharing 43.2% · awkward coordination 40.5% · forced to take part 25.2%",
                  "กล่องกระดาษปิดใบเล็ก กับกุญแจกระดาษวางอยู่ข้างๆ — เครื่องมือที่ยังไม่คุ้น",
                  "ONE small closed paper box and ONE flat paper key lying on the table beside it. Two objects, nothing else."),
            scene("finding", 14,
                  "ช่องทางที่เลือกมากที่สุดคือเฟซบุ๊ก ห้าสิบสามเปอร์เซ็นต์ ทิ้งห่างเว็บบอร์ดกับอีเมลที่ได้ราวยี่สิบเปอร์เซ็นต์ ส่วนทวิตเตอร์ได้แค่หกเปอร์เซ็นต์ เจ้าหน้าที่ไม่ได้อยากได้แพลตฟอร์มใหม่ แต่อยากใช้ช่องทางที่ใช้อยู่แล้วทุกวัน",
                  "The channel they chose most was Facebook, at fifty-three percent, far ahead of web boards and email at around twenty percent, with Twitter at just six percent. The officers did not want a new platform. They wanted the channel already in their daily lives.",
                  "ช่องทางที่เลือก", "The channel they chose",
                  "เฟซบุ๊ก 53.2% · เว็บบอร์ดและอีเมล 19.8% · แชต 18.9% · ทวิตเตอร์ 6.3%",
                  "Facebook 53.2% · web boards and email 19.8% · chat 18.9% · Twitter 6.3%",
                  "วงกลมกระดาษใหญ่หนึ่งวง กับวงกลมเล็กสามวงเรียงอยู่ข้างๆ — ช่องทางเดียวที่ทิ้งห่าง",
                  "ONE large flat paper circle and exactly THREE much smaller flat paper circles lying in a row beside it. Four objects in total, nothing else."),
            scene("finding", 19,
                  "แต่กิจกรรมที่อยากได้ กลับเป็นแบบพบหน้ากัน ประชุมและศึกษาดูงาน สามสิบเอ็ดเปอร์เซ็นต์ บรรยายและอบรมเชิงปฏิบัติการ สามสิบเปอร์เซ็นต์ และมีพี่เลี้ยงคอยแนะ ยี่สิบเจ็ดเปอร์เซ็นต์ และคำตอบที่ชัดที่สุดของทั้งชุดคือ อยากอยู่ในกลุ่มที่คละประสบการณ์และมีพี่เลี้ยง ห้าสิบหกเปอร์เซ็นต์ เทียบกับกลุ่มที่มีแต่คนช่ำชอง สิบหกเปอร์เซ็นต์ และกลุ่มมือใหม่ล้วน แค่หกเปอร์เซ็นต์",
                  "But the activities they wanted were face to face: meetings and study visits, thirty-one percent; lectures and workshops, thirty percent; having a mentor, twenty-seven percent. And the clearest answer in the whole survey was the kind of group they wanted: mixed experience with a mentor, at fifty-six percent, against sixteen percent for a group of old hands only, and just six percent for beginners only.",
                  "คนสำคัญกว่าเครื่องมือ", "People over tools",
                  "อยากพบหน้า · ประชุมดูงาน 30.6% · อบรม 29.7% · พี่เลี้ยง 27.0% · กลุ่มคละประสบการณ์ มีพี่เลี้ยง 55.9%",
                  "Face to face · meetings and visits 30.6% · workshops 29.7% · mentoring 27.0% · mixed group with a mentor 55.9%",
                  "ลูกบาศก์กระดาษคนละขนาดตั้งชิดกัน — กลุ่มคละประสบการณ์ (ภาพที่เจนได้มีสี่ก้อน ใหญ่ กลางสอง เล็ก ไม่ใช่สามตามบรีฟ ยังอ่านเป็นกลุ่มคละขนาดได้ จึงคงไว้)",
                  "exactly THREE paper cubes of different sizes, one large, one medium and one small, standing close together in a group. Three objects, nothing else."),
            scene("lesson", 22,
                  "บทเรียนสำหรับคนที่ต้องวางระบบจัดการความรู้ในองค์กรก็คือ คำตอบของคนหน้างานสวนทางกับที่มักคิดกันว่า ต้องเริ่มที่แพลตฟอร์มใหม่ ในเมื่ออุปสรรคอันดับหนึ่งคือความไม่คุ้นเคย การเพิ่มเครื่องมือใหม่ยิ่งทำให้ปัญหาหนักขึ้น สิ่งที่เจ้าหน้าที่เลือกคือ ช่องทางที่ใช้อยู่แล้ว บวกกับคนที่คอยแนะ เทคโนโลยีเป็นเรื่องรอง ความสัมพันธ์เป็นเรื่องหลัก",
                  "The lesson for anyone setting up knowledge management in an organisation is that the people doing the work answered against the usual assumption that you start with a new platform. When the top obstacle is unfamiliarity, adding another tool makes the problem worse. What the officers chose was the channel they already used, plus people to guide them. Technology comes second. Relationships come first.",
                  "บทเรียน", "The lesson",
                  "อย่าเริ่มที่แพลตฟอร์มใหม่ · ใช้ช่องทางที่ใช้อยู่แล้ว บวกคนที่คอยแนะ · เทคโนโลยีเป็นรอง ความสัมพันธ์เป็นหลัก",
                  "Do not start with a new platform · the channel they already use, plus a guide · technology second, relationships first",
                  "หัวใจกระดาษวางอยู่บนกระดาษสี่เหลี่ยมที่เป็นจอ — ความสัมพันธ์อยู่เหนือเทคโนโลยี",
                  "ONE flat paper heart shape lying on top of ONE larger flat paper rectangle. Two objects, nothing else."),
            caveat("ข้อควรระวัง ที่ตอบครบทุกคน เพราะผู้บริหารกำหนดให้ตอบ ไม่ใช่ความสมัครใจ คำตอบจึงอาจเอนไปทางที่คิดว่าองค์กรอยากได้ยิน เป็นความชอบที่บอกเอง ไม่ใช่พฤติกรรมที่สังเกตได้จริง และเก็บข้อมูลปีสองพันห้าร้อยห้าสิบเจ็ดถึงห้าสิบแปด ตัวเลือกในแบบสอบถามยังมีไฮไฟฟ์อยู่เลย บทบาทของเฟซบุ๊กในที่ทำงานวันนี้จึงต่างจากตอนนั้นมาก",
                   "One caution: everyone replied because management required it, not because they wanted to, so answers may lean toward what people thought the organisation wanted to hear. These are preferences people stated, not behaviour anyone observed. And the data is from twenty fourteen to twenty fifteen. The list of options still included Hi-five, and Facebook's place in Thai workplaces has changed a great deal since.",
                   "ตอบครบเพราะถูกกำหนด · ความชอบที่บอกเอง · ข้อมูลปี 2557–2558 ยังมีไฮไฟฟ์ในตัวเลือก",
                   "Replied because required · stated preferences · data from 2014–2015, Hi5 still on the list", secs=(12, 12)),
            closing(),
        ],
    },
]
