"""สตอรี่บอร์ดชุดที่ 3 — 5 เรื่อง × ไทย/อังกฤษ (4 ก.ย. 2569) — storyboard.py นำเข้าไฟล์นี้แล้วต่อท้าย CLIPS/PALETTE

กติกาเดียวกับชุดที่ 2 (ดูหัวไฟล์ storyboard_batch2.py) · ข้อเพิ่มของชุดนี้:
  · คลิปโควิดไม่เอ่ยชื่อบุคคล ยี่ห้อวัคซีน หรือบริษัท (กติกาข้อ 5 — บทสรุปบนเว็บก็ตัดออกแล้ว) และพูดว่า "รัฐบาล" ไม่ใช่ "ผู้นำรัฐบาล"
  · คลิปวีทูปเบอร์ไม่เอ่ยชื่ออินฟลูเอนเซอร์สองคนที่ใช้เป็นสิ่งเร้า
  · เลือกเรื่องคริปโต Reddit ออก เพราะบทสรุปบนเว็บบางเกินกว่าจะเล่า 8 ฉากได้ (ไม่มีตัวเลข) — สลับเป็นวีทูปเบอร์
"""
from storyboard_batch2 import CLOSING2, ASTERISK

CLOSING3 = CLOSING2

# คู่สีอ่านจากภาพประจำบทความของแต่ละเรื่อง (ดูภาพจริง frames/b3-illustrations.png) เพื่อให้ภาพใหม่กลมกลืนกับภาพ hook
PALETTE3 = {
    "covidcred": {"object": "soft coral pink", "shadow": "deep teal", "obj_hex": "#F3A498", "sh_hex": "#1F6B72",
                  "shadow_style": "clean flat-edged shadows to the lower right rendered as solid deep-teal shapes, like cut paper rather than soft photographic shadows"},
    "cruelty": {"object": "sage green", "shadow": "soft olive-grey", "obj_hex": "#8FB07A", "sh_hex": "#A8A48C",
                "shadow_style": "soft olive-grey shadows to the lower right, as in a real studio photograph of paper on a table"},
    "techno": {"object": "deep wine magenta", "shadow": "sage green", "obj_hex": "#8B1E4A", "sh_hex": "#9CA86E",
               "shadow_style": "soft sage-green shadows to the lower right, as in a real studio photograph of paper on a table"},
    "joox": {"object": "vivid rose pink", "shadow": "olive green", "obj_hex": "#E0578B", "sh_hex": "#9BA36A",
             "shadow_style": "clean flat-edged shadows to the lower right rendered as solid olive-green shapes, like cut paper rather than soft photographic shadows"},
    "vtuber": {"object": "olive green", "shadow": "soft rose pink", "obj_hex": "#8C9A4E", "sh_hex": "#E8A0B8",
               "shadow_style": "soft rose-pink shadows to the lower right, as in a real studio photograph of paper on a table"},
}


def closing():
    return {"role": "closing", "secs": (14, 14), "image": "logo", "narr": CLOSING3, "label": None, "text": None,
            "visual_th": "การ์ดปิดประจำชุด + ชื่อผู้เขียนทุกคน (ไม่ต้องเจนภาพ)", "subject": None}


def caveat(narr_th, narr_en, text_th, text_en, secs=(10, 10)):
    return {"role": "caveat", "secs": secs, "image": "new", "narr": {"th": narr_th, "en": narr_en},
            "label": {"th": "ข้อควรระวัง", "en": "One caution"}, "text": {"th": text_th, "en": text_en},
            "visual_th": "ดอกจันกระดาษพับหนึ่งดอก — สัญลักษณ์ประจำฉากข้อควรระวัง (คู่สีของคลิปนี้)", "subject": ASTERISK}


def scene(role, secs, narr_th, narr_en, label_th, label_en, text_th, text_en, visual_th, subject, image="new"):
    return {"role": role, "secs": (secs, secs), "image": image, "narr": {"th": narr_th, "en": narr_en},
            "label": {"th": label_th, "en": label_en}, "text": {"th": text_th, "en": text_en},
            "visual_th": visual_th, "subject": subject}


CLIPS3 = [
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "covidcred", "batch": 3,
        "slug": "covid-official-communication-credibility",
        "name_th": "ความน่าเชื่อถือของข้อความรัฐช่วงโควิด",
        "name_en": "Official COVID messaging and credibility",
        "label": {"th": "งานวิจัย · การสื่อสารในภาวะวิกฤต", "en": "Research · Crisis communication"},
        "scenes": [
            scene("hook", 9,
                  "ช่วงโควิด คนไทยเชื่อสิ่งที่รัฐบอกมากแค่ไหน … คำตอบไม่ได้อยู่ที่ว่ารัฐพูดจริงหรือไม่จริง แต่อยู่ที่ว่าตอนนั้น รัฐคุมโรคอยู่หรือเปล่า",
                  "How much did Thais trust what the government told them during COVID? … It turned out to have little to do with whether it was true, and everything to do with whether the outbreak looked under control.",
                  "งานวิจัย · การสื่อสารในภาวะวิกฤต", "Research · Crisis communication",
                  "คนเชื่อข้อความของรัฐ ตราบเท่าที่เห็นว่ารัฐคุมโรคได้ พอมาตรการล้มเหลว ความเชื่อก็หายไปด้วย",
                  "People believed official messaging as long as the government seemed to be winning. Once measures failed, belief went with them",
                  "ภาพประจำบทความ (มีแล้ว): แถบกระดาษสองเส้นไต่ขึ้นถึงยอดแล้วลาดลงพร้อมกัน — ความเชื่อถือกับผลงานเดินไปด้วยกัน", None, image="existing"),
            scene("method", 17,
                  "คณะผู้วิจัยไล่อ่านโพสต์และคอมเมนต์บนเฟซบุ๊กกับทวิตเตอร์ ตั้งแต่ต้นปีสองพันห้าร้อยหกสิบสาม จนถึงต้นปีสองพันห้าร้อยหกสิบห้า โดยค้นทีละเดือนตามแฮชแท็กที่คนใช้กันในช่วงนั้น แล้วสัมภาษณ์ผู้เชี่ยวชาญอีกห้าสิบคน ทั้งคนตรวจสอบข้อเท็จจริง คนทำงานด้านข้อมูลสุขภาพ นักข่าว และนักประชาสัมพันธ์ จากนั้นแบ่งเรื่องทั้งหมดออกเป็นสี่ช่วงของการระบาด",
                  "The authors read through posts and comments on Facebook and Twitter from early twenty twenty to early twenty twenty-two, searching month by month under the hashtags people were using at the time, and interviewed fifty experts: fact-checkers, health-information workers, journalists and people in public relations. Then they traced the story through the four waves of the outbreak.",
                  "ทำอะไร", "What was done",
                  "โพสต์และคอมเมนต์ 2 ปี · ผู้เชี่ยวชาญ 50 คน · แบ่งเป็น 4 ช่วง",
                  "Two years of posts · 50 expert interviews · four waves",
                  "กรอบคำพูดกระดาษสี่ใบขนาดต่างกันเล็กน้อยวางเรียงหลวมๆ — วาทกรรมสี่ช่วง",
                  "exactly FOUR flat paper speech bubbles of slightly different sizes lying in a loose row. Four objects, nothing else."),
            scene("finding", 16,
                  "ช่วงแรก รัฐพูดไม่ตรงกันเอง คนเลยหันไปยึดแนวทางขององค์การอนามัยโลกแทน แต่พอล็อกดาวน์ได้ผลกลางปีสองพันห้าร้อยหกสิบสาม ความเชื่อถือก็ขึ้นถึงจุดสูงสุด คนไว้ใจการแถลงรายวันที่มีหมอเป็นคนพูด และเรื่องหน้ากาก คนไทยเชื่อรัฐมากกว่าองค์การอนามัยโลกด้วยซ้ำ ทั้งที่ตอนนั้นองค์การอนามัยโลกยังไม่ได้แนะนำให้ใส่",
                  "In the early weeks the official line kept contradicting itself, so people turned to the World Health Organization instead. But once the lockdown worked, in mid twenty twenty, trust peaked. People believed the daily briefings, fronted by a doctor, and on masks they sided with the government over WHO, which was not yet recommending them.",
                  "ช่วงที่คุมได้", "While it worked",
                  "ล็อกดาวน์ได้ผล · ความเชื่อถือสูงสุด · เรื่องหน้ากาก คนเชื่อรัฐ มากกว่า WHO",
                  "Lockdown worked · credibility peaked · on masks, people trusted the government over WHO",
                  "โล่กระดาษตั้งตรงหนึ่งใบ กับเครื่องหมายถูกกระดาษพิงอยู่ — ช่วงที่คุมได้และคนไว้ใจ",
                  "ONE upright paper shield shape and ONE small paper tick mark (check mark) leaning against it. Two objects, nothing else."),
            scene("finding", 20,
                  "แล้วระลอกที่สามก็มา เมษายนสองพันห้าร้อยหกสิบสี่ เดือนเดียวมีคนติดเชื้อใหม่กว่าสามหมื่นหกพันคน มากกว่าที่สะสมมาทั้งหมดก่อนหน้านั้นเสียอีก ส่วนคนที่ฉีดวัคซีนครบ ยังไม่ถึงหนึ่งเปอร์เซ็นต์ มีคนเข้าชื่อออนไลน์ให้ปลดคนที่รับผิดชอบเรื่องนี้ ได้สองแสนชื่อในไม่กี่วัน และคะแนนนิยมรัฐบาลร่วงจากกว่าเก้าสิบเปอร์เซ็นต์ เหลือไม่ถึงยี่สิบ พอผลงานร่วง ความเชื่อถือก็ร่วงตาม",
                  "Then came the third wave. April twenty twenty-one alone brought more than thirty-six thousand new cases, more than the whole outbreak up to then, while fewer than one person in a hundred was fully vaccinated. An online petition to remove the official in charge gathered two hundred thousand signatures in days, and the government's approval fell from over ninety percent to under twenty. As performance collapsed, so did trust.",
                  "เมื่อผลงานตก", "When performance fell",
                  "เมษายน 2564 ติดเชื้อใหม่ 36,650 ราย · ฉีดครบไม่ถึง 1% · คะแนนนิยม 93% → 19%",
                  "April 2021: 36,650 new cases · under 1% fully vaccinated · approval 93% → 19%",
                  "แท่งกระดาษสองแท่ง แท่งหนึ่งสูง อีกแท่งเตี้ยไม่ถึงหนึ่งในสี่ — คะแนนนิยมที่ร่วง",
                  "exactly TWO upright paper columns standing side by side: one tall, the other less than a quarter of its height. Two objects, nothing else."),
            scene("finding", 16,
                  "ที่น่าสนใจคือ ทิศทางกลับหัวกับฝั่งตะวันตก ทางนั้น คนที่ไม่เชื่อรัฐใช้โซเชียลต่อต้านวัคซีน แต่ที่ไทย คนที่ไม่เชื่อรัฐกลับเรียกร้องให้เอาวัคซีนรุ่นใหม่กว่าเข้ามา แล้วเอาตัวเลขเปรียบเทียบจากองค์การอนามัยโลกกับซีดีซี มาโต้ว่ารัฐเลือกผิด พอสิ้นปีสองพันห้าร้อยหกสิบสี่ คนที่ฉีดแล้วหรือยินดีฉีด มีถึงเก้าสิบเปอร์เซ็นต์",
                  "And it ran the opposite way to the West. There, people who distrusted the government used social media to fight vaccines. In Thailand, people who distrusted the government demanded newer vaccines, and pulled up WHO and CDC comparisons to argue that the government had chosen badly. By the end of twenty twenty-one, ninety percent had either been vaccinated or wanted to be.",
                  "กลับทางกับตะวันตก", "The reverse of the West",
                  "คนไม่เชื่อรัฐ ไม่ได้ต้านวัคซีน แต่เรียกร้องวัคซีนรุ่นใหม่ · ปลายปี 2564 ยินดีฉีด 90%",
                  "Sceptics did not reject vaccines, they demanded newer ones · by late 2021, 90% vaccinated or willing",
                  "ลูกศรกระดาษสองอันวางคู่กัน ชี้คนละทาง — ทิศทางที่กลับกัน",
                  "exactly TWO flat paper arrows lying side by side and pointing in opposite directions. Two objects, nothing else."),
            scene("lesson", 24,
                  "บทเรียนสำหรับการสื่อสารในภาวะวิกฤตก็คือ คนจะเชื่อหรือไม่เชื่อ ขึ้นกับผลงานที่เขาเห็นด้วยตา ไม่ได้ขึ้นกับว่ารัฐพูดจริงหรือโปร่งใสแค่ไหน อธิบายดีแค่ไหนก็ไม่พอ ถ้าสิ่งที่คนเห็นมันสวนทางกัน และพอคนเลิกเชื่อ เขาไม่ได้เลิกหาข้อมูล แต่ย้ายไปฟังแหล่งที่เขาเชื่อมากกว่า รัฐที่อ้างองค์กรสากลอย่างเปิดเผย จึงยืมความน่าเชื่อถือตรงนั้นมาใช้ได้ ส่วนการคุมข้อมูลในช่วงที่คนไม่เชื่ออยู่แล้ว ยิ่งได้ผลตรงข้าม เพราะคนจะอ่านว่า มีอะไรต้องปิดหรือเปล่า",
                  "The lesson for crisis communication is that trust follows the results people can see, not how true or how transparent the message is. Explaining well is not enough when what people see points the other way. And when trust goes, people do not stop looking for information. They go to sources they trust more. So an official voice that openly cites international bodies can borrow their credibility. And clamping down on information when trust is already low backfires, because it reads as having something to hide.",
                  "บทเรียน", "The lesson",
                  "ความน่าเชื่อถือตามผลงานที่คนเห็น · อ้างองค์กรสากลอย่างเปิดเผย · คุมข้อมูลตอนคนไม่เชื่อ ยิ่งเสีย",
                  "Credibility follows visible results · cite international bodies openly · controlling information when trust is low backfires",
                  "แถบกระดาษโค้งเป็นสะพานพาดบนบล็อกกระดาษสองก้อน และมีบล็อกอีกสองก้อนวางอยู่ข้างๆ — ยืมความน่าเชื่อถือข้ามไป (ภาพที่เจนได้มีบล็อกสี่ก้อน ไม่ใช่สามชิ้นตามบรีฟ ก้อนเกินเชื่อมกับเงาของสะพานจึงลบด้วย patch_bg ไม่ได้)",
                  "ONE long paper strip arched like a bridge, its two ends resting on TWO small paper blocks. Three pieces in total, nothing else."),
            caveat("ข้อควรระวัง งานนี้เป็นการอ่านและตีความ ไม่ได้นับว่ามีกี่โพสต์ และที่บอกว่าคะแนนนิยมกับความเชื่อถือไปด้วยกัน ก็ดูจากลำดับเหตุการณ์ ไม่ได้วัดเป็นสถิติ ส่วนคลิปนี้ตั้งใจไม่เอ่ยชื่อใคร ไม่เอ่ยยี่ห้อวัคซีนหรือบริษัทใด เพราะบทเรียนอยู่ที่กลไก ไม่ได้อยู่ที่ตัวบุคคล",
                   "One caution: this is a reading of events, not a count. It tallies no posts, and the link between approval and trust comes from the order things happened in, not from a statistical test. And this clip deliberately names no individuals, vaccine brands or companies, because the lesson is about the mechanism, not about who was involved.",
                   "อ่านและตีความ ไม่ได้นับโพสต์ · ดูจากลำดับเหตุการณ์ · ไม่เอ่ยชื่อบุคคล ยี่ห้อ หรือบริษัท",
                   "A reading of events, not a count · from the order things happened · no names, brands or companies", secs=(12, 12)),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "cruelty", "batch": 3,
        "slug": "genz-cruelty-free-purchase",
        "name_th": "เจนซีกับสินค้าที่ไม่ทดลองกับสัตว์",
        "name_en": "Gen Z and cruelty-free products",
        "label": {"th": "งานวิจัย · พฤติกรรมผู้บริโภค", "en": "Research · Consumer behaviour"},
        "scenes": [
            scene("hook", 8,
                  "เจนซีไทยเลือกสินค้าที่ไม่ทดลองกับสัตว์เพราะค่านิยม … แต่พอราคาขึ้น ค่านิยมจะพาไปถึงขั้นควักเงินจ่ายไหม",
                  "Thai Gen Z choose cruelty-free products out of their values … but when the price goes up, do values carry them to the checkout?",
                  "งานวิจัย · พฤติกรรมผู้บริโภค", "Research · Consumer behaviour",
                  "เจนซีเลือกสินค้าไม่ทดลองกับสัตว์ เพราะค่านิยม แต่สิ่งที่ทำนายการซื้อได้แรงที่สุด คือความภักดี ซึ่งหายไปเมื่อราคาขึ้น",
                  "Gen Z buy cruelty-free out of values. The strongest predictor of purchase is loyalty, and loyalty falls away when the price rises",
                  "ภาพประจำบทความ (มีแล้ว): ขั้นบันไดสามขั้น ขั้นบนสุดหลุดลอยห่างออกไป — ขั้นสุดท้ายที่ไปไม่ถึง", None, image="existing"),
            scene("method", 15,
                  "ทีมวิจัยทำแบบสอบถามออนไลน์กับคนไทยอายุสิบแปดถึงยี่สิบหกปี สี่ร้อยคน ที่รู้จักแบรนด์ที่ประกาศตัวว่าไม่ทดลองกับสัตว์ ถามสี่เรื่อง คือค่านิยม ความรู้สึกต่อวิธีที่แบรนด์ใช้สื่อสาร ความภักดีต่อแบรนด์ และความตั้งใจซื้อ แล้วดูว่าเรื่องไหนบอกได้จริงว่าคนจะซื้อ",
                  "The research team surveyed four hundred Thais aged eighteen to twenty-six who knew at least one brand that calls itself cruelty-free. They asked about four things: values, how people feel about the ways brands market to them, loyalty to the brand, and whether they intend to buy. Then they tested which of those actually predicts buying.",
                  "ทำอะไร", "What was done",
                  "400 คน อายุ 18–26 ปี · ถาม 4 เรื่อง · ค่านิยม ความรู้สึกต่อการสื่อสาร ความภักดี ความตั้งใจซื้อ",
                  "400 people aged 18–26 · four questions · values, feelings about marketing, loyalty, intention to buy",
                  "กระดาษสี่เหลี่ยมเล็กสี่แผ่นขนาดเท่ากัน วางเป็นตารางสองคูณสอง — สี่ด้านที่วัด",
                  "exactly FOUR small square paper tiles of identical size lying flat in a neat two-by-two grid with equal gaps. Four objects, nothing else."),
            scene("finding", 12,
                  "ค่านิยมที่คนให้คะแนนสูงสุด คือเรื่องดูแลสัตว์และธรรมชาติ ได้สี่จุดหกห้าจากห้า ส่วนเรื่องอยากให้คนรอบตัวยอมรับ ได้แค่สามจุดสามหก คนซื้อเพราะห่วงสัตว์จริง ไม่ใช่เพราะอยากดูดี",
                  "The value people rated highest was caring about animals and nature, at four point six five out of five. Being thought well of by the people around them scored only three point three six. They buy because they care, not to look good.",
                  "ค่านิยม", "The values",
                  "ดูแลสัตว์และธรรมชาติ 4.65 · การยอมรับจากคนรอบตัว 3.36 (จาก 5)",
                  "Care for animals and nature 4.65 · recognition from others 3.36 (out of 5)",
                  "หัวใจกระดาษหนึ่งดวงวางราบ มีใบไม้กระดาษใบเล็กวางอยู่บนนั้น — ค่านิยมเรื่องสัตว์และธรรมชาติ",
                  "ONE flat paper heart shape lying on the table with ONE small paper leaf resting on top of it. Two objects, nothing else."),
            scene("finding", 13,
                  "แต่สิ่งที่บอกได้แรงที่สุดว่าคนจะซื้อหรือไม่ซื้อ กลับไม่ใช่ค่านิยม แต่เป็นความภักดีต่อแบรนด์ รองลงมาคือความรู้สึกต่อการสื่อสารของแบรนด์ ส่วนค่านิยมมาเป็นอันดับสาม สามอย่างนี้รวมกัน อธิบายความตั้งใจซื้อได้ราวหกสิบสามเปอร์เซ็นต์",
                  "But the strongest sign that someone would actually buy was not values. It was loyalty to the brand, then how they felt about the brand's marketing, with values a distant third. Together the three explained about sixty-three percent of the intention to buy.",
                  "อะไรบอกว่าคนจะซื้อ", "What predicts buying",
                  "ความภักดี β .49 · ความรู้สึกต่อการสื่อสาร β .30 · ค่านิยม β .12 · รวมกันอธิบายได้ 63%",
                  "Loyalty β .49 · feelings about marketing β .30 · values β .12 · together explain 63%",
                  "แท่งกระดาษสามแท่งเรียงกัน สูง กลาง เตี้ย — ความภักดีนำ",
                  "exactly THREE upright paper columns standing in a row, descending in height from left to right: tall, medium, short. Three objects, nothing else."),
            scene("finding", 16,
                  "แล้วพอดูคำถามเรื่องความภักดีทีละข้อ ข้อที่ได้คะแนนต่ำสุดคือ จะซื้อแบรนด์นี้ต่อไหมถ้าราคาขึ้น ส่วนข้อที่ได้สูงสุด สี่จุดสี่ คือจะแนะนำให้คนอื่น สรุปคือ ยินดีเชียร์ให้คนอื่น แต่ไม่ยินดีจ่ายเพิ่มเอง และในเรื่องความตั้งใจซื้อ ข้อที่ต่ำสุดคือ จะซื้อไหมถ้าไม่มีขายใกล้ตัว",
                  "And look inside loyalty: the item that scored lowest was carrying on buying the brand if the price went up, while recommending it to others scored highest at four point four. Happy to cheer for it, not willing to pay more for it. And the lowest-scoring intention of all was buying it when it is not sold nearby.",
                  "ช่องว่างที่พบ", "The gap",
                  "บอกต่อ 4.40 สูงสุด · จ่ายแพงขึ้น ต่ำสุด · ซื้อแม้หาซื้อยาก 3.60",
                  "Recommend 4.40, highest · pay more, lowest · buy even if hard to find 3.60",
                  "ป้ายราคากระดาษหนึ่งใบ กับเหรียญกระดาษเล็กหนึ่งเหรียญวางข้างกัน — เชียร์ได้ แต่ไม่จ่ายเพิ่ม",
                  "ONE flat paper price tag (a rectangle with one corner cut off and a small round hole) and ONE small flat paper coin lying beside it. Two objects, nothing else."),
            scene("lesson", 22,
                  "บทเรียนสำหรับแบรนด์และคนทำแคมเปญก็คือ ค่านิยมพาคนมาถึงหน้าร้านได้ แต่พาไปไม่ถึงการจ่ายเงิน ถ้าราคาแพงกว่า แบรนด์ที่พูดแต่เรื่องคุณค่า จะได้เสียงเชียร์ที่ดัง แต่ยอดขายที่บาง ข้อมูลชุดเดียวกันบอกด้วยว่า คนชอบโปรโมชันมากที่สุด รองลงมาคือการประชาสัมพันธ์ที่ให้ความรู้ สองอย่างนี้จึงต้องไปด้วยกัน และต้องกระจายสินค้าให้หาซื้อได้ง่าย ข้อนี้ตัดออกไม่ได้เลย",
                  "The lesson for brands and campaigners is that values get people to the shelf, but they do not get them past a higher price. A brand that talks only about values earns loud cheering and thin sales. The same data shows promotions were the best-liked tool, with public relations that teaches something second, so the two have to work together. And getting the product within easy reach is not optional.",
                  "บทเรียน", "The lesson",
                  "ค่านิยมพามาถึงหน้าร้าน ไม่ถึงการจ่ายเงิน · โปรโมชันคู่กับการให้ความรู้ · ต้องหาซื้อได้สะดวก",
                  "Values bring people to the shelf, not past the price · promotion with education · keep it within reach",
                  "ตะกร้ากระดาษใบเล็กมีหูหิ้วโค้ง กับลูกบาศก์กระดาษเล็กหนึ่งก้อนอยู่ข้างใน — ถึงตะกร้าจริง",
                  "ONE small open paper basket (an open box with a paper handle arched over it) with ONE small paper cube resting inside it. Two objects, nothing else."),
            caveat("ข้อควรระวัง คนตอบเป็นผู้หญิงถึงแปดสิบห้าเปอร์เซ็นต์ ตัวเลขทั้งหมดจึงเล่าเรื่องของกลุ่มนี้เป็นหลัก สินค้าแบบนี้ในไทยส่วนใหญ่ก็คือเครื่องสำอางกับของใช้ส่วนตัว และที่วัดคือความตั้งใจซื้อที่คนบอกเอง ไม่ใช่ยอดขายจริง",
                   "One caution: eighty-five percent of the people surveyed were women, so the numbers mostly describe them. Cruelty-free products in Thailand are mostly cosmetics and personal care, and what was measured is what people said they would buy, not what they bought.",
                   "คนตอบเป็นหญิง 85% · ส่วนใหญ่เป็นเครื่องสำอาง · ความตั้งใจซื้อ ไม่ใช่ยอดขายจริง",
                   "85% women · mostly cosmetics · intentions, not purchases"),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "techno", "batch": 3,
        "slug": "first-year-online-learning-technostress",
        "name_th": "ความเครียดจากเทคโนโลยีของนิสิตปีหนึ่ง",
        "name_en": "Technostress among first-year students",
        "label": {"th": "งานวิจัย · การศึกษา", "en": "Research · Education"},
        "scenes": [
            scene("hook", 8,
                  "นิสิตปีหนึ่งที่ต้องย้ายมาเรียนออนไลน์กลางคัน เครียดกับเทคโนโลยีกันมาก … แต่ไม่ใช่เพราะมันใช้ยาก",
                  "First-year students who were pushed online halfway through the year found the technology stressful … but not because it was hard to use.",
                  "งานวิจัย · การศึกษา", "Research · Education",
                  "ความเครียดของนิสิตปีหนึ่ง ไม่ได้มาจากเทคโนโลยียาก แต่มาจากปริมาณ ที่ต้องรับมือพร้อมกัน",
                  "First-year stress did not come from technology being hard. It came from how much of it arrived at once",
                  "ภาพประจำบทความ (มีแล้ว): กองแผ่นบางซ้อนสูงจนทรุด ข้างแผ่นหนาแผ่นเดียวที่ตั้งมั่นคง — ปริมาณ ไม่ใช่ความยาก", None, image="existing"),
            scene("method", 20,
                  "ผู้วิจัยส่งแบบสอบถามออนไลน์สี่สิบห้าข้อ ให้นิสิตปีหนึ่งของมหาวิทยาลัยแห่งหนึ่ง แปดร้อยสามคน ในปีการศึกษาสองพันห้าร้อยหกสิบสาม ถามว่ารู้สึกอย่างไรกับการเรียนสองแบบ คือเรียนสด กับเรียนจากคลิปที่บันทึกไว้ และเครียดกับเทคโนโลยีด้านไหนบ้าง จากสี่ด้าน คืองานล้นมือ ระบบซับซ้อน ระบบไม่เสถียร และเทคโนโลยีที่เปลี่ยนบ่อยจนตามไม่ทัน แล้วเทียบนิสิตสายวิทย์กับสายอื่น",
                  "The researcher sent a forty-five-question online survey to eight hundred and three first-years at one university in the twenty twenty academic year, asking how they felt about two ways of learning, live classes and recorded material, and how much four kinds of technology stress affected them: too much to handle, systems that are complicated, systems that are unreliable, and technology that keeps changing. Then science students were compared with everyone else.",
                  "ทำอะไร", "What was done",
                  "นิสิตปีหนึ่ง 803 คน · เรียนสด กับ เรียนจากคลิป · ความเครียด 4 ด้าน · สายวิทย์ กับ สายอื่น",
                  "803 first-years · live vs recorded · four kinds of stress · science vs non-science",
                  "แล็ปท็อปกระดาษใบเล็ก ฐานแบนกับจอบางตั้งขึ้น — ห้องเรียนที่ย้ายมาอยู่บนจอ",
                  "ONE small paper laptop: a flat paper base with a thin paper screen hinged upright along its back edge. One object, nothing else."),
            scene("finding", 15,
                  "เรื่องงานล้นมือ เครียดสูงกว่าอีกสามด้านชัดเจน ทั้งสองกลุ่มเหมือนกัน สายวิทย์ได้สามจุดห้าสอง สายอื่นได้สามจุดหกสี่ จากห้า ส่วนเรื่องระบบซับซ้อน ระบบไม่เสถียร และเทคโนโลยีเปลี่ยนบ่อย อยู่แค่กลางค่อนไปทางต่ำทั้งหมด ราวสองจุดเจ็ดถึงสาม",
                  "Having too much to handle stood well above the other three in both groups: three point five two for science students and three point six four for the rest, out of five. Complicated systems, unreliable systems and constant change all sat in the middle-to-low range, around two point seven to three.",
                  "ด้านที่สูง", "The high one",
                  "งานล้นมือ 3.5–3.6 · ระบบซับซ้อน ระบบไม่เสถียร เทคโนโลยีเปลี่ยนบ่อย 2.7–3.0 (จาก 5)",
                  "Too much at once 3.5–3.6 · complicated, unreliable, changing 2.7–3.0 (out of 5)",
                  "แท่งกระดาษสี่แท่งเรียงกัน แท่งแรกสูง อีกสามแท่งเตี้ยเท่ากัน — ด้านเดียวที่โดดขึ้นมา",
                  "exactly FOUR upright paper columns standing in a row: the first tall, the other three short and equal in height. Four objects, nothing else."),
            scene("finding", 11,
                  "สายวิทย์กับสายอื่นต่างกันชัดแค่ด้านเดียว คือเรื่องเทคโนโลยีเปลี่ยนบ่อย ส่วนเรื่องระบบซับซ้อนกับระบบไม่เสถียร สองกลุ่มรู้สึกไม่ต่างกันเลย",
                  "The two groups differed clearly on just one kind of stress: technology that keeps changing. On complicated systems and unreliable systems there was no difference at all.",
                  "สองกลุ่มต่างกันไหม", "Did the groups differ",
                  "ต่างกันด้านเดียว คือเทคโนโลยีเปลี่ยนบ่อย · ระบบซับซ้อนกับระบบไม่เสถียร ไม่ต่าง",
                  "Differed on one thing only, constant change · no difference on complexity or reliability",
                  "วงกลมกระดาษสองวงขนาดเท่ากัน ซ้อนเหลื่อมกันเล็กน้อย — สองกลุ่มที่แทบเหมือนกัน",
                  "exactly TWO flat paper circles of identical size lying on the table and overlapping each other slightly. Two objects, nothing else."),
            scene("finding", 14,
                  "ส่วนความรู้สึกต่อการเรียน นิสิตสายอื่นมองบวกกว่าสายวิทย์ทั้งสองแบบ แต่ที่ต่างกันชัดจริง มีแค่แบบเรียนจากคลิปที่บันทึกไว้ และไม่ว่ากลุ่มไหน คะแนนความรู้สึกต่อการเรียนออนไลน์อยู่แค่ราวสามจากห้า คืออยู่ตรงกลางพอดี ไม่ได้ชอบ แต่ก็ไม่ได้เกลียด",
                  "As for the two ways of learning, non-science students felt better about both, but the gap was only clear for recorded material. And every group put online learning at around three out of five: right in the middle, neither liked nor disliked.",
                  "ชอบเรียนออนไลน์ไหม", "Did they like it",
                  "ความรู้สึกต่อการเรียนออนไลน์ ราว 3 จาก 5 ทุกกลุ่ม · สายอื่นชอบ เรียนจากคลิป มากกว่า",
                  "Online learning rated about 3 of 5 by every group · non-science preferred recorded material",
                  "วงแหวนกระดาษหนึ่งวง มีสามเหลี่ยมกระดาษเล็กอยู่ข้างใน — ปุ่มเล่นของบทเรียนที่บันทึกไว้",
                  "ONE flat paper ring lying on the table with ONE small paper triangle (a play symbol) resting inside it. Two objects, nothing else."),
            scene("lesson", 20,
                  "บทเรียนก็คือ ในเมื่อสิ่งที่สูงคือปริมาณ ส่วนความยากของระบบกลับต่ำ การจัดอบรมสอนใช้เครื่องมือจึงไม่ใช่คำตอบ สิ่งที่ต้องจัดการคือจำนวนแพลตฟอร์ม กับจำนวนงานที่กำหนดส่งพร้อมกันจากหลายวิชา ผู้วิจัยจึงเสนอให้ลดจำนวนระบบที่ใช้ในหลักสูตรเดียวกันลง และเพิ่มการเรียนจากคลิปที่บันทึกไว้ ให้นิสิตจัดจังหวะของตัวเองได้",
                  "The lesson: when the problem is how much, not how hard, running workshops on how to use the tools is not the answer. What needs managing is the number of platforms, and the number of deadlines landing at once from different courses. The researcher recommends fewer systems within a programme, and more recorded material, so students can set their own pace.",
                  "บทเรียน", "The lesson",
                  "อบรมใช้เครื่องมือ ไม่ใช่คำตอบ · ลดจำนวนระบบในหลักสูตร · เพิ่มการเรียนจากคลิป ให้จัดจังหวะเอง",
                  "Tool training is not the answer · fewer systems per programme · more recorded material, self-paced",
                  "ลูกบาศก์กระดาษใหญ่หนึ่งก้อน ข้างลูกบาศก์เล็กสามก้อนเรียงแถว — หลายระบบยุบเหลือหนึ่ง",
                  "ONE large paper cube standing beside exactly THREE much smaller paper cubes lined up in a row. Four objects, nothing else."),
            caveat("ข้อควรระวัง ข้อมูลมาจากมหาวิทยาลัยเดียว นิสิตรุ่นเดียว ในช่วงที่ทุกวิชาต้องย้ายไปออนไลน์ทั้งหมด และเป็นความรู้สึกที่นิสิตบอกเอง ไม่ได้วัดปริมาณงานจริง ผู้วิจัยจึงเสนอให้สัมภาษณ์เชิงลึกต่อ",
                   "One caution: this is one university and one year group, at a time when everything had gone online. It measures how students said they felt, not their actual workload, and the researcher suggests interviews as the next step.",
                   "มหาวิทยาลัยเดียว รุ่นเดียว · ช่วงเรียนออนไลน์ทั้งหมด · ความรู้สึกที่นิสิตบอกเอง ไม่ใช่ปริมาณงานจริง",
                   "One university, one cohort · fully online period · self-reported, not measured workload"),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "joox", "batch": 3,
        "slug": "joox-rooms-relational-bonds",
        "name_th": "ห้องไลฟ์ของแฟนเพลง รักศิลปินหรือรักแพลตฟอร์ม",
        "name_en": "Live rooms: loving the artist or the platform",
        "label": {"th": "งานวิจัย · สื่อบันเทิงและแพลตฟอร์ม", "en": "Research · Entertainment platforms"},
        "scenes": [
            scene("hook", 9,
                  "ห้องไลฟ์ที่แฟนเพลงได้คุยกับศิลปินแบบสด อะไรทำให้คนติดแพลตฟอร์ม … แล้วที่ติด เพราะรักศิลปิน หรือรักแอป",
                  "A live room where fans can talk to artists in real time. What keeps people hooked on the platform … and is it the artist they love, or the app?",
                  "งานวิจัย · สื่อบันเทิงและแพลตฟอร์ม", "Research · Entertainment platforms",
                  "แฟนเพลงแยกไม่ออก ว่ารักศิลปินหรือรักแพลตฟอร์ม และนั่นคือข้อค้นพบ ไม่ใช่ความบกพร่องของแบบวัด",
                  "Fans could not separate loving the artist from loving the platform. That is the finding, not a flaw in the instrument",
                  "ภาพประจำบทความ (มีแล้ว): รูปทรงมนสองรูปซ้อนกันเกือบสนิท — สองสิ่งที่แยกจากกันไม่ได้", None, image="existing"),
            scene("method", 19,
                  "ทีมวิจัยทำแบบสอบถามออนไลน์กับคนที่ใช้ห้องไลฟ์ จูกซ์ รูมส์ ในไทย ช่วงเมษายนถึงพฤษภาคมสองพันห้าร้อยหกสิบเจ็ด ได้คำตอบที่ใช้ได้หนึ่งร้อยเจ็ดสิบห้าคน แล้ววิเคราะห์ด้วยแบบจำลองทางสถิติ โดยแยกสิ่งที่ผูกคนไว้กับแพลตฟอร์มออกเป็นสามแบบ แบบแรกคือเรื่องเงิน เช่นส่วนลดกับเหรียญในแอป แบบที่สองคือเรื่องคน เช่นแชตสดกับการที่ศิลปินตอบกลับ และแบบที่สามคือเรื่องระบบ เช่นระบบใช้งานได้ลื่น และตอบคำถามอย่างมืออาชีพ",
                  "The research team surveyed people who use JOOX Rooms in Thailand in April and May twenty twenty-four, ending up with one hundred and seventy-five usable answers, and ran them through a statistical model that separates three kinds of bond: money, such as discounts and in-app coins; people, such as live chat and artists who reply; and the service itself, such as an app that works smoothly and answers questions professionally.",
                  "ทำอะไร", "What was done",
                  "ผู้ใช้ 175 คน · สิ่งที่ผูกคนไว้ 3 แบบ · เงิน คน ระบบ",
                  "175 users · three bonds · money, people, the service",
                  "ริบบิ้นกระดาษสามเส้นยาวเท่ากัน ผูกรวมปลายหนึ่งแล้วบานออก — สายสัมพันธ์สามแบบ",
                  "exactly THREE flat paper ribbons of equal length, joined together at one end in a small knot and fanning apart toward the other end. Three pieces, nothing else."),
            scene("finding", 14,
                  "ทั้งสามแบบทำให้คนรู้สึกผูกพันกับแพลตฟอร์มมากขึ้น และความผูกพันนั้นก็บอกได้ว่าเขาจะใช้ต่อและบอกต่อ แต่ไม่มีแบบไหนที่ทำให้คนใช้ต่อได้โดยตรง ทุกอย่างต้องผ่านความรู้สึกผูกพันก่อนทั้งนั้น",
                  "All three bonds made people feel more attached to the platform, and that attachment predicted whether they would keep using it and recommend it. But none of the three worked directly. Everything went through how people felt.",
                  "ผ่านความรู้สึกเท่านั้น", "Only through feeling",
                  "3 แบบ → ความผูกพัน → ใช้ต่อและบอกต่อ · ไม่มีทางลัด ที่ข้ามความรู้สึก",
                  "3 bonds → attachment → keep using and recommend · no shortcut past feeling",
                  "ลูกศรกระดาษสั้นสามอันชี้เข้าหาหัวใจกระดาษดวงเดียวตรงกลาง — ทุกทางผ่านความรู้สึก",
                  "exactly THREE short flat paper arrows pointing inward toward ONE paper heart shape at the centre. Four pieces in total, nothing else."),
            scene("finding", 18,
                  "แต่เรื่องที่น่าสนใจที่สุด กลับมาจากสิ่งที่ต้องตัดทิ้ง ความผูกพันกับศิลปิน กับความผูกพันกับแพลตฟอร์ม ไปด้วยกันแทบเป็นเส้นเดียว ค่าความสัมพันธ์สูงถึงจุดแปดเก้า จนแบบจำลองคำนวณไม่ออก ทีมวิจัยจึงต้องตัดเรื่องศิลปินออกไปทั้งก้อน สมมติฐานทุกข้อที่เกี่ยวกับศิลปิน จึงเป็นเรื่องที่ยังไม่ได้ทดสอบ ไม่ใช่ทดสอบแล้วไม่พบ",
                  "But the most interesting finding came from something that had to be thrown out. Attachment to the artists and attachment to the platform moved together so tightly, a correlation of point eight nine, that the model broke down. The team had to drop the artist measure altogether. So every hypothesis about artists is untested, not disproved.",
                  "ตัวแปรที่ต้องตัดทิ้ง", "The variable that had to go",
                  "ผูกพันกับศิลปิน กับ ผูกพันกับแพลตฟอร์ม สัมพันธ์กันสูงถึง .89 · แยกวัดไม่ได้ · ยังไม่ได้ทดสอบ ไม่ใช่ไม่พบ",
                  "Artist vs platform attachment r = .89 · could not be separated · untested, not disproved",
                  "วงกลมกระดาษสองวงซ้อนกันจนเกือบเป็นรูปเดียว — สองความรู้สึกที่แยกไม่ออก",
                  "exactly TWO flat paper circles lying on the table and overlapping so far that they almost form a single shape. Two objects, nothing else."),
            scene("finding", 14,
                  "และแต่ละแบบให้ความผูกพันคนละชนิด ส่วนลดให้ความผูกพันแบบแลกกัน แชตสดให้ความใกล้ชิด ระบบที่เสถียรให้ความไว้ใจ ถ้าเลือกทุ่มแต่เรื่องราคา ก็จะได้ยอดใช้งานช่วงสั้นที่ไม่มีอะไรลึก",
                  "And each bond gives a different kind of attachment. Discounts give you a deal, live chat gives closeness, a reliable service gives trust. Build on price alone and you get a burst of activity with nothing underneath.",
                  "สามชนิดของความผูกพัน", "Three kinds of attachment",
                  "ส่วนลด = แลกกัน · แชตสด = ใกล้ชิด · ระบบเสถียร = ไว้ใจ",
                  "Discounts = a deal · live chat = closeness · reliability = trust",
                  "เหรียญกระดาษ กรอบคำพูดกระดาษ และโล่กระดาษ วางเรียงกัน — สามชนิดของความผูกพัน",
                  "ONE small flat paper coin, ONE small flat paper speech bubble and ONE small flat paper shield lying in a row. Three objects, nothing else."),
            scene("lesson", 19,
                  "บทเรียนสำหรับแพลตฟอร์มและค่ายเพลงก็คือ ต้องลงทุนทั้งสามเรื่องไปพร้อมกัน และเรื่องที่ทำให้ต้องตัดข้อมูลศิลปินทิ้งนั่นแหละ กลับเป็นบทเรียนที่ใช้ได้จริงที่สุด ถ้าคนฟังแยกไม่ออกว่ารักศิลปินหรือรักแพลตฟอร์ม การย้ายไปแพลตฟอร์มอื่น ก็ไม่ใช่แค่โหลดแอปใหม่ แต่มีต้นทุนทางใจติดมาด้วย",
                  "The lesson for platforms and labels is to invest in all three at once. And the finding that broke the model is the most useful of all: if listeners cannot tell loving the artist apart from loving the platform, then switching platforms costs them something emotionally, not just the bother of installing another app.",
                  "บทเรียน", "The lesson",
                  "ลงทุนทั้ง 3 เรื่องพร้อมกัน · ย้ายแพลตฟอร์ม มีต้นทุนทางใจ ไม่ใช่แค่โหลดแอปใหม่",
                  "Invest in all three bonds · switching platforms costs feeling, not just an app install",
                  "หัวใจกระดาษหนึ่งดวง มีแม่กุญแจกระดาษเล็กวางอยู่บนนั้น — ความรู้สึกที่ล็อกไว้กับแพลตฟอร์ม",
                  "ONE flat paper heart shape lying on the table with ONE small paper padlock resting on top of it. Two objects, nothing else."),
            caveat("ข้อควรระวัง คนตอบมาจากการบอกต่อกัน จึงเอนไปทางคนที่ติดแพลตฟอร์มอยู่แล้ว วัดแค่ครั้งเดียว จึงบอกไม่ได้ว่าอะไรเกิดก่อนเกิดหลัง และเก็บจากแพลตฟอร์มเดียวในประเทศเดียว ที่สำคัญ งานนี้ไม่ได้บอกว่าศิลปินไม่สำคัญ แต่บอกว่าแบบวัดชุดนี้ แยกศิลปินออกจากแพลตฟอร์มไม่ได้",
                   "One caution: the people surveyed were recruited through word of mouth, which tilts the sample toward people who were already hooked; a single survey cannot say what came first; and it covers one platform in one country. The study does not say artists do not matter. It says this set of questions could not tell them apart from the platform.",
                   "เอนไปทางคนที่ติดอยู่แล้ว · วัดครั้งเดียว · แพลตฟอร์มเดียว · ไม่ได้แปลว่า ศิลปินไม่สำคัญ",
                   "Skewed to engaged users · one survey · one platform · not that artists do not matter", secs=(11, 11)),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "vtuber", "batch": 3,
        "slug": "vtuber-streamer-purchase-intention",
        "name_th": "วีทูปเบอร์ สตรีมเมอร์ และความน่าเชื่อถือ",
        "name_en": "VTubers, streamers and credibility",
        "label": {"th": "งานวิจัย · การตลาดอินฟลูเอนเซอร์", "en": "Research · Influencer marketing"},
        "scenes": [
            scene("hook", 8,
                  "อินฟลูเอนเซอร์สายเกมสองแบบ ตัวละครเสมือน กับคนจริง … อะไรทำให้ผู้ชมอยากซื้อของที่เขาแนะนำ",
                  "Two kinds of gaming influencer, a virtual character and a real person … what makes viewers want to buy what they recommend?",
                  "งานวิจัย · การตลาดอินฟลูเอนเซอร์", "Research · Influencer marketing",
                  "ความน่าเชื่อถือคนละแบบ ได้ผลกับคนละกลุ่ม ความรู้จริงขายของให้แฟนตัวจริง หน้าตาขายให้คนทั่วไป",
                  "Different kinds of credibility work on different audiences. Expertise sells to true fans, looks sell to everyone else",
                  "ภาพประจำบทความ (มีแล้ว): ตาชั่งสองอัน ลูกบาศก์กับลูกกลมเอียงคนละทาง — น้ำหนักที่ต่างกันตามกลุ่ม", None, image="existing"),
            scene("method", 19,
                  "ทีมวิจัยทำแบบสอบถามออนไลน์กับผู้หญิงไทยที่เล่นเกม หกร้อยแปดสิบหกคน ทุกคนติดตามอินฟลูเอนเซอร์สายเกมผู้หญิงอย่างน้อยหนึ่งคน และในนี้มีหนึ่งร้อยห้าคนที่บอกว่าตัวเองเป็นโอตาคุ ทีมวิจัยให้ดูอินฟลูเอนเซอร์ที่มีอยู่จริงสองคน คนหนึ่งเป็นวีทูปเบอร์ คือตัวละครเสมือน อีกคนเป็นสตรีมเมอร์ที่เป็นคนจริง แล้วให้คะแนนความน่าเชื่อถือสามด้าน คือรู้จริง หน้าตาน่าดึงดูด และไว้ใจได้",
                  "The research team surveyed six hundred and eighty-six Thai women gamers who each follow at least one female gaming influencer; one hundred and five of them described themselves as otaku. Everyone was shown two actual influencers: a VTuber, which is a virtual character, and a streamer, who is a real person. They rated each on three things: how expert they seemed, how attractive, and how trustworthy.",
                  "ทำอะไร", "What was done",
                  "ผู้หญิงที่เล่นเกม 686 คน · โอตาคุ 105 คน · วีทูปเบอร์ กับ สตรีมเมอร์ · ความน่าเชื่อถือ 3 ด้าน",
                  "686 women gamers · 105 otaku · VTuber vs streamer · three kinds of credibility",
                  "จอยเกมกระดาษแบนหนึ่งอัน มีปุ่มกลมเล็กสองปุ่ม — ผู้ชมสายเกม",
                  "ONE flat paper game controller shape (a rounded rectangle with two small round paper buttons on its right side) lying on the table. One object, nothing else."),
            scene("finding", 12,
                  "ถ้าดูรวมทั้งสองแบบ ทั้งสามด้านล้วนบอกได้ว่าคนจะซื้อ รู้จริงมาก่อน ตามด้วยไว้ใจได้ และหน้าตา แต่พอแยกดูทีละแบบ ภาพกลับคนละเรื่อง",
                  "Taken together, all three predicted whether viewers would buy: expertise first, then trust, then looks. But split the two influencers apart, and the picture changed completely.",
                  "ภาพรวม", "Overall",
                  "รวมสองแบบ บอกได้ทั้ง 3 ด้าน · รู้จริง .33 · ไว้ใจได้ .24 · หน้าตา .19",
                  "Combined, all three predict · expertise .33 · trust .24 · looks .19",
                  "วงกลมกระดาษสามวงขนาดลดหลั่นเรียงแถว — สามด้านที่มีน้ำหนักต่างกัน",
                  "exactly THREE flat paper circles of decreasing size lying in a row from large to small. Three objects, nothing else."),
            scene("finding", 16,
                  "กับวีทูปเบอร์ สิ่งที่ทำให้คนซื้อคือความรู้จริงกับความไว้ใจได้ ส่วนหน้าตาไม่มีผล แต่กับสตรีมเมอร์กลับตรงกันข้าม สิ่งที่ทำให้คนซื้อคือความไว้ใจได้กับหน้าตา ส่วนความรู้จริงไม่มีผลเลย",
                  "For the VTuber, what drove buying was expertise and trust, and looks made no difference. For the streamer it was the other way round: trust and looks drove buying, and expertise made no difference at all.",
                  "ตัวละครเสมือน กับ คนจริง", "Virtual vs real",
                  "วีทูปเบอร์: รู้จริง .42 ไว้ใจได้ .26 · สตรีมเมอร์: ไว้ใจได้ .44 หน้าตา .23",
                  "VTuber: expertise .42, trust .26 · streamer: trust .44, looks .23",
                  "ลูกบาศก์กระดาษกับลูกกลมกระดาษขนาดเท่ากันวางคู่กัน — ตัวละครเสมือนกับคนจริง",
                  "ONE small paper cube and ONE paper sphere of the same size standing side by side with a small gap between them. Two objects, nothing else."),
            scene("finding", 15,
                  "กลุ่มโอตาคุให้คะแนนความรู้จริงสูงกว่า และอยากซื้อมากกว่าคนกลุ่มอื่นชัดเจน กลุ่มนี้ ความรู้จริงสำคัญที่สุด ส่วนคนที่ไม่ใช่โอตาคุ หน้าตาสำคัญที่สุด และความไว้ใจได้กลับไม่มีผล",
                  "Otaku viewers rated expertise higher and were clearly keener to buy than everyone else. For them, expertise came first. For viewers who were not otaku, looks came first, and trust made no difference.",
                  "แฟนตัวจริง กับ คนทั่วไป", "True fans vs everyone else",
                  "โอตาคุ: รู้จริงมาก่อน · ไม่ใช่โอตาคุ: หน้าตามาก่อน ไว้ใจได้ไม่มีผล",
                  "Otaku: expertise first · non-otaku: looks first, trust no effect",
                  "ดาวกระดาษหนึ่งดวงกับหัวใจกระดาษหนึ่งดวงวางคู่กัน — ฝีมือกับความชอบ",
                  "ONE flat paper star shape and ONE flat paper heart shape lying side by side. Two objects, nothing else."),
            scene("lesson", 19,
                  "บทเรียนสำหรับแบรนด์ก็คือ เอาข้อค้นพบนี้ไปใช้เลือกคน และเลือกวิธีพูดให้ตรงกลุ่ม ถ้ากลุ่มเป้าหมายเป็นแฟนตัวจริงของเรื่องนั้น สิ่งที่ต้องพิสูจน์คือรู้จริง ไม่ใช่ภาพลักษณ์ เนื้อหาจึงต้องให้เห็นฝีมือ และเห็นว่าเข้าใจสินค้าจริง แต่ถ้าเป็นคนดูทั่วไป ความชอบและความคุ้นเคยมีผลมากกว่า",
                  "The lesson for brands is to use this to pick the right person and the right pitch. If your audience are true fans of the category, what you have to prove is real knowledge, not image, so the content should show skill and a real grasp of the product. If your audience is the general public, being liked and being familiar do more of the work.",
                  "บทเรียน", "The lesson",
                  "แฟนตัวจริง: พิสูจน์ว่ารู้จริง ไม่ใช่ภาพลักษณ์ · คนทั่วไป: ความชอบและความคุ้นเคย",
                  "True fans: prove real knowledge, not image · general audience: liking and familiarity",
                  "ถ้วยรางวัลกระดาษใบเล็กมีหูสองข้างตั้งอยู่ — ฝีมือที่พิสูจน์ได้",
                  "ONE small paper trophy cup with two small paper handles, standing upright on a short paper base. One object, nothing else."),
            caveat("ข้อควรระวัง คนตอบเป็นผู้หญิงไทยที่เล่นเกมเท่านั้น กลุ่มโอตาคุมีแค่หนึ่งร้อยห้าคน เทียบกับอีกกลุ่มห้าร้อยแปดสิบเอ็ดคน ให้ดูอินฟลูเอนเซอร์แค่สองคน และที่วัดคือความตั้งใจซื้อที่คนบอกเอง ไม่ใช่การซื้อจริง",
                   "One caution: everyone surveyed was a Thai woman who plays games; the otaku group was just one hundred and five people against five hundred and eighty-one; viewers saw only two influencers; and what was measured is what people said they would buy, not what they bought.",
                   "ผู้หญิงไทยที่เล่นเกมเท่านั้น · โอตาคุ 105 คน กับ 581 คน · ให้ดูแค่ 2 คน · ความตั้งใจ ไม่ใช่การซื้อจริง",
                   "Thai women gamers only · 105 otaku vs 581 · two influencers shown · intentions, not purchases", secs=(11, 11)),
            closing(),
        ],
    },
]
