"""สตอรี่บอร์ดชุดที่ 5 — 5 เรื่อง × ไทย/อังกฤษ (5 ก.ย. 2569) — storyboard.py นำเข้าไฟล์นี้แล้วต่อท้าย CLIPS/PALETTE

กติกาเดียวกับชุดที่ 2–4 (ดูหัวไฟล์ storyboard_batch2.py · บทพากย์เป็นภาษาพูด ผ่าน check_narration.py ก่อนอัด) · ข้อเพิ่มของชุดนี้:
  · เลือกจากงานเชิงประจักษ์ที่เหลือซึ่งทะเบียนมี citation ครบ — ผู้ใช้เลือกทาง "ทำจาก 5 เรื่องที่พร้อม" (5 ก.ย.)
    สามเรื่องแรกเป็นชุดงานสื่อสารเอชไอวีกับแรงงานเมียนมาของทีมเดียวกัน (2560 → 2562 → 2565) จึงเรียงตามลำดับเวลาให้เล่าต่อกันได้
  · เอชไอวี: เล่าเป็นเรื่องการสื่อสารสุขภาพ ไม่เล่าพฤติกรรมเสี่ยงของบุคคล · ไม่ระบุชื่อโรงงาน · "กรมควบคุมโรค" เอ่ยได้เพราะเป็นขอบเขตของงาน
    (ข้อยกเว้นของกติกาข้อ 5 แบบเดียวกับชุดที่ 4) ข้อค้นพบเรื่องทัศนคติของเจ้าหน้าที่เล่าตามที่บทความเขียน โดยชี้ไปที่โครงสร้าง (ไม่มีใครถูกกำหนดให้ทำ)
  · อินฟลูเอนเซอร์เกม: ชื่อยูทูบเบอร์ขึ้นบนจอและในบทอังกฤษเพราะเป็นขอบเขตของงาน บทไทยเรียก "ยูทูบเบอร์สายเกมรายใหญ่ระดับโลกคนหนึ่ง"
    เพราะการอ่านชื่อทับศัพท์ด้วยเสียงไทยเสี่ยงเพี้ยน · ข้อควรระวังบอกว่าบทความไม่ได้วิจารณ์ตัวเขา
  · คริปโต: **บทคัดย่อของบทความขัดกับตารางผลและบทสรุปของบทความเอง** (บทคัดย่อ: ความเสี่ยงมีผลลบ + ประชากรศาสตร์เป็นตัวปรับ ·
    ตารางผล: ความเสี่ยงไม่มีผล t = 1.28 p = .20 · มีแค่การศึกษาที่มีผล) คลิปยึดตารางผลและบอกความขัดแย้งในข้อควรระวัง
    บทสรุปบนเว็บเดิมเขียนตามบทคัดย่อ → แก้ paperSummaries.ts ให้ตรงกับตารางผลในคอมมิตแยก (กติกา: บทความขัดกันเองให้เขียนบอก ไม่เลือกข้างเงียบๆ)
  · ภาพ: ทุกฉากนับวัตถุไม่เกินสี่ชิ้น · หกขั้นของ ENGAGE-A3 ใช้กระดาษพับซิกแซกชิ้นเดียวแทนการนับหกชิ้น (บทเรียน #46)
"""
from storyboard_batch2 import CLOSING2, ASTERISK

CLOSING5 = CLOSING2

# คู่สีอ่านจากภาพประจำบทความของแต่ละเรื่อง (นับพิกเซลที่อิ่มสีของไฟล์ -800.webp) เพื่อให้ภาพใหม่กลมกลืนกับภาพ hook
PALETTE5 = {
    "engage": {"object": "deep raspberry pink", "shadow": "warm khaki", "obj_hex": "#A23056", "sh_hex": "#A08B6C",
               "shadow_style": "clean flat-edged shadows to the lower right rendered as solid warm-khaki shapes, like cut paper rather than soft photographic shadows"},
    "samut": {"object": "dusty steel blue", "shadow": "olive yellow", "obj_hex": "#6290B0", "sh_hex": "#949661",
              "shadow_style": "clean flat-edged shadows to the lower right rendered as solid olive-yellow shapes, like cut paper rather than soft photographic shadows"},
    "officers": {"object": "rose pink", "shadow": "soft dusty rose-grey", "obj_hex": "#BA426C", "sh_hex": "#A8808A",
                 "shadow_style": "soft dusty rose-grey shadows to the lower right, as in a real studio photograph of paper on a table"},
    "gameinf": {"object": "warm coral", "shadow": "deep teal", "obj_hex": "#E27C6F", "sh_hex": "#245258",
                "shadow_style": "clean flat-edged shadows to the lower right rendered as solid deep-teal shapes, like cut paper rather than soft photographic shadows"},
    "crypto": {"object": "deep raspberry", "shadow": "light sky blue", "obj_hex": "#B24570", "sh_hex": "#8BB7DA",
               "shadow_style": "clean flat-edged shadows to the lower right rendered as solid light-sky-blue shapes, like cut paper rather than soft photographic shadows"},
}


def closing():
    return {"role": "closing", "secs": (14, 14), "image": "logo", "narr": CLOSING5, "label": None, "text": None,
            "visual_th": "การ์ดปิดประจำชุด + ชื่อผู้เขียนทุกคน (ไม่ต้องเจนภาพ)", "subject": None}


def caveat(narr_th, narr_en, text_th, text_en, secs=(10, 10)):
    return {"role": "caveat", "secs": secs, "image": "new", "narr": {"th": narr_th, "en": narr_en},
            "label": {"th": "ข้อควรระวัง", "en": "One caution"}, "text": {"th": text_th, "en": text_en},
            "visual_th": "ดอกจันกระดาษพับหนึ่งดอก — สัญลักษณ์ประจำฉากข้อควรระวัง (คู่สีของคลิปนี้)", "subject": ASTERISK}


def scene(role, secs, narr_th, narr_en, label_th, label_en, text_th, text_en, visual_th, subject, image="new"):
    return {"role": role, "secs": (secs, secs), "image": image, "narr": {"th": narr_th, "en": narr_en},
            "label": {"th": label_th, "en": label_en}, "text": {"th": text_th, "en": text_en},
            "visual_th": visual_th, "subject": subject}


CLIPS5 = [
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "officers", "batch": 5,
        "slug": "hiv-knowledge-public-health-officers",
        "name_th": "เจ้าหน้าที่สาธารณสุขกับความรู้เอชไอวีสำหรับแรงงานเมียนมา",
        "name_en": "Health officers and HIV knowledge for Myanmar migrants",
        "label": {"th": "งานวิจัย · สื่อสารสุขภาพ", "en": "Research · Health communication"},
        "scenes": [
            scene("hook", 9,
                  "ความรู้เรื่องเอชไอวีเดินทางจากระบบสาธารณสุขไทย ไปถึงแรงงานเมียนมาได้แค่ไหน … ทีมวิจัยไปถามคนส่งสาร แล้วพบว่าปัญหาไม่ได้อยู่ที่ตัวสื่อเลย",
                  "How far does HIV knowledge travel from the Thai health system to Myanmar migrant workers? … The research team asked the people who send it, and found the problem was never the materials.",
                  "งานวิจัย · สื่อสารสุขภาพ", "Research · Health communication",
                  "ปัญหาไม่ได้อยู่ที่สื่อไม่ดีพอ แต่อยู่ที่ไม่มีใครมีหน้าที่ต้องทำ",
                  "The gap is not weak materials. Nobody was assigned the job",
                  "ภาพประจำบทความ (มีแล้ว): ฟันเฟืองเรียงขบกัน โดยมีช่องหนึ่งว่างอยู่ — ระบบที่ขาดชิ้นส่วนหนึ่ง", None, image="existing"),
            scene("method", 16,
                  "ทีมวิจัยส่งแบบสอบถามถึงเจ้าหน้าที่สาธารณสุขที่รับผิดชอบงานสื่อสารความเสี่ยงของกรมควบคุมโรคทั่วประเทศ ได้กลับมาหนึ่งร้อยหกคน เป็นหญิงหกสิบหกคน ชายสี่สิบคน เกือบครึ่งทำงานมาไม่ถึงห้าปี ถามว่าในรอบปีที่ผ่านมาได้สื่อสารเรื่องเอชไอวีกับแรงงานเมียนมาบ่อยแค่ไหน ติดตรงไหน และคิดว่าช่องทางไหนจะได้ผล",
                  "The research team sent a questionnaire to the public health officers responsible for risk communication at the Department of Disease Control across the country, and got one hundred and six back: sixty-six women and forty men, nearly half with under five years in the job. It asked how often in the past year they had communicated about HIV with Myanmar migrants, where they got stuck, and which channels they thought would work.",
                  "ทำอะไร", "What was done",
                  "เจ้าหน้าที่ 106 คน · หญิง 66 คน ชาย 40 คน · เกือบครึ่ง ทำงานไม่ถึง 5 ปี",
                  "106 officers · 66 women · 40 men · nearly half under five years in the job",
                  "แฟ้มกระดาษหนึ่งแฟ้มวางเปิดแง้ม มีกระดาษหนึ่งแผ่นโผล่ออกมา — แบบสอบถามที่ส่งกลับมา",
                  "ONE flat paper folder lying slightly open with ONE plain sheet of paper peeking out of it. Two objects, nothing else."),
            scene("finding", 15,
                  "ในรอบสิบสองเดือน เจ้าหน้าที่เจ็ดสิบเจ็ดเปอร์เซ็นต์ ไม่เคยสื่อสารเรื่องเอชไอวีกับแรงงานเมียนมาเลยแม้แต่ครั้งเดียว ที่ทำหนึ่งครั้งมีไม่ถึงหกเปอร์เซ็นต์ และทีมวิจัยไม่พบข้อกำหนดใดจากภาครัฐ ที่บอกว่าการให้ความรู้กับแรงงานกลุ่มนี้เป็นหน้าที่ของใคร",
                  "In the past twelve months, seventy-seven percent of the officers had not communicated about HIV with Myanmar migrants even once. Fewer than six percent had done it once. And the team found no government mandate saying whose job it was to educate this group at all.",
                  "ไม่มีใครมีหน้าที่", "Nobody's job",
                  "ไม่เคยติดต่อในรอบปี 77% · ทำครั้งเดียว 6% · ไม่มีข้อกำหนดว่าเป็นหน้าที่ของใคร",
                  "No contact in a year 77% · once 6% · no mandate naming whose job it is",
                  "หน้าปฏิทินกระดาษหนึ่งแผ่น ตารางว่างเปล่าไม่มีเครื่องหมายใด — ปีที่ไม่มีอะไรเกิดขึ้น",
                  "ONE flat paper calendar page with an empty grid of small squares and no marks on it. One object, nothing else."),
            scene("finding", 16,
                  "แล้วติดตรงไหน สิ่งที่เจ้าหน้าที่บอกว่าเป็นอุปสรรคมากที่สุดคือภาษา พูดภาษาเมียนมาไม่ได้ และไม่มีช่องทางสื่อที่เหมาะกับแรงงานกลุ่มนี้ ส่วนคนที่เคยทำงานกับล่ามมาแล้ว ราวครึ่งหนึ่งบอกว่ามีปัญหา และเกือบหนึ่งในสามยอมรับว่า ในลำดับความสำคัญของงาน แรงงานเมียนมาถูกมองเป็นกลุ่มเป้าหมายที่สำคัญน้อยกว่าแรงงานไทย",
                  "So where do they get stuck? The obstacle officers rated highest was language: not being able to speak Myanmar, and having no channel suited to this group. Of those who had worked with interpreters, about half reported problems. And nearly a third admitted that, in the pecking order of the work, Myanmar migrants were treated as a less important target than Thai workers.",
                  "ติดตรงไหน", "Where it sticks",
                  "ติดที่ภาษา · ไม่มีช่องทางที่เหมาะ · ล่ามมีปัญหาราวครึ่ง · เกือบ 1 ใน 3 มองว่าสำคัญน้อยกว่า",
                  "Language · no fitting channel · interpreter trouble for half · nearly 1 in 3 saw them as lower priority",
                  "ลูกโป่งคำพูดกระดาษสองอันหันหากัน ว่างเปล่าทั้งคู่ — บทสนทนาที่ไม่เกิด",
                  "exactly TWO flat paper speech bubbles facing each other with a small gap between them, both empty. Two objects, nothing else."),
            scene("finding", 16,
                  "และเมื่อถามว่าถ้าจะทำ ควรทำอย่างไร คำตอบชัดที่สุดคือ อบรมเป็นกลุ่มที่โรงงาน หกสิบเก้าเปอร์เซ็นต์ รองลงมาคือโปสเตอร์ หกสิบหกเปอร์เซ็นต์ เสียงตามสายในโรงงาน ห้าสิบแปดเปอร์เซ็นต์ และใบปลิว ห้าสิบเจ็ดเปอร์เซ็นต์ ส่วนโซเชียลมีเดียได้แค่ยี่สิบเปอร์เซ็นต์ และเรื่องที่ควรสอนก่อนคือสาเหตุกับการแพร่เชื้อ แล้วค่อยเรื่องการป้องกัน",
                  "And asked how it should be done, the clearest answer was group training at the factory, at sixty-nine percent, then posters at sixty-six, announcements over the factory loudspeakers at fifty-eight, and flyers at fifty-seven. Social media got only twenty percent. And the topic to teach first was how the virus is caught and spread, then prevention.",
                  "ถ้าจะทำ ควรทำอย่างไร", "How it should be done",
                  "อบรมกลุ่มที่โรงงาน 69% · โปสเตอร์ 66% · เสียงตามสาย 58% · ใบปลิว 57% · โซเชียล 20%",
                  "Group training at the factory 69% · posters 66% · loudspeakers 58% · flyers 57% · social media 20%",
                  "โปสเตอร์กระดาษหนึ่งแผ่น มีหมุดกระดาษกลมหนึ่งอันที่ขอบบน — ช่องทางที่เจ้าหน้าที่เลือก",
                  "ONE flat rectangular paper poster, blank, with ONE small round paper pin at the middle of its top edge. Two objects, nothing else."),
            scene("lesson", 23,
                  "บทเรียนสำหรับคนวางระบบสื่อสารสุขภาพก็คือ ข้อสรุปของงานนี้ชี้ไปที่โครงสร้าง ไม่ใช่ที่ตัวสื่อ เมื่อไม่มีคำสั่งหรือภารกิจที่ระบุชัดว่าใครรับผิดชอบ งานก็ไม่เกิดขึ้น แม้จะมีคนพร้อมทำ และช่องทางที่เจ้าหน้าที่เลือก ก็ตรงกับที่แรงงานเลือกเองในงานอื่นของทีมเดียวกัน คือการอบรมกลุ่มในที่ทำงาน กับโปสเตอร์และใบปลิวประกอบ ทีมวิจัยจึงเสนอสองอย่าง กำหนดหน้าที่ให้ชัด และอบรมแรงงานเมียนมาเองให้เป็นคนสื่อสารกับเพื่อนร่วมชาติ ซึ่งข้ามกำแพงภาษาได้ในตัว",
                  "The lesson for anyone building a health communication system is that this study points at structure, not at materials. With no order or mission naming who is responsible, the work does not happen even where willing people exist. And the channels the officers chose match what the workers themselves chose in the same team's other work: group training in the workplace, with posters and flyers alongside. So the team proposes two things. Name whose job it is, and train Myanmar workers themselves to communicate with their own people, which crosses the language barrier by itself.",
                  "บทเรียน", "The lesson",
                  "กำหนดให้ชัดว่าเป็นหน้าที่ของใคร · อบรมกลุ่มในที่ทำงาน · ให้แรงงานเมียนมาเป็นคนสื่อสารเอง",
                  "Name whose job it is · group training at work · let Myanmar workers carry the message",
                  "ป้ายชื่อกระดาษหนึ่งใบ มีคลิปหนีบกระดาษเล็กอยู่ด้านบน — งานที่มีเจ้าของ",
                  "ONE flat rectangular paper name badge, blank, with ONE small paper clip at the middle of its top edge. Two objects, nothing else."),
            caveat("ข้อควรระวัง สำรวจเจ้าหน้าที่จากหน่วยงานเดียวในปีสองพันห้าร้อยหกสิบ ข้อมูลเกี่ยวกับตัวแรงงานในงานนี้มาจากมุมมองของเจ้าหน้าที่ ไม่ได้ถามแรงงานโดยตรง และคำถามเรื่องงบประมาณกับการอนุมัติโครงการ มีเจ้าหน้าที่หนึ่งในสี่เลือกไม่ตอบ",
                   "One caution: this is a survey of officers at a single agency in twenty seventeen. What it says about the migrants comes from the officers' point of view, not from migrants themselves. And on the questions about budget and project approval, one officer in four chose not to answer.",
                   "หน่วยงานเดียว ปี 2560 · มุมมองของเจ้าหน้าที่ ไม่ได้ถามแรงงาน · คำถามเรื่องงบ 1 ใน 4 ไม่ตอบ",
                   "One agency, 2017 · officers' view, not migrants' · 1 in 4 skipped the budget questions", secs=(11, 11)),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "samut", "batch": 5,
        "slug": "hiv-risk-communication-samut-sakhon",
        "name_th": "แคมเปญเอชไอวีที่แรงงานเมียนมาออกแบบเอง",
        "name_en": "An HIV campaign the Myanmar workers designed themselves",
        "label": {"th": "งานวิจัย · สื่อสารความเสี่ยง", "en": "Research · Risk communication"},
        "scenes": [
            scene("hook", 9,
                  "ให้แรงงานข้ามชาติออกแบบแคมเปญเอชไอวีเอง … ความรู้กับความมั่นใจเพิ่มขึ้นจริง แต่มีอย่างหนึ่งที่ไม่ขยับเลย",
                  "Let migrant workers design an HIV campaign themselves … knowledge and confidence really did rise. But one thing did not move at all.",
                  "งานวิจัย · สื่อสารความเสี่ยง", "Research · Risk communication",
                  "ความรู้ขึ้น ความมั่นใจขึ้น แต่ความรู้สึกว่าตัวเองเสี่ยง ไม่ขยับ",
                  "Knowledge up, confidence up, but the sense of personal risk did not move",
                  "ภาพประจำบทความ (มีแล้ว): แท่งสองแท่งสูงขึ้น ส่วนแท่งที่สามยังราบอยู่กับพื้น", None, image="existing"),
            scene("method", 18,
                  "ทีมวิจัยเริ่มจากสนทนากลุ่มกับแรงงานเมียนมาสิบหกคนในโรงงานแห่งหนึ่งที่สมุทรสาคร และสัมภาษณ์เจ้าหน้าที่รัฐกับองค์กรพัฒนาเอกชนที่ดูแลงานป้องกันเอชไอวีอีกสิบคน แล้วคัดแรงงานในโรงงานมาเป็นอาสาสมัครสาธารณสุข ให้เป็นคนจัดงานเองทั้งหมด ทั้งซุ้มเกม สาธิตการใช้ถุงยาง โปสเตอร์ เสียงตามสาย และเพจเฟซบุ๊ก แคมเปญกินเวลาสองสัปดาห์ เริ่มวันถุงยางอนามัยสากลปีสองพันห้าร้อยหกสิบ แล้ววัดผลกับแรงงานสองร้อยคน ก่อน หลัง และอีกสองสัปดาห์ถัดมา",
                  "The research team began with focus groups of sixteen Myanmar workers at one factory in Samut Sakhon, and interviews with ten government and NGO officers responsible for HIV prevention. Then they recruited workers from the factory as health volunteers and let them run the whole campaign themselves: game booths, condom demonstrations, posters, announcements over the factory loudspeakers, and a Facebook page. It ran for two weeks from International Condom Day in twenty seventeen, and the team measured two hundred workers before, after, and two weeks later.",
                  "ทำอะไร", "What was done",
                  "กลุ่มย่อย 16 คน · สัมภาษณ์ 10 คน · อาสาสมัครคือแรงงานเอง · 2 สัปดาห์ · วัดผล 200 คน 3 ครั้ง",
                  "Focus groups of 16 · 10 interviews · volunteers from the workers · two weeks · 200 workers measured three times",
                  "เสื้อยืดกระดาษพับหนึ่งตัววางแบน — อาสาสมัครขอเสื้อทีมใส่จัดงาน",
                  "ONE small folded paper T-shirt lying flat, seen from directly above. One object, nothing else."),
            scene("finding", 17,
                  "คะแนนความรู้เรื่องเอชไอวีเพิ่มเกือบเท่าตัว จากสี่จุดศูนย์เจ็ด เป็นเจ็ดจุดเก้าสี่ และสองสัปดาห์ต่อมายังอยู่ที่เจ็ดจุดหกเจ็ด ความมั่นใจว่าตัวเองป้องกันได้ก็เพิ่มขึ้นชัด และแหล่งที่แรงงานบอกว่าได้ความรู้มากที่สุด ไม่ใช่โปสเตอร์หรือเฟซบุ๊ก แต่คืออาสาสมัครที่เป็นเพื่อนร่วมโรงงาน ครึ่งหนึ่งของคนตอบชี้ไปที่คนกลุ่มนี้",
                  "Knowledge scores nearly doubled, from four point oh seven to seven point nine four, and two weeks later they were still at seven point six seven. Confidence in being able to protect themselves rose clearly too. And the source workers said they learned most from was not the posters or the Facebook page. It was the volunteers, their own co-workers: half of the people surveyed pointed to them.",
                  "ความรู้และความมั่นใจ", "Knowledge and confidence",
                  "ความรู้ 4.07 → 7.94 · สองสัปดาห์ต่อมา 7.67 · แหล่งความรู้อันดับหนึ่ง คือเพื่อนร่วมโรงงาน 50%",
                  "Knowledge 4.07 → 7.94 · still 7.67 two weeks on · top source: co-workers, 50%",
                  "ลูกศรกระดาษหนึ่งอันชี้ขึ้นชัน — ความรู้ที่เพิ่มเกือบเท่าตัว",
                  "ONE flat paper arrow pointing up and to the right at a steep angle, lying on the surface. One object, nothing else."),
            scene("finding", 16,
                  "ขั้นของการเปลี่ยนพฤติกรรมก็ขยับ ทั้งเรื่องการใช้ถุงยาง จากสองจุดสี่ห้า เป็นสองจุดแปดห้า และเรื่องการไปตรวจเอชไอวี และคนมองเห็นประโยชน์ของการป้องกันมากขึ้น แต่ที่น่าสนใจคือ คะแนนอุปสรรคที่คนรับรู้ ก็เพิ่มขึ้นด้วย จากหนึ่งจุดเก้าเก้า เป็นสองจุดห้าหก ทีมวิจัยอ่านว่า พอรู้มากขึ้น คนก็เห็นชัดขึ้นว่าอะไรขวางอยู่บ้าง",
                  "Behaviour moved too. On condom use the stage of change rose from two point four five to two point eight five, HIV testing moved as well, and people saw more benefit in protecting themselves. But here is the interesting part: the barriers people perceived rose too, from one point nine nine to two point five six. The team's reading is that once people know more, they also see more clearly what stands in their way.",
                  "พฤติกรรมและอุปสรรค", "Behaviour and barriers",
                  "ถุงยาง 2.45 → 2.85 · ตรวจเอชไอวีขยับ · เห็นประโยชน์มากขึ้น · อุปสรรคก็ชัดขึ้น 1.99 → 2.56",
                  "Condom use 2.45 → 2.85 · testing moved · more benefit seen · but barriers seen more clearly too, 1.99 → 2.56",
                  "รั้วกระโดดกระดาษเตี้ยหนึ่งอัน กับลูกศรกระดาษโค้งข้ามไป — เห็นอุปสรรคชัด แต่ข้ามได้",
                  "ONE small paper hurdle made of two short posts and a crossbar, and ONE curved paper arrow arching over it. Two objects, nothing else."),
            scene("finding", 16,
                  "แต่สิ่งเดียวที่ไม่ขยับเลย คือความรู้สึกว่าตัวเองเสี่ยงจะติดเชื้อ หนึ่งจุดแปดสามก่อนแคมเปญ หนึ่งจุดแปดสองหลังแคมเปญ ไม่ต่างกัน ส่วนความรู้สึกว่าโรคนี้ร้ายแรง กลับลดลงเล็กน้อย จากหนึ่งจุดเจ็ดแปด เป็นหนึ่งจุดหกห้า พอรู้ว่ารักษาได้ และมีสิทธิรักษา ความกลัวก็ลดลง",
                  "But the one thing that did not move at all was people's sense that they themselves were at risk: one point eight three before the campaign, one point eight two after. No change. And the sense that the disease is severe actually eased slightly, from one point seven eight to one point six five. Once people knew it could be treated, and that they had a right to treatment, the fear came down.",
                  "สิ่งที่ไม่ขยับ", "What did not move",
                  "รู้สึกเสี่ยง 1.83 → 1.82 ไม่ขยับ · รู้สึกว่าร้ายแรง 1.78 → 1.65 ลดลง",
                  "Felt at risk 1.83 → 1.82 · unchanged · felt severe 1.78 → 1.65 · eased",
                  "แถบกระดาษตรงหนึ่งเส้นวางราบเรียบขนานพื้น — เส้นที่ไม่ขยับ",
                  "ONE flat straight paper strip lying perfectly level across the middle of the frame, like a flat line. One object, nothing else."),
            scene("lesson", 23,
                  "บทเรียนสำหรับคนออกแบบแคมเปญสุขภาพก็คือ ผลที่ไม่ขยับมีค่าพอกับผลที่ขยับ แคมเปญนี้ทำให้คนรู้มากขึ้น มั่นใจขึ้น และขยับพฤติกรรม โดยไม่ต้องทำให้เขารู้สึกว่าตัวเองเสี่ยงก่อนเลย แปลว่าการเปลี่ยนพฤติกรรมไม่จำเป็นต้องพึ่งความกลัว และปัจจัยที่ทีมวิจัยยกให้เป็นหัวใจ คือแรงงานเป็นคนออกแบบและจัดงานเอง คนในโรงงานฟังเพื่อนร่วมงานที่พูดภาษาเดียวกัน มากกว่าฟังสื่อชิ้นไหน ทีมวิจัยจึงเสนอให้หน่วยงานรัฐใช้แรงงานที่ผ่านการอบรม กับซุ้มเกม เป็นสื่อหลัก",
                  "The lesson for anyone designing a health campaign is that what did not move is worth as much as what did. This campaign made people know more, feel more confident and shift their behaviour, without ever making them feel personally at risk. So changing behaviour does not have to run on fear. And the factor the team puts at the heart of it is that the workers designed and ran the campaign themselves. People in the factory listened to co-workers who spoke their language more than to any piece of media. The team's recommendation to government agencies is to make trained workers and game booths the main channel.",
                  "บทเรียน", "The lesson",
                  "ไม่ต้องทำให้กลัว ก็เปลี่ยนพฤติกรรมได้ · เพื่อนร่วมงานที่พูดภาษาเดียวกัน คือสื่อที่ได้ผลที่สุด",
                  "Behaviour can change without fear · co-workers who speak your language are the best channel",
                  "โทรโข่งกระดาษพับหนึ่งอันวางตะแคง — เสียงตามสายที่อาสาสมัครอ่านเอง",
                  "ONE small folded paper megaphone lying on its side. One object, nothing else."),
            caveat("ข้อควรระวัง เป็นการศึกษาในโรงงานเดียวที่สมุทรสาคร เก็บข้อมูลปีสองพันห้าร้อยหกสิบ ไม่มีกลุ่มเปรียบเทียบ จึงแยกไม่ได้เต็มที่ว่าผลมาจากแคมเปญล้วน พฤติกรรมวัดจากที่แรงงานบอกเอง ไม่ได้สังเกตจริง และคนที่ตอบเป็นแรงงานอายุยี่สิบถึงสามสิบปีที่พูดภาษาเมียนมาได้ดี",
                   "One caution: this is one factory in Samut Sakhon, with data from twenty seventeen and no comparison group, so the effect cannot be fully separated from everything else going on. Behaviour is what the workers said they did, not what anyone observed. And the people surveyed were workers aged twenty to thirty who spoke Myanmar well.",
                   "โรงงานเดียว ปี 2560 · ไม่มีกลุ่มเปรียบเทียบ · พฤติกรรมจากคำบอกเอง",
                   "One factory, 2017 · no comparison group · self-reported behaviour", secs=(11, 11)),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "engage", "batch": 5,
        "slug": "engage-a3-model",
        "name_th": "แบบจำลอง ENGAGE-A3 สื่อสารเรื่องเอดส์กับแรงงานข้ามชาติ",
        "name_en": "The ENGAGE-A3 model for HIV communication with migrant workers",
        "label": {"th": "งานวิจัย · สื่อสารสุขภาพ", "en": "Research · Health communication"},
        "scenes": [
            scene("hook", 9,
                  "งานสื่อสารเรื่องเอดส์กับแรงงานข้ามชาติ มักเริ่มที่การผลิตสื่อ … แต่ผู้เชี่ยวชาญบอกว่า สิ่งที่ต้องมาก่อนคือความไว้วางใจ",
                  "HIV communication with migrant workers usually starts by producing materials … but the experts said what has to come first is trust.",
                  "งานวิจัย · สื่อสารสุขภาพ", "Research · Health communication",
                  "เริ่มที่ความไว้วางใจ ไม่ใช่เริ่มที่ตัวสื่อ",
                  "Start with trust, not with materials",
                  "ภาพประจำบทความ (มีแล้ว): สะพานโค้งที่วางอยู่บนฐานซึ่งถูกวางไว้ก่อน", None, image="existing"),
            scene("method", 17,
                  "ทีมวิจัยสร้างแบบจำลองขึ้นจากบทเรียนภาคสนามของตัวเอง กับงานวิจัยที่มีมาก่อน แล้วนำเข้าวงสนทนากับผู้เชี่ยวชาญสิบคน ทั้งอาจารย์มหาวิทยาลัยและมืออาชีพด้านการสื่อสาร สาธารณสุข แรงงานข้ามชาติ และการลดความเสี่ยงด้านสุขภาพ ทุกคนมีประสบการณ์เกินสิบปี ให้ช่วยให้คะแนนว่าแต่ละขั้นเหมาะสมแค่ไหน จากหนึ่งถึงห้า",
                  "The research team built the model from their own field lessons and earlier research, then took it to a focus group of ten experts: university lecturers and professionals in communication, public health, migration and health risk reduction, each with more than ten years' experience. The experts scored how appropriate each step was, from one to five.",
                  "ทำอะไร", "What was done",
                  "ผู้เชี่ยวชาญ 10 คน · ประสบการณ์เกิน 10 ปี · ให้คะแนน 1–5 ทีละขั้น",
                  "Ten experts · 10+ years each · scored 1–5 per step",
                  "โต๊ะกลมกระดาษหนึ่งตัวมองจากด้านบน มีเก้าอี้กระดาษเล็กสี่ตัวรอบโต๊ะ (บรีฟสั่งสามตัว ภาพที่ได้มีสี่ตัว ใช้ได้เพราะจำนวนไม่สื่อความหมาย) — วงสนทนาผู้เชี่ยวชาญ",
                  "ONE round flat paper disc like a table seen from above, with exactly THREE small folded paper chairs spaced around its edge. Four objects, nothing else."),
            scene("finding", 18,
                  "ได้แบบจำลองชื่อเอ็นเกจ เอ สาม มีหกขั้น สร้างความไว้วางใจก่อน สำรวจบริบทของพื้นที่ หาคนในพื้นที่มาช่วย ลงมือทำ ทำให้เป็นเกม แล้วประเมินผล ปลายทางคือสามอย่าง คนประเมินความเสี่ยงของตัวเองได้ ตระหนักถึงความเสี่ยง และลุกขึ้นมาเป็นปากเสียงให้เรื่องนี้",
                  "The result is a model called ENGAGE A-three, with six steps: earn trust first, scan the setting, get local people to help, act, turn it into a game, and evaluate. It aims at three outcomes: people can assess their own risk, they become aware of it, and some of them start speaking up about it.",
                  "หกขั้น", "Six steps",
                  "ไว้วางใจ · สำรวจบริบท · คนในพื้นที่ · ลงมือทำ · ทำเป็นเกม · ประเมินผล",
                  "Trust · scan · local help · act · gamify · evaluate",
                  "แถบกระดาษยาวหนึ่งเส้นพับซิกแซกเป็นขั้นบันไดไต่ขึ้น — หกขั้นในชิ้นเดียว (ไม่นับจำนวน)",
                  "ONE long paper strip folded into a rising zigzag staircase shape, standing on its edge and seen from a low side angle. One object, nothing else."),
            scene("finding", 16,
                  "ผู้เชี่ยวชาญให้คะแนนรวมสี่จุดสองหกจากห้า อยู่ในระดับเหมาะสมมาก และสองขั้นที่ได้คะแนนสูงสุดเท่ากันคือ การสร้างความไว้วางใจ กับการทำให้เป็นเกม สี่จุดสี่ห้าทั้งคู่ รองลงมาคือการหาคนในพื้นที่มาช่วย กับการลงมือทำ สี่จุดสามหกทั้งคู่",
                  "The experts gave the model four point two six out of five overall, in the very appropriate band. The two steps they rated highest, tied at four point four five, were earning trust and turning it into a game. Next came getting local help and taking action, at four point three six each.",
                  "คะแนนจากผู้เชี่ยวชาญ", "The experts' scores",
                  "รวม 4.26 จาก 5 · ไว้วางใจ 4.45 · ทำเป็นเกม 4.45 · คนในพื้นที่ 4.36 · ลงมือทำ 4.36",
                  "Overall 4.26 of 5 · trust 4.45 · gamify 4.45 · local help 4.36 · act 4.36",
                  "แท่งกระดาษสี่แท่งตั้งเรียงกัน สองแท่งแรกสูงเท่ากัน สองแท่งหลังเตี้ยกว่าเล็กน้อยเท่ากัน — สองคู่คะแนน",
                  "exactly FOUR flat paper rectangular bars standing upright in a row: the first two the same tall height, the last two the same slightly shorter height. Four objects, nothing else."),
            scene("finding", 16,
                  "ขั้นที่ได้คะแนนต่ำสุดคือการประเมินผล สี่จุดสิบแปด ยังอยู่ระดับเหมาะสม แต่ไม่ถึงเหมาะสมมาก ทีมวิจัยอ่านว่า เป็นเพราะงานสื่อสารสุขภาพจำนวนมากวัดแค่ว่าคนรู้อะไรเพิ่ม กับพอใจไหม แต่ไม่ได้วัดว่าพฤติกรรมเปลี่ยนจริงหรือเปล่า และในปลายทางสามอย่าง การประเมินความเสี่ยงของตัวเองได้คะแนนสูงกว่า ความตระหนักกับการเป็นปากเสียง ซึ่งได้สี่จุดศูนย์เท่ากัน",
                  "The step rated lowest was evaluation, at four point one eight: still appropriate, but not very appropriate. The team's reading is that too many health campaigns measure only what people learned and whether they were satisfied, not whether behaviour actually changed. And of the three outcomes, self-assessment scored higher than awareness and advocacy, which tied at four point oh.",
                  "ขั้นที่ได้คะแนนต่ำสุด", "The lowest-scoring step",
                  "ประเมินผล 4.18 ต่ำสุด · วัดแค่รู้กับพอใจ ไม่พอ · ตระหนักและเป็นปากเสียง 4.00",
                  "Evaluation 4.18, lowest · knowing and liking are not enough · awareness and advocacy 4.00",
                  "ไม้บรรทัดกระดาษหนึ่งอันวางเฉียง ปลายด้านไกลพับงอลงเล็กน้อย — เครื่องวัดที่ยังไม่ครบ",
                  "ONE flat paper ruler with short tick marks along one edge, lying diagonally, its far end folded slightly downward. One object, nothing else."),
            scene("lesson", 23,
                  "บทเรียนสำหรับคนทำงานสื่อสารสุขภาพกับกลุ่มเปราะบางก็คือ ลำดับสำคัญกว่าเครื่องมือ สิ่งที่ผู้เชี่ยวชาญให้น้ำหนักสูงสุด คือสิ่งที่ต้องทำก่อนจะมีสื่อชิ้นแรกเสียอีก คือสร้างความไว้วางใจ และดึงคนในพื้นที่มาเป็นเจ้าของงาน ถ้าเริ่มที่โปสเตอร์ก่อน คนก็มองว่าเป็นคนนอกมาสั่ง แต่ถ้าเริ่มที่ความไว้วางใจ คนในพื้นที่จะพาสื่อไปถึงคนของเขาเอง องค์กรที่กำลังวางแคมเปญกับแรงงานข้ามชาติ เอาหกขั้นนี้ไปเป็นโครงได้เลย",
                  "The lesson for anyone doing health communication with a vulnerable group is that the order matters more than the tools. What the experts weighted most heavily is what has to happen before the first poster exists: earning trust, and bringing local people in as owners of the work. Start with the poster and people see outsiders giving orders. Start with trust and local people carry the message to their own. An organisation planning a campaign with migrant workers can take the six steps as its scaffold.",
                  "บทเรียน", "The lesson",
                  "ลำดับสำคัญกว่าเครื่องมือ · ไว้วางใจก่อนมีสื่อชิ้นแรก · ให้คนในพื้นที่เป็นเจ้าของงาน",
                  "Order beats tools · trust before the first poster · let local people own it",
                  "กุญแจกระดาษหนึ่งดอก กับประตูกระดาษบานเล็กที่แง้มอยู่ในกรอบ วางคู่กัน — ความไว้วางใจที่เปิดประตู",
                  "ONE small flat paper key and ONE small paper door standing slightly ajar in its frame, side by side with a small gap between them. Two objects, nothing else."),
            caveat("ข้อควรระวัง งานนี้วัดความเห็นของผู้เชี่ยวชาญสิบคน ว่าแบบจำลองเหมาะสมแค่ไหน ไม่ได้วัดผลลัพธ์ทางสุขภาพในภาคสนาม ส่วนนั้นอยู่ในงานปีสองพันห้าร้อยหกสิบสองของทีมเดียวกัน ซึ่งเราเล่าไว้ในอีกคลิปหนึ่ง และผู้เชี่ยวชาญสิบคนเป็นวงเล็ก ทีมวิจัยระบุเองว่าถ้าได้คนจากสาขาอื่นเพิ่ม ผลอาจต่างออกไป",
                   "One caution: this study measures ten experts' opinion of how appropriate the model is. It does not measure health outcomes in the field; that is the same team's study from twenty nineteen, which we tell in another clip. And ten experts is a small circle: the authors themselves say that adding people from other fields could change the result.",
                   "ความเห็นผู้เชี่ยวชาญ 10 คน · ไม่ได้วัดผลในภาคสนาม · วงเล็ก",
                   "Ten experts' opinion · no field outcomes measured · a small circle", secs=(11, 11)),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "gameinf", "batch": 5,
        "slug": "game-influencer-credibility",
        "name_th": "ความน่าเชื่อถือของอินฟลูเอนเซอร์เกม",
        "name_en": "A gaming influencer's credibility",
        "label": {"th": "งานวิจัย · การตลาดอินฟลูเอนเซอร์", "en": "Research · Influencer marketing"},
        "scenes": [
            scene("hook", 9,
                  "อินฟลูเอนเซอร์เกมที่น่าเชื่อถือ ทำให้แฟนอยากซื้อเกมที่เขาเล่นจริงไหม … คำตอบคือจริง แต่ถ้าวัดผิดวิธี จะเห็นเหมือนมีแค่ความไว้ใจที่ทำงาน",
                  "Does a credible gaming influencer make fans want to buy the games he plays? … Yes. But measure it the wrong way, and it looks as if only trust is doing the work.",
                  "งานวิจัย · การตลาดอินฟลูเอนเซอร์", "Research · Influencer marketing",
                  "น่าเชื่อถือแล้วอยากซื้อจริง แต่แยกวัดทีละส่วน จะเห็นแค่ความไว้ใจ",
                  "Credibility does sell. Split it into parts and only trust seems to work",
                  "ภาพประจำบทความ (มีแล้ว): แถบกระดาษสามเส้นทอดจากขอบซ้ายมาบรรจบที่ลูกบาศก์ลูกเดียว", None, image="existing"),
            scene("method", 17,
                  "ทีมวิจัยทำแบบสอบถามออนไลน์กับผู้ติดตามยูทูบเบอร์สายเกมรายใหญ่ระดับโลกคนหนึ่ง จากหลายประเทศ ได้มาสี่ร้อยสิบสี่คน คัดเหลือสองร้อยสามสิบแปดคนที่ผ่านเกณฑ์ ส่วนใหญ่เป็นผู้ชาย อายุราวยี่สิบเอ็ดถึงยี่สิบสองปี ตามดูมาเฉลี่ยกว่าสี่ปี ถามว่ามองเขาน่าดึงดูดไหม ไว้ใจได้ไหม เก่งเกมไหม แล้วอยากซื้อเกมที่เขาเล่นแค่ไหน แล้วลองวิเคราะห์สองแบบเทียบกัน",
                  "The research team ran an online survey of followers of one of the world's biggest gaming YouTubers, PewDiePie, from many countries. Four hundred and fourteen answered, and two hundred and thirty-eight met the criteria: mostly men, around twenty-one to twenty-two years old, who had watched him for over four years on average. They were asked whether they found him attractive, trustworthy and skilled, and how much they wanted to buy the games he plays. Then the team analysed it two different ways and compared.",
                  "ทำอะไร", "What was done",
                  "ผู้ติดตามยูทูบเบอร์สายเกม PewDiePie · ตอบ 414 คน ผ่านเกณฑ์ 238 คน · ชาย 77% · วิเคราะห์ 2 แบบเทียบกัน",
                  "PewDiePie's followers · 414 answered · 238 eligible · men 77% · two models compared",
                  "จอยเกมกระดาษพับหนึ่งอัน มีปุ่มกลมกระดาษสองปุ่ม — ผู้ติดตามสายเกม",
                  "ONE small folded paper game controller lying flat, with two small round paper buttons on its right side. One object, nothing else."),
            scene("finding", 16,
                  "แบบแรก วัดทีละส่วน ทั้งสามอย่างสัมพันธ์กับความอยากซื้อ ความไว้ใจได้แรงที่สุด จุดห้าหนึ่ง ความน่าดึงดูด จุดสี่หก และความเชี่ยวชาญ จุดสามสาม แต่พอเอาทั้งสามใส่พร้อมกันในแบบจำลองเดียว ให้แข่งกันอธิบายความอยากซื้อ เหลือแค่ความไว้ใจได้ที่ยังมีผล อีกสองอย่างหายไปเลย",
                  "The first way measured each part on its own. All three went with wanting to buy: trustworthiness the strongest at point five one, attractiveness at point four six, expertise at point three three. But put all three into one model at once, each competing to explain the wish to buy, and only trustworthiness kept its effect. The other two simply vanished.",
                  "วัดทีละส่วน", "Measured one by one",
                  "ไว้ใจได้ .51 · น่าดึงดูด .46 · เชี่ยวชาญ .33 · ใส่พร้อมกัน เหลือแค่ความไว้ใจ",
                  "Trust .51 · attractiveness .46 · expertise .33 · together, only trust survives",
                  "แถบกระดาษสามเส้นวางขนานกัน ยาวใกล้เคียงกัน (บรีฟสั่งให้เส้นกลางยาวที่สุด ภาพที่ได้ยาวแทบเท่ากัน ตัวเลขบนจอเป็นตัวบอกความต่าง) — สามส่วน",
                  "exactly THREE flat paper strips lying parallel to each other; the middle strip is the longest and the other two are shorter. Three objects, nothing else."),
            scene("finding", 17,
                  "ทีมวิจัยชี้ว่านี่คือปัญหาที่เรียกว่า ตัวควบคุมที่ไม่ควรควบคุม สามอย่างนี้เป็นด้านของสิ่งเดียวกัน คนที่มองว่าเขาไว้ใจได้ ก็มักมองว่าน่าดึงดูดด้วย สัมพันธ์กันถึงจุดแปด พอให้แข่งกันเองในสมการ มันเลยกลบผลของกันและกัน แบบที่สองจึงจัดเป็นความน่าเชื่อถือก้อนเดียวที่มีสามด้าน เส้นทางไปถึงความอยากซื้อเท่ากับจุดห้าสี่ และแบบจำลองเข้ากับข้อมูลได้ดี",
                  "The team's point is that this is what statisticians call a bad-controls problem. The three are facets of the same thing: people who found him trustworthy also tended to find him attractive, the two went together at point eight. Made to compete inside one equation, they cancel each other out. So the second way treats credibility as a single thing with three sides. Its path to wanting to buy comes to point five four, and the model fits the data well.",
                  "วัดเป็นก้อนเดียว", "Measured as one thing",
                  "ไว้ใจกับน่าดึงดูด สัมพันธ์กัน .80 · ให้แข่งกันเอง ผลกลบกัน · รวมเป็นก้อนเดียว เส้นทาง .54",
                  "Trust and attractiveness go together at .80 · made to compete, they cancel · as one construct, path .54",
                  "ลูกบาศก์กระดาษพับหนึ่งลูกมองจากมุม เห็นสามด้านที่เฉดต่างกันเล็กน้อย — สิ่งเดียวที่มีสามด้าน",
                  "ONE folded paper cube seen from a corner so that three faces are visible, each face a slightly different shade of the same colour. One object, nothing else."),
            scene("finding", 14,
                  "แต่ถึงจะน่าเชื่อถือ แฟนก็ไม่ได้ตั้งใจซื้อมากนัก คะแนนความอยากซื้อเฉลี่ยอยู่ราวกลางมาตร สามจุดหนึ่งสี่ถึงสามจุดสี่ห้าจากห้า ทั้งที่ตามดูเป็นประจำ และมองว่าเขาสนุก สี่จุดสองสี่ บันเทิง สี่จุดสามสี่ มีประสบการณ์ สี่จุดสาม การตามดูกับการซื้อจึงเป็นคนละเรื่อง",
                  "Yet even with that credibility, fans were not especially set on buying. The wish to buy sat around the middle of the scale, three point one four to three point four five out of five, even though they watched regularly and rated him funny at four point two four, entertaining at four point three four and experienced at four point three. Watching and buying are different things.",
                  "ตามดู ไม่เท่ากับซื้อ", "Watching is not buying",
                  "อยากซื้อ 3.14–3.45 จาก 5 กลางมาตร · สนุก 4.24 · บันเทิง 4.34 · มีประสบการณ์ 4.30",
                  "Purchase intention 3.14–3.45 of 5, mid-scale · funny 4.24 · entertaining 4.34 · experienced 4.30",
                  "รถเข็นช้อปปิ้งกระดาษพับคันเล็กหนึ่งคัน ว่างเปล่า มองจากด้านข้าง — ตามดูแต่ยังไม่ซื้อ",
                  "ONE small folded paper shopping cart, empty, seen from the side. One object, nothing else."),
            scene("lesson", 23,
                  "บทเรียนสำหรับแบรนด์ที่จะทำงานกับอินฟลูเอนเซอร์เกมก็คือ อย่าเลือกคนด้วยการติ๊กทีละข้อ ว่าหน้าตาดี หรือเล่นเก่ง สิ่งที่ทำงานคือความน่าเชื่อถือโดยรวมที่คนดูรับรู้ ซึ่งมีความไว้ใจได้เป็นแกน ส่วนบทเรียนสำหรับนักวิจัยก็คือ ผลที่ดูเหมือนว่าความน่าดึงดูดกับความเชี่ยวชาญไม่มีผล อาจเป็นผลข้างเคียงของสมการ ไม่ใช่ข้อเท็จจริงเกี่ยวกับคนดู และคะแนนอยากซื้อที่อยู่กลางมาตร เตือนว่ายอดผู้ติดตามไม่ใช่ยอดขาย",
                  "The lesson for a brand about to work with a gaming influencer is not to pick someone by ticking boxes, good-looking here, skilled there. What works is the overall credibility the audience perceives, with trust at its core. The lesson for researchers is that a result which seems to say attractiveness and expertise do not matter may be a side effect of the equation, not a fact about the audience. And a wish to buy that sits mid-scale is a reminder that follower counts are not sales.",
                  "บทเรียน", "The lesson",
                  "อย่าเลือกด้วยการติ๊กทีละข้อ · ความน่าเชื่อถือรวม แกนคือความไว้ใจ · ยอดผู้ติดตาม ไม่ใช่ยอดขาย",
                  "Don't pick by ticking boxes · overall credibility, trust at the core · followers are not sales",
                  "ช่องสี่เหลี่ยมกระดาษเล็กสามช่องเรียงกัน กับเครื่องหมายถูกกระดาษอันใหญ่หนึ่งอันวางคร่อมทั้งสามช่อง — ติ๊กรวม ไม่ติ๊กทีละข้อ",
                  "exactly THREE small flat paper squares in a row and ONE large flat paper tick mark lying across all three of them. Four objects, nothing else."),
            caveat("ข้อควรระวัง เป็นการวัด ณ จุดเวลาเดียว บอกได้ว่าอะไรไปด้วยกัน ไม่ได้พิสูจน์ว่าความน่าเชื่อถือทำให้ซื้อ คนตอบเป็นผู้ติดตามอินฟลูเอนเซอร์คนเดียวและสมัครใจตอบ ส่วนใหญ่เป็นชายอายุยี่สิบต้น ความอยากซื้อวัดจากคำบอก ไม่ใช่การซื้อจริง มาตรวัดความเชี่ยวชาญมีแค่สองข้อและความเที่ยงต่ำ และเก็บข้อมูลช่วงโควิดที่กิจกรรมย้ายไปออนไลน์มากผิดปกติ ชื่อยูทูบเบอร์ที่ขึ้นบนจอระบุไว้เพราะเป็นขอบเขตของงาน บทความไม่ได้วิจารณ์ตัวเขา",
                   "One caution: this is a single point in time. It shows what goes together, not that credibility causes buying. The people surveyed follow one influencer and volunteered to answer; most are men in their early twenties. The wish to buy is what people said, not actual purchases. The expertise scale had only two items and low reliability. And the data comes from the COVID period, when life had moved online to an unusual degree. The YouTuber is named because he is the scope of the study; the article makes no criticism of him.",
                   "จุดเวลาเดียว ไม่พิสูจน์เหตุ · อินฟลูเอนเซอร์คนเดียว · วัดจากคำบอก · ช่วงโควิด",
                   "One time point, no causation · one influencer · self-reported · COVID period", secs=(12, 12)),
            closing(),
        ],
    },
    # ───────────────────────────────────────────────────────────────────────────
    {
        "key": "crypto", "batch": 5,
        "slug": "cryptocurrency-adoption-reddit",
        "name_th": "คริปโตกับคนใช้เรดดิต คุณค่าที่เห็นกับความเสี่ยงที่รับรู้",
        "name_en": "Crypto on Reddit: perceived value versus perceived risk",
        "label": {"th": "งานวิจัย · การสื่อสารการเงิน", "en": "Research · Financial communication"},
        "scenes": [
            scene("hook", 9,
                  "คนที่ลงทุนคริปโตอยู่แล้ว ถูกความเสี่ยงดึงถอยไหม … ทีมวิจัยถามคนใช้เรดดิตสองร้อยคน แล้วพบว่า ที่พาคนเข้ามาคือคุณค่าที่เห็น ส่วนความเสี่ยงที่รับรู้ แทบไม่มีผล",
                  "Do people already in crypto get pulled back by the risk? … The research team asked two hundred Reddit users and found that what draws people in is the value they see. The risk they perceive barely registers.",
                  "งานวิจัย · การสื่อสารการเงิน", "Research · Financial communication",
                  "คุณค่าที่เห็น พาเข้ามา · ความเสี่ยงที่รับรู้ ไม่ดึงถอย",
                  "Perceived value pulls people in. Perceived risk does not pull them back",
                  "ภาพประจำบทความ (มีแล้ว): ตราชั่งสามตัวเอียงคนละองศา", None, image="existing"),
            scene("method", 17,
                  "ทีมวิจัยโพสต์แบบสอบถามในชุมชนคริปโตบนเรดดิต ช่วงปลายปีสองพันห้าร้อยหกสิบห้า มีคนตอบมาหนึ่งพันสี่ร้อยสี่สิบสี่คน คัดเหลือสองร้อยคนที่ผ่านเกณฑ์และไม่ซ้ำกัน หญิงกับชายพอกัน ส่วนใหญ่อายุยี่สิบห้าถึงสี่สิบสี่ปี และเจ็ดสิบเปอร์เซ็นต์ถือบิตคอยน์อยู่ ถามว่าเห็นคุณค่าของคริปโตแค่ไหน มองว่าเสี่ยงแค่ไหน แล้วยอมรับการลงทุนนี้แค่ไหน พร้อมข้อมูลอายุ การศึกษา รายได้ และประสบการณ์ลงทุน",
                  "The research team posted a survey in a cryptocurrency community on Reddit in late twenty twenty-two. One thousand four hundred and forty-four people answered, screened down to two hundred who qualified and were not duplicates: men and women in equal measure, mostly aged twenty-five to forty-four, and seventy percent holding Bitcoin. They were asked how much value they saw in crypto, how risky they thought it was, and how far they accepted it as an investment, along with their age, education, income and investing experience.",
                  "ทำอะไร", "What was done",
                  "คนใช้เรดดิต ตอบ 1,444 คน คัดเหลือ 200 คน · อายุ 25–44 ปี เป็นส่วนใหญ่ · ถือบิตคอยน์ 70%",
                  "1,444 Reddit users answered, 200 kept · mostly aged 25–44 · 70% hold Bitcoin",
                  "เหรียญกระดาษกลมหนึ่งเหรียญ ขอบนูนเรียบ วางบนพื้น — หนึ่งเหรียญ",
                  "ONE flat round paper coin with a plain raised rim, lying on the surface. One object, nothing else."),
            scene("finding", 15,
                  "คุณค่าที่เห็นเป็นตัวเดียวที่ทำงานแรง คนที่มองว่าคริปโตให้ผลตอบแทนสูง กระจายความเสี่ยงได้ หรือเป็นเทคโนโลยีที่ก้าวหน้า ยอมรับการลงทุนนี้มากกว่าชัดเจน ผลของมันใหญ่มากในทางสถิติ และแบบจำลองทั้งหมดอธิบายการยอมรับได้ราวห้าสิบสี่เปอร์เซ็นต์",
                  "Perceived value was the one thing that worked, and worked hard. People who saw crypto as offering high returns, diversification or advanced technology accepted it far more readily. The effect was large by statistical standards, and the whole model explained about fifty-four percent of acceptance.",
                  "คุณค่าที่เห็น", "Perceived value",
                  "คุณค่าที่เห็น มีผลใหญ่ · อธิบายการยอมรับได้ 54%",
                  "Perceived value: a large effect · explains 54% of acceptance",
                  "แม่เหล็กกระดาษรูปเกือกม้าหนึ่งอันวางบนพื้น — สิ่งที่ดึงคนเข้ามา",
                  "ONE flat paper horseshoe-magnet shape lying on the surface, its two arms pointing to the right. One object, nothing else."),
            scene("finding", 16,
                  "ส่วนความเสี่ยงที่รับรู้ กลับไม่มีผลต่อการยอมรับ คนที่มองว่าเสี่ยงสูง ก็ไม่ได้ยอมรับน้อยลงอย่างที่คาด ทีมวิจัยอ่านว่า คนกลุ่มนี้ทนความเสี่ยงได้สูงกว่าคนทั่วไป และคุณค่าที่เห็นอาจกลบความเสี่ยงไปเลย ซึ่งสวนกับงานก่อนหน้าหลายชิ้นที่พบว่าความเสี่ยงดึงคนถอย",
                  "Perceived risk, on the other hand, had no real effect on acceptance. People who saw crypto as high risk did not accept it any less, contrary to what the team expected. Their reading is that this group tolerates risk more than most, and that the value they see may simply drown the risk out. That runs against several earlier studies where risk held people back.",
                  "ความเสี่ยงที่รับรู้", "Perceived risk",
                  "ความเสี่ยงที่รับรู้ ไม่มีผล · ทนความเสี่ยงได้สูงกว่าคนทั่วไป · สวนกับงานก่อนหน้า",
                  "Perceived risk: no effect · a high-tolerance crowd · against earlier studies",
                  "ป้ายเตือนสามเหลี่ยมกระดาษหนึ่งอันล้มนอนหงายอยู่กับพื้น — คำเตือนที่ไม่มีผล",
                  "ONE flat triangular paper warning sign lying flat on its back on the surface, as if knocked over. One object, nothing else."),
            scene("finding", 15,
                  "แล้วใครเป็นใครมีผลไหม จากห้าอย่างที่ถาม มีแค่ระดับการศึกษาที่มีผล คนที่เรียนสูงกว่ายอมรับการลงทุนนี้มากกว่า ส่วนอายุ เพศ รายได้ และประสบการณ์ลงทุน ไม่มีผลเลย และคนตอบส่วนใหญ่ประเมินตัวเองว่ารู้เรื่องคริปโตแค่นิดหน่อยถึงปานกลาง ที่บอกว่าเป็นผู้เชี่ยวชาญมีแค่สองจุดห้าเปอร์เซ็นต์",
                  "Does who you are matter? Of the five things asked, only education did: people with more schooling accepted the investment more readily. Age, gender, income and investing experience made no difference at all. And most of those surveyed rated their own crypto knowledge as a little to moderate; only two point five percent called themselves experts.",
                  "ใครเป็นใคร", "Who they are",
                  "การศึกษาเท่านั้นที่มีผล · อายุ เพศ รายได้ ประสบการณ์ ไม่มีผล · เรียกตัวเองว่าผู้เชี่ยวชาญ 2.5%",
                  "Only education mattered · age, gender, income, experience did not · 2.5% call themselves experts",
                  "หมวกรับปริญญากระดาษพับหนึ่งใบ มีพู่สั้นห้อยหนึ่งเส้น มองเฉียงเล็กน้อย — การศึกษา",
                  "ONE small folded paper graduation cap, a flat square mortarboard with ONE short paper tassel, seen from a slight angle. One object, nothing else."),
            scene("lesson", 23,
                  "บทเรียนสำหรับคนทำงานสื่อสารการเงินก็คือ กับคนที่อยู่ในตลาดคริปโตอยู่แล้ว การเน้นเตือนความเสี่ยงอย่างเดียวแทบไม่เปลี่ยนอะไร เพราะสิ่งที่ตัดสินใจให้เขาคือคุณค่าที่เขาเห็น ถ้าอยากให้คนลงทุนอย่างรู้เท่าทัน ต้องพูดเรื่องความเสี่ยงให้อยู่ในภาษาเดียวกับคุณค่า และเพราะการศึกษาเป็นตัวเดียวที่มีผล ทีมวิจัยจึงเสนอให้ลงทุนกับความรู้ทางการเงิน ทั้งในหลักสูตรและในชุมชนออนไลน์ที่คนกลุ่มนี้อยู่จริง มากกว่าจะไปไล่เตือนตามแพลตฟอร์ม",
                  "The lesson for anyone communicating about finance is that with people already in the crypto market, warning about risk on its own changes almost nothing, because what decides for them is the value they see. If you want people to invest with their eyes open, risk has to be talked about in the same language as value. And since education was the one thing that mattered, the team's proposal is to invest in financial literacy, in curricula and in the online communities where these people actually are, rather than chasing them with warnings.",
                  "บทเรียน", "The lesson",
                  "เตือนความเสี่ยงอย่างเดียว ไม่เปลี่ยนอะไร · พูดความเสี่ยงในภาษาเดียวกับคุณค่า · ลงทุนกับความรู้ทางการเงิน",
                  "Warnings alone change nothing · talk risk in the language of value · invest in financial literacy",
                  "หนังสือกระดาษเล่มเล็กหนึ่งเล่มวางเปิดอยู่ มองจากด้านบน — ความรู้ทางการเงิน",
                  "ONE small folded paper book lying open, seen from above, its two pages blank. One object, nothing else."),
            caveat("ข้อควรระวัง คนตอบสองร้อยคนจากชุมชนเรดดิตเดียว และเป็นคนที่ลงทุนคริปโตอยู่แล้ว ไม่ใช่ตัวแทนของนักลงทุนทั่วไปหรือคนไทย และมีเรื่องหนึ่งที่ต้องบอกให้ชัด บทคัดย่อของบทความเขียนว่าความเสี่ยงมีผลทางลบ และอายุ เพศ รายได้ เป็นตัวปรับ แต่ตารางผลและบทสรุปของบทความเองบอกตรงข้าม คลิปนี้และบทสรุปบนเว็บของเรายึดตามตารางผล",
                   "One caution: two hundred people from a single Reddit community, all already investing in crypto. They stand for neither investors in general nor people in Thailand. And one thing has to be said plainly: the article's abstract says risk has a negative effect and that age, gender and income moderate it, but the article's own results tables and conclusion say the opposite. This clip, and our summary on the website, follow the results tables.",
                   "เรดดิตชุมชนเดียว 200 คน · ลงทุนอยู่แล้ว · บทคัดย่อกับตารางผลขัดกัน คลิปยึดตารางผล",
                   "One Reddit community, 200 people · already investors · abstract and results disagree, we follow the results", secs=(12, 12)),
            closing(),
        ],
    },
]
